### ISSUE TITLE
django.core.exceptions.ValidationError: ['The attribute "text" is required.'] on Microsoft Bot Emulator

### ISSUE THREAD

**Issue by shre81** [gunthercox/ChatterBot#1014]
Hello,

I tried connecting the Chatterbot Django app as an endpoint within the Bot Emulator. I was able to get it running but at the first instance of the connection, I encounter this error

``` Bash
django.core.exceptions.ValidationError: ['The attribute "text" is required.']
```

I have run the necessary migrations. FWIW, this is the line I'm running at the terminal:

``` Bash
python manage.py runserver 127.0.0.1:3978
```

and below is the error trace. Can anyone please help me understand what I'm doing wrong?

``` Bash
Internal Server Error: /api/chatterbot/
Traceback (most recent call last):
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/chatterbot/ext/django_chatterbot/views.py", line 63, in post
    self.validate(input_data)
  File "/Users/shreyasgopinath/Installs/anaconda/envs/py36/lib/python3.6/site-packages/chatterbot/ext/django_chatterbot/views.py", line 24, in validate
    raise ValidationError('The attribute "text" is required.')
django.core.exceptions.ValidationError: ['The attribute "text" is required.']
```

**Comment by vkosuri** [comment]
@shre81 Are you getting this error message after starting Django server or when you submit input to on the web form?

Usually the user input will make as an JSON object for example 
``` JSON
{"text" : "respose" }
```
https://github.com/gunthercox/ChatterBot/blob/857a83fe3d7ef341907b7aee5893f47a75a1e355/examples/django_app/example_app/templates/app.html#L84

After it will make POST request to Django server, it validates here 
https://github.com/gunthercox/ChatterBot/blob/857a83fe3d7ef341907b7aee5893f47a75a1e355/chatterbot/ext/django_chatterbot/views.py#L23

At this point it was broken.

**Comment by shre81** [comment]
@vkosuri This happens on startup. I noticed that when I send a message on the emulator, I get no response back (but I get a response back on the web form). 

Is there some Microsoft emulator specific changes I need to make in the example to make it work?

**Comment by gunthercox** [comment]
It seems that the code we have for connecting to the Microsoft Bot Framework is for an older version of the Bot Framework API. #1285 has been created for upgrading it.
