### ISSUE TITLE
Error Installing on mac OS x (Command "python setup.py egg_info" failed with error code 1)

### ISSUE THREAD

**Issue by engrphil** [gunthercox/ChatterBot#1055]
``` Bash
Collecting ruamel.yaml<=0.15 (from chatterbot-corpus<1.2,>=1.1->ChatterBot==0.7.6)
  Using cached ruamel.yaml-0.15.0.tar.gz
    Complete output from command python setup.py egg_info:
    /var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/tmp_ruamel_zrLror/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/tmp_ruamel_zrLror/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/tmp_ruamel_zrLror/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    /var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/tmp_ruamel_zrLror/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/tmp_ruamel_zrLror/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/tmp_ruamel_zrLror/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/pip-build-rppoxZ/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/pip-build-rppoxZ/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
        reqs = self.dist.requires(self.extras)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
        dm = self._dep_map
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
        if invalid_marker(marker):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
        env = cls._translate_metadata2(_markerlib.default_environment())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
        for key, value in env
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/lm/442twlkj54z9vpkbhwv7y1c80000gn/T/pip-build-rppoxZ/ruamel.yaml/
```

**Comment by vkosuri** [comment]
Hi @engrphil by looking into trace log, the installation failed unable to fetch ``ruamel`` requirement from pip, to avoid before installing ``chatterbot`` install ``ruamel``.

``` Bash
pip install ruamel.yaml --upgrade
```
The similar issue https://github.com/gunthercox/ChatterBot/issues/913#issuecomment-321088695

**Comment by engrphil** [comment]
Thank you. That resolves the issue, it turns out that I need to use sudo.

**Comment by zacharyyzhou** [comment]
I'm having the same issue. I tried pip install ruamel.yaml --upgrade but I got the same issue. I also have Mac OS X.

**Comment by engrphil** [comment]
try using sudo pip install ruamel.yaml --upgrade

**Comment by zacharyyzhou** [comment]
Same problem.

     File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-Hlbubl/ruamel.yaml/
