### ISSUE TITLE
Error Installing on mac OS x (Command "python setup.py egg_info")

### ISSUE THREAD

**Issue by zacharyyzhou** [gunthercox/ChatterBot#1077]
I am having the same issue someone else raised on this forum, but the solution on his post didn't work for me (i.e., I tried both sudo and pip install ruamel.yaml --upgrade. 
Collecting ruamel.yaml
  Downloading ruamel.yaml-0.15.34.tar.gz (260kB)
    100% |████████████████████████████████| 266kB 2.4MB/s 
    Complete output from command python setup.py egg_info:
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/gp/nx04ldr11cs2nt91drhj9ssc0000gn/T/pip-build-yVVKYG/ruamel.yaml/setup.py", line 917, in <module>
        main()
      File "/private/var/folders/gp/nx04ldr11cs2nt91drhj9ssc0000gn/T/pip-build-yVVKYG/ruamel.yaml/setup.py", line 905, in main
        setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
        reqs = self.dist.requires(self.extras)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
        dm = self._dep_map
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
        if invalid_marker(marker):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
        env = cls._translate_metadata2(_markerlib.default_environment())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
        for key, value in env
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/gp/nx04ldr11cs2nt91drhj9ssc0000gn/T/pip-build-yVVKYG/ruamel.yaml/

Same error with chatterbot as well.

**Comment by mikekeda** [comment]
I don't have this issue on MacOS High Sierra (I'm using Python 3.6.2)

**Comment by zacharyyzhou** [comment]
I am using MacOS High Sierra with Python 3.6.3.

**Comment by mikekeda** [comment]
but in your logs python2.7 and without virtualenv python 2 will be used by default
P.S. https://virtualenv.pypa.io/en/stable/

**Comment by vkosuri** [comment]
Hi @zacharyyzhou by looking into trace log, the installation failed unable to fetch ruamel requirement from pip, to avoid before installing chatterbot install ruamel.

```
pip install ruamel.yaml --upgrade
```

The similar issue #913 and https://github.com/gunthercox/ChatterBot/issues/1055

**Comment by zacharyyzhou** [comment]
I installed virtualenv, but I don't know how to change using python 2 by default. I tried typing python3 and changing the path using 
PATH="/Library/Frameworks/Python.framework/Versions/3.6.3/bin:${PATH}"
export PATH

but my version is still 2.7.10 (found out using python --version)

**Comment by zacharyyzhou** [comment]
I think I figured out how to use virtualenv since I got chatterbot to work. Thanks for the help everyone!

**Comment by vkosuri** [comment]
Glad to here that, could please you post your resolution steps, this might useful to resolve issues very quickly

**Comment by zacharyyzhou** [comment]
Yes. After installing virtualenv by following the published documentation, I downloaded chatterbot into its bin folder. I believe I typed env/bin/pip install chatterbot. I have no idea what version of python was used to install it, but the download was successful, and I was able to run the bot. A link I found helpful is the following: https://www.dabapps.com/blog/introduction-to-pip-and-virtualenv-python/

**Comment by juusujanar** [comment]
I got the same error when running with pip, which uses Python2 by default. I used pip3 to install the chatterbot for Python3 and that was successful.

**Comment by darshanddd7** [comment]
This is the error I' getting installing flask-mysqldb in virtualenv and installed all the above related files[ip install ruamel.yaml --upgrade],
[pip install python3.6-dev libmysqlclient-dev]--  Could not find a version that satisfies the requirement python3.6.3-dev (from versions: )
No matching distribution found for python3.6.3-dev
[pip install MySQL-python]--same below error


(env) Darshans-MacBook-Air:CrudWithFlask-4 ddd$ pip3 install flask-mysqldb
Collecting flask-mysqldb
  Using cached Flask-MySQLdb-0.2.0.tar.gz
Requirement already satisfied: Flask>=0.10 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from flask-mysqldb)
Collecting mysqlclient (from flask-mysqldb)
  Using cached mysqlclient-1.3.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-_jwc4c5a/mysqlclient/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-_jwc4c5a/mysqlclient/setup_posix.py", line 54, in get_config
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-_jwc4c5a/mysqlclient/setup_posix.py", line 54, in <listcomp>
        libraries = [dequote(i[2:]) for i in libs if i.startswith('-l')]
      File "/private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-_jwc4c5a/mysqlclient/setup_posix.py", line 12, in dequote
        if s[0] in "\"'" and s[0] == s[-1]:
    IndexError: string index out of range

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/l0/3dzllb2j4djb18jr5j82fvpr0000gn/T/pip-build-_jwc4c5a/mysqlclient/







which throw error,but still i'm unable to get rid of this error 
please help out with this issue

**Comment by mikekeda** [comment]
@darshanddd7 it's not related to ChatterBot

**Comment by darshanddd7** [comment]
@mikekeda
I didn't get ...what about the error code where do I get the solution

**Comment by mikekeda** [comment]
@darshanddd7 you can use google, check the documentation, post an issue at https://github.com/admiralobvious/flask-mysqldb

In general I think you don't have mysqlclient-python installed. I checked the flask-mysqldb, last code update was 2 years ago, so it could be the reason too.

Why to not use sqlalchemy?

**Comment by eraseandinstall** [comment]
> I got the same error when running with pip, which uses Python2 by default. I used pip3 to install the chatterbot for Python3 and that was successful.

Holy hell thank you.
