### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-7ByNxM/ruamel.yaml/

### ISSUE THREAD

**Issue by Kapowpenguin1** [gunthercox/ChatterBot#1087]
I tried to install chatterbot with a fresh install of pip. I used sudo, just for good measure. I don't know if there are specific, important parts, so I just pasted the whole activity. Apologies if I did it wrong.

```
Alberts-MacBook-Air:~ albertma$ sudo pip install chatterbot
The directory '/Users/albertma/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/albertma/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting chatterbot
  Downloading ChatterBot-0.7.6-py2.py3-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 920kB/s 
Collecting sqlalchemy<1.2,>=1.1 (from chatterbot)
  Downloading SQLAlchemy-1.1.15.tar.gz (5.2MB)
    100% |████████████████████████████████| 5.2MB 174kB/s 
Collecting chatterbot-corpus<1.1,>=1.0 (from chatterbot)
  Downloading chatterbot_corpus-1.0.1-py2.py3-none-any.whl (180kB)
    100% |████████████████████████████████| 184kB 3.0MB/s 
Collecting jsondatabase<1.0.0,>=0.1.7 (from chatterbot)
  Downloading jsondatabase-0.1.7-py2.py3-none-any.whl
Collecting python-twitter<4.0,>=3.0 (from chatterbot)
  Downloading python_twitter-3.3-py2-none-any.whl (72kB)
    100% |████████████████████████████████| 81kB 866kB/s 
Collecting pymongo<4.0,>=3.3 (from chatterbot)
  Downloading pymongo-3.5.1-cp27-none-macosx_10_12_x86_64.whl (270kB)
    100% |████████████████████████████████| 276kB 2.0MB/s 
Collecting python-dateutil<2.7,>=2.6 (from chatterbot)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |████████████████████████████████| 194kB 1.2MB/s 
Collecting nltk<4.0,>=3.2 (from chatterbot)
  Downloading nltk-3.2.5.tar.gz (1.2MB)
    100% |████████████████████████████████| 1.2MB 517kB/s 
Collecting ruamel.yaml<=0.15 (from chatterbot-corpus<1.1,>=1.0->chatterbot)
  Downloading ruamel.yaml-0.15.0.tar.gz (247kB)
    100% |████████████████████████████████| 256kB 1.2MB/s 
    Complete output from command python setup.py egg_info:
    /tmp/tmp_ruamel_O08QqP/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /tmp/tmp_ruamel_O08QqP/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /tmp/tmp_ruamel_O08QqP/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    /tmp/tmp_ruamel_O08QqP/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /tmp/tmp_ruamel_O08QqP/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /tmp/tmp_ruamel_O08QqP/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-6tgzrW/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/tmp/pip-build-6tgzrW/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
        reqs = self.dist.requires(self.extras)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
        dm = self._dep_map
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
        if invalid_marker(marker):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
        env = cls._translate_metadata2(_markerlib.default_environment())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
        for key, value in env
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-6tgzrW/ruamel.yaml/
```

**Comment by gunthercox** [comment]
Hi, @Kapowpenguin1, this line is the clue: `Collecting ruamel.yaml<=0.15 (from chatterbot-corpus<1.1,>=1.0->chatterbot)`

There is an existing error in the `ruamel.yaml` package that makes it fail during installation. I just released an update to the `chatterbot-corpus` module to remove `ruamel.yaml` and use `PyYaml` instead. This should fix the issue.

You can install the latest version of the `chatterbot-corpus` module by running:

```
pip install chatterbot-corpus>=1.1.1
```
