### ISSUE TITLE
Errors on adapters in very 1st tutorial

### ISSUE THREAD

**Issue by sbaity** [gunthercox/ChatterBot#1095]
Hi, trying to use the online tutorials but getting stymied on very first one.
Python 3.6.3
Chatterbot 0.7.6
I do not have the utils or adapter folders.

using this code:
``` Python
# -*- coding: utf-8 -*-

##import ChatterBot

from chatterbot import ChatBot

##create instance of chatBot class and create/define the database
## and input and output adapters
bot = ChatBot(
    'Norman',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    input_adapter='chatterbot.input.TerminalAdapter',
    output_adapter='chatterbot.output.TerminalAdapter',
    logic_adapters=[
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter'
    ],
    database='./database.sqlite3'
)

while True:
    try:
     bot_input = bot.get_response(None)

    except(KeyboardInterrupt, EOFError, SystemExit):
        break
```

type anything and the errors are:

``` Bash
Traceback (most recent call last):
  File "chatbot.py", line 23, in <module>
    bot_input = bot.get_response(None)
  File "/Users/smb/ChatterBot/chatterbot/chatterbot.py", line 113, in get_response
    statement, response = self.generate_response(input_statement, conversation_id)
  File "/Users/smb/ChatterBot/chatterbot/chatterbot.py", line 132, in generate_response
    response = self.logic.process(input_statement)
  File "/Users/smb/ChatterBot/chatterbot/logic/multi_adapter.py", line 50, in process
    if adapter.can_process(statement):
  File "/Users/smb/ChatterBot/chatterbot/logic/mathematical_evaluation.py", line 32, in can_process
    response = self.process(statement)
  File "/Users/smb/ChatterBot/chatterbot/logic/mathematical_evaluation.py", line 41, in process
    from mathparse import mathparse
ModuleNotFoundError: No module named 'mathparse'
```

I noticed that the mathematical_evaluation.py tries to import math parse (from mathparse import mathparse), but there is not mathparse directory to import from???
What am I doing wrong? Apologies if this is wrong place to post. Please direct me if so

**Comment by vkosuri** [comment]
could try to install mathparse, ``pip install mathparse``

**Comment by gunthercox** [comment]
@sbaity I believe @vkosuri's diagnosis is correct. I'm going to close this ticket off, feel free to reopen it if that didn't solve the issue.
