### ISSUE TITLE
sqlite3.InterfaceError

### ISSUE THREAD

**Issue by indiclinguist** [gunthercox/ChatterBot#1129]
I am trying to play with Odia. I get the following error. Can anyone help to get rid of this issue?
-------------------------------  
``` Bash
File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.InterfaceError: Error binding parameter 0 - probably unsupported type.
```
The above exception was the direct cause of the following exception:
``` Bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/site-packages/chatterbot/trainers.py", line 133, in train
    statement = self.get_or_create(text)
  File "/usr/lib/python3.4/site-packages/chatterbot/trainers.py", line 28, in get_or_create
    statement = self.storage.find(statement_text)
  File "/usr/lib/python3.4/site-packages/chatterbot/storage/sql_storage.py", line 141, in find
    record = query.first()
  File "/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2755, in first
    ret = list(self[0:1])
  File "/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2547, in __getitem__
    return list(res)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2855, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/orm/query.py", line 2878, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/sql/elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1189, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/util/compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/usr/lib/python3.4/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.InterfaceError>>> 
```

**Comment by vkosuri** [comment]
I think this might related to this https://github.com/gunthercox/ChatterBot/issues/1130?

**Comment by gunthercox** [comment]
@indiclinguist I'm going to close this ticket off. It appears that the code that was triggering this error has since been removed from the ChatterBot project. Feel free to open a new issue if difficulties persist.
