### ISSUE TITLE
I am facing No module name logic while working on chatter bot in my django app

### ISSUE THREAD

**Issue by Fazalcs13** [gunthercox/ChatterBot#1133]
Here is setting.py code

CHATTERBOT = {
    'name': 'Django ChatterBot Example',
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        #'chatterbot.corpus.english.greetings',
        #'chatterbot.corpus.english.conversations',
        'chatterbot.corpus.english.JohnPowers'
    ],
    'logic_adapters':[
        {
            'import_path': 'chatterbot.adapters.logic.ClosestMatchAdapter'
        },
        {
            'import_path': 'chatterbot.adapters.logic.LowConfidenceAdapter',
            'threshold': 0.65,
            'default_response': "I didn't understand that question; do you need help with Math, Excel, Music or Graphic?"
        }
    ],
    'django_app_name': 'django_chatterbot',
    'read_only': True
}

Traceback (most recent call last):
  File "C:\Python27\lib\wsgiref\handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "C:\Python27\lib\site-packages\django\contrib\staticfiles\handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "C:\Python27\lib\site-packages\django\core\handlers\wsgi.py", line 170, in __call__
    self.load_middleware()
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 52, in load_middleware
    mw_instance = mw_class()
  File "C:\Python27\lib\site-packages\django\middleware\locale.py", line 24, in __init__
    for url_pattern in get_resolver(None).url_patterns:
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 401, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\core\urlresolvers.py", line 395, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\tutorial_project_new\tutorial-project\tutorial-project\mysite\urls.py", line 15, in <module>
    from chatterbot.ext.django_chatterbot import urls as chatterbot_urls
  File "C:\Python27\lib\site-packages\chatterbot\ext\django_chatterbot\urls.py", line 2, in <module>
    from .views import ChatterBotView
  File "C:\Python27\lib\site-packages\chatterbot\ext\django_chatterbot\views.py", line 8, in <module>
    class ChatterBotViewMixin(object):
  File "C:\Python27\lib\site-packages\chatterbot\ext\django_chatterbot\views.py", line 13, in ChatterBotViewMixin
    chatterbot = ChatBot(**settings.CHATTERBOT)
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 54, in __init__
    self.logic.add_adapter(adapter, **kwargs)
  File "C:\Python27\lib\site-packages\chatterbot\logic\multi_adapter.py", line 123, in add_adapter
    utils.validate_adapter_class(adapter, LogicAdapter)
  File "C:\Python27\lib\site-packages\chatterbot\utils.py", line 63, in validate_adapter_class
    if not issubclass(import_module(validate_class), adapter_class):
  File "C:\Python27\lib\site-packages\chatterbot\utils.py", line 15, in import_module
    module = importlib.import_module(module_path)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named logic
[28/Dec/2017 13:41:21] "GET /en/ HTTP/1.1" 500 59

**Comment by vkosuri** [comment]
I think ``chatterbot.corpus.english.JohnPowers`` it didn't exists in chatterbot installed directory (C:\Python27\lib\site-packages\chatterbot)

**Comment by Fazalcs13** [comment]
No its not because of JohnPowers it is because of adapters when i remove adapters it is working as expected
