### ISSUE TITLE
Example code not running

### ISSUE THREAD

**Issue by kanishk-mehta** [gunthercox/ChatterBot#1159]
hi,

I can't get the example code to run. My python version is **3.6.0**

I'm getting the following error message: 

``` Bash
Unhandled exception in thread started by <function check_errors.<locals>.wrapper
 at 0x00000000040632F0>
Traceback (most recent call last):
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\core\management\__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\apps\registry.py", line 112, in populate
    app_config.import_models()
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\django\apps\config.py", line 198, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\import
lib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\chatterbot\ext\django_chatterbot\models.py", line 125, in <module>
    class Response(models.Model):
  File "C:\Users\kanishk.mehta\AppData\Local\Programs\Python\Python36\lib\site-p
ackages\chatterbot\ext\django_chatterbot\models.py", line 135, in Response
    related_name='in_response'
TypeError: __init__() missing 1 required positional argument: 'on_delete'

```
please let me know if i've missed out on providing some information, am new to python.

please help @gunthercox

**Comment by gunthercox** [comment]
What version of Django do you have installed?

**Comment by kanishk-mehta** [comment]
2.0.1

**Comment by kalentang** [comment]
please use django v1.11
