### ISSUE TITLE
KeyError: 'unary_operators'

### ISSUE THREAD

**Issue by konstantin42127** [gunthercox/ChatterBot#1235]
can not use chatterbot.logic.MathematicalEvaluation with non-English
how to solve?

**Comment by gunthercox** [comment]
Many non-english characters are currently supported.

Could you please provide instructions so that I can recreate this error?

**Comment by konstantin42127** [comment]
```
from chatterbot import ChatBot
import logging

logging.basicConfig(level=logging.INFO)

chatbot = ChatBot(
    'bot',
    database='./db.sqlite3',
    response_selection_method=get_random_response,
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.MathematicalEvaluation'
            'language': 'RUS'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.5,
            'default_response': ".."
        }
    ],
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)

response = chatbot.get_response('Сколько будет четыре плюс четыре?') #What is four plus four?
```

error:

```
response = chatbot.get_response('Сколько будет четыре плюс четыре?') #What is four plus four?
INFO:chatterbot.adapters:Received input statement: Сколько будет четыре плюс четыре?
INFO:chatterbot.adapters:"Сколько будет четыре плюс четыре?" is not a known statement
INFO:chatterbot.adapters:Not processing the statement using BestMatch
Traceback (most recent call last):
  File "<pyshell#3>", line 1, in <module>
    response = chatbot.get_response('Сколько будет четыре плюс четыре?') #What is four plus four?
  File "C:\Users\lik47\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chatterbot-0.8.4-py3.6.egg\chatterbot\chatterbot.py", line 113, in get_response
    statement, response = self.generate_response(input_statement, conversation_id)
  File "C:\Users\lik47\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chatterbot-0.8.4-py3.6.egg\chatterbot\chatterbot.py", line 132, in generate_response
    response = self.logic.process(input_statement)
  File "C:\Users\lik47\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chatterbot-0.8.4-py3.6.egg\chatterbot\logic\multi_adapter.py", line 49, in process
    if adapter.can_process(statement):
  File "C:\Users\lik47\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chatterbot-0.8.4-py3.6.egg\chatterbot\logic\mathematical_evaluation.py", line 33, in can_process
    response = self.process(statement)
  File "C:\Users\lik47\AppData\Local\Programs\Python\Python36-32\lib\site-packages\chatterbot-0.8.4-py3.6.egg\chatterbot\logic\mathematical_evaluation.py", line 59, in process
    mathparse.parse(expression, language=self.language)
  File "C:\Users\lik47\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mathparse\mathparse.py", line 266, in parse
    string = replace_word_tokens(string, language)
  File "C:\Users\lik47\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mathparse\mathparse.py", line 99, in replace_word_tokens
    operators.update(words['unary_operators'])
KeyError: 'unary_operators'
```

**Comment by manoelrui** [comment]
@gunthercox, @vkosuri and @konstantin42127 I am sure that the main problem is inside **mathparse** lib, I send a [pull request ](https://github.com/gunthercox/mathparse/pull/23) to mathparse repository to try fix this [bug](https://github.com/gunthercox/mathparse/issues/13). In my environment, It worked as expected after this fix. When a new version of mathparse was released fixing this bug I can add unit tests to cover this scenarios. The follow application show the final result:
**CODE**:
```
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
import logging

logging.basicConfig(level=logging.INFO)

chatbot = ChatBot(
        'bot',
        database='./db.sqlite3',
        logic_adapters=[
            {
                'import_path': 'chatterbot.logic.BestMatch'
                },
            {
                'import_path': 'chatterbot.logic.MathematicalEvaluation',
                'language': 'RUS'
                },
            {
                'import_path': 'chatterbot.logic.LowConfidenceAdapter',
                'threshold': 0.5,
                'default_response': ".."
                }
            ],
        trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
        )

# What is four plus four?
response = chatbot.get_response('Сколько будет четыре плюс четыре?')
print(response.text)
```
**OUTPUT**:
```
INFO:chatterbot.adapters:Received input statement: Сколько будет четыре плюс четыре?
INFO:chatterbot.adapters:"Сколько будет четыре плюс четыре?" is a known statement
INFO:chatterbot.adapters:No statements have known responses. Choosing a random response to return.
INFO:chatterbot.adapters:Using "Сколько будет четыре плюс четыре?" as a close match to "Сколько будет четыре плюс четыре?"
INFO:chatterbot.adapters:No response to "Сколько будет четыре плюс четыре?" found. Selecting a random response.
INFO:chatterbot.adapters:BestMatch selected "четыре плюс четыре = 8" as a response with a confidence of 0
INFO:chatterbot.adapters:MathematicalEvaluation selected "четыре плюс четыре = 8" as a response with a confidence of 1
INFO:chatterbot.adapters:No statements have known responses. Choosing a random response to return.
INFO:chatterbot.response_selection:Selecting first response from list of 1 options.
INFO:chatterbot.adapters:LowConfidenceAdapter selected ".." as a response with a confidence of 1
INFO:chatterbot.adapters:NoKnowledgeAdapter selected "Сколько будет четыре плюс четыре?" as a response with a confidence of 0
четыре плюс четыре = 8

```
