### ISSUE TITLE
sqlite3 Operational Error in Flask

### ISSUE THREAD

**Issue by adamjameshuston** [gunthercox/ChatterBot#1260]
I have this build working on my own machine locally [chamkank's flask-chatterbot](https://github.com/chamkank/flask-chatterbot/blob/master/app.py)

And I have wsgi and portforwarding working on my apache server

But when it launches my app I get an error

)
```
 File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
  return self.dbapi.connect(*cargs, **cparams)
 OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
```

seems to be happening during database creation?

I've used chmod and 000-default.conf to pry the permissions as wide open as I can get them...

**Comment by adamjameshuston** [comment]
More stuff:

Chatterbot version: 0.8.4
Operating system: Apache/2.4.10 on Raspbian - it's Debian for Raspberry Pi
Python

Permissions might not be as wide as I think? I'm really not sure

```
ahuston@webserver01:~$ ls -l public_html
total 20
drwxr-xr-x 3 ahuston www-data 4096 Mar 23 12:30 apps
drwxr-xr-x 2 ahuston www-data 4096 Mar 25 00:38 http
drwxr-xr-x 2 ahuston www-data 4096 Mar 17 00:22 https
drwxr-xr-x 2 ahuston www-data 4096 Mar 17 01:14 logs
drwxr-xr-x 2 ahuston www-data 4096 Mar 23 12:01 wsgi
ahuston@webserver01:~$

```

Full trace

```
mod_wsgi (pid=21196): Target WSGI script '/home/ahuston/public_html/wsgi/helloworld.wsgi' cannot be loaded as Python module.
mod_wsgi (pid=21196): Exception occurred processing WSGI script '/home/ahuston/public_html/wsgi/helloworld.wsgi'.
Traceback (most recent call last):
  File "/home/ahuston/public_html/wsgi/helloworld.wsgi", line 3, in <module>
     from helloworld import app as application
  File "/home/ahuston/public_html/apps/flasktest/helloworld.py", line 9, in <module>
     english_bot = ChatBot("d3")
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 39, in __init__
     self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/utils.py", line 33, in initialize_class
     return Class(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/sql_storage.py", line 77, in __init__
     if not self.engine.dialect.has_table(self.engine, 'Statement'):
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 1181, in has_table
     connection, "table_info", table_name, schema=schema)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 1572, in _get_table_pragma
     cursor = connection.execute(statement)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2074, in execute
     connection = self.contextual_connect(close_with_result=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
     self._wrap_pool_connect(self.pool.connect, None),
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
    e, dialect, self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
     exc_info
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
     reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
     return fn()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 403, in connect
     return _ConnectionFairy._checkout(self)
   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 784, in _checkout
     fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 532, in checkout
     rec = pool._do_get()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 1280, in _do_get
     return self._create_connection()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
     return _ConnectionRecord(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 477, in __init__
     self.__connect(first_connect_check=True)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/pool.py", line 667, in __connect
     connection = pool._invoke_creator(self)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
     return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/engine/default.py", line 410, in connect
     return self.dbapi.connect(*cargs, **cparams)
OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
```

Any help would be much appreciated! Thanks, all!

**Comment by adamjameshuston** [comment]
When I figure out what exactly I did to fix this, I'll post ;)
