### ISSUE TITLE
Can't get ChatterBot to work

### ISSUE THREAD

**Issue by dylanail** [gunthercox/ChatterBot#1297]
Hi, I installed version 0.8.6 on Ubuntu 16.04 and am using Python 3.x, and the first thing that I tried to do is get some examples up and running. The first time I installed chatterbot, it somehow worked but would only reiterate the words which I entered. I then tried the quick start guide code, but that one would only reply with the time for some reason. I uninstalled and reinstalled chatterbot, and now when I try to run any of the code, it comes up with this error:

``` Bash
List Trainer: [#######             ] 33%Traceback (most recent call last):
  File "chatbot.py", line 13, in <module>
    "Your flight has been booked."
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/trainers.py", line 110, in train
    statement = self.get_or_create(text)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/sql_storage.py", line 132, in find
    record = query.first()
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2825, in first
    ret = list(self[0:1])
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/query.py", line 2617, in __getitem__
    return list(res)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 98, in instances
    util.raise_from_cause(err)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 79, in instances
    rows = [proc(row) for row in fetch]
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 508, in _instance
    loaded_instance, populate_existing, populators)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/loading.py", line 608, in _populate_full
    dict_[key] = getter(row)
  File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/sql/sqltypes.py", line 1588, in process
    return loads(value)
ValueError: unsupported pickle protocol: 4
```

and when I try running it with python3, it does this:

``` Bash
List Trainer: [#######             ] 33%Traceback (most recent call last):
  File "chatbot.py", line 13, in <module>
    "Your flight has been booked."
  File "/home/dylan/.local/lib/python3.5/site-packages/chatterbot/trainers.py", line 110, in train
    statement = self.get_or_create(text)
  File "/home/dylan/.local/lib/python3.5/site-packages/chatterbot/trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
  File "/home/dylan/.local/lib/python3.5/site-packages/chatterbot/storage/sql_storage.py", line 128, in find
    Statement = self.get_model('statement')
  File "/home/dylan/.local/lib/python3.5/site-packages/chatterbot/storage/storage_adapter.py", line 34, in get_model
    return get_model_method()
  File "/home/dylan/.local/lib/python3.5/site-packages/chatterbot/storage/sql_storage.py", line 89, in get_statement_model
    from chatterbot.ext.sqlalchemy_app.models import Statement
  File "/home/dylan/.local/lib/python3.5/site-packages/chatterbot/ext/sqlalchemy_app/models.py", line 8, in <module>
    from chatterbot.conversation import StatementMixin
ImportError: cannot import name 'StatementMixin'
```
I have no idea what's going on at this point, and I am in dire need of some help, which would be greatly appreciated. Thanks so much.

PS I tried running everything with sudo.

**Comment by dylanail** [comment]
One more thing is that I ~just got it to do something else with the "basic example", and all it does is consistently reply "I am sorry, but I do not understand". Still no luck with any other example.

**Comment by vkosuri** [comment]
It seems to me you are using old version of chatterbot, could you try to upgrade to latest version ``pip install --upgrade chatterbot`` still you are getting errors please post stack trace.

**Comment by gunthercox** [comment]
@dylanail The upgrade command will also make sure that you have the latest supported dependencies installed for ChatterBot, such as sqlalchemy.
***
I'm uncertain about the cause of the import error. What does the structure of your working directory look like?
