### ISSUE TITLE
Error in training chatbot

### ISSUE THREAD

**Issue by ChristinaLai2019** [gunthercox/ChatterBot#1337]
Hi When I am trying to train my chatbot using corpuses I found a list of errors reporting and the chatbot is not trained. The error message is shown below: 

```
Traceback (most recent call last):
  File "/Users/christinalai/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1182, in _execute_context
    context)
  File "/Users/christinalai/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/christinalai/PycharmProjects/chatterbot/chatbot.py", line 17, in <module>
    bot.train(new)
  File "/Users/christinalai/anaconda/lib/python3.6/site-packages/chatterbot/trainers.py", line 91, in train
    self.storage.update(statement)
  File "/Users/christinalai/anaconda/lib/python3.6/site-packages/chatterbot/storage/sql_storage.py", line 277, in update
  File "/Users/christinalai/anaconda/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) database is locked [SQL: 'INSERT INTO "StatementTable" (text, extra_data) VALUES (?, ?)'] [parameters: ...]
```
My program is as below:

```
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import os

bot = ChatBot('ChatBot')
bot.set_trainer(ListTrainer)
new = []

for files in os.listdir('/Users/christinalai/Desktop/corpus'):
    print(files)
    data = open('/Users/christinalai/Desktop/corpus/' + files, mode='r', errors="ignore").readlines()
    for line in data:
        new.append(line)

bot.train(new)

while True:
    message = input("You: ")
    if message.strip() not in message_list:
        reply = bot.get_response(message).decode("utf-8")
        print("ChatBot: ", reply)
```

**Comment by Kaporos** [comment]
The program does not have the necessary access rights to access the db, try to run it as an administrator

**Comment by ChristinaLai2019** [comment]
Thanks I solved it now. And can I ask one more questions? How can we retrain the chatterbot when we get a new corpus, without having to train the entire corpus we had all over again? I just want to train the new corpus on my chatterbot that is already trained with my old corpuses.

**Comment by vkosuri** [comment]
See this issue https://github.com/gunthercox/ChatterBot/issues/1364#issuecomment-410578498
