### ISSUE TITLE
Getting unicode error while running test_chatbot.py

### ISSUE THREAD

**Issue by getnsv** [gunthercox/ChatterBot#1367]
Hi there,

Am getting the following error when I run the test_chatbot.py. Please cna you help. And also while testing with the emoji icon etc.
```
======================================================================
ERROR: Test the case that a unicode string is passed in.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\workspace\ChatterBot-master\ChatterBot-master\tests\test_chatbot.py", line 90, in test_get_response_unicode
    response = self.chatbot.get_response(u'Mirabilis')
  File "D:\workspace\ChatterBot-master\ChatterBot-master\chatterbot\chatterbot.py", line 111, in get_response
    input_statement = self.input.process_input_statement(input_item)
  File "D:\workspace\ChatterBot-master\ChatterBot-master\chatterbot\input\input_adapter.py", line 20, in process_input_statement
    input_statement = self.process_input(*args, **kwargs)
  File "D:\workspace\ChatterBot-master\ChatterBot-master\chatterbot\input\variable_input_type_adapter.py", line 29, in process_input
    input_type = self.detect_type(statement)
  File "D:\workspace\ChatterBot-master\ChatterBot-master\chatterbot\input\variable_input_type_adapter.py", line 24, in detect_type
    input_type
UnrecognizedInputFormatException: "The type <type 'unicode'> is not recognized as a valid input type."

----------------------------------------------------------------------
```

**Comment by vkosuri** [comment]
@getnsv did you tried these methods https://chatterbot.readthedocs.io/en/stable/encoding.html#how-do-i-fix-python-encoding-errors
