### ISSUE TITLE
MySQL storage adapter error

### ISSUE THREAD

**Issue by r4nx** [gunthercox/ChatterBot#1379]
I am using pymysql, my database_uri looks like this: `mysql+pymysql://root@localhost:3306/eternityapi`
Tables create successfully, but when I learning the bot I am getting an error: `sqlalchemy.orm.exc.FlushError: Can't flush None value found in collection Conversation.statements` (full traceback below). The interesting thing: when I learn bot the same statement again - there is no error.

    Traceback (most recent call last):
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 2309, in __call__
        return self.wsgi_app(environ, start_response)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 2295, in wsgi_app
        response = self.handle_exception(e)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
        return original_handler(e)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 1741, in handle_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\_compat.py", line 34, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 2292, in wsgi_app
        response = self.full_dispatch_request()
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
        rv = self.handle_user_exception(e)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask_restful\__init__.py", line 273, in error_router
        return original_handler(e)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
        reraise(exc_type, exc_value, tb)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\_compat.py", line 34, in reraise
        raise value.with_traceback(tb)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
        rv = self.dispatch_request()
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\app.py", line 1799, in dispatch_request
        return self.view_functions[rule.endpoint](**req.view_args)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask_restful\__init__.py", line 480, in wrapper
        resp = resource(*args, **kwargs)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask\views.py", line 88, in view
        return self.dispatch_request(*args, **kwargs)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\flask_restful\__init__.py", line 595, in dispatch_request
        resp = meth(*args, **kwargs)
      File "C:\Users\Admin\Desktop\eternityapi\eternityapi\botapi.py", line 30, in post
        chatbot.learn(args['question'], args['response'])
      File "d:\projects\python\eternitychatbot-core\eternitychatbot_core\core.py", line 114, in learn
        self.__chatbot.storage.add_to_conversation(self.__conversation_id, question, response)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\chatterbot\storage\sql_storage.py", line 330, in add_to_conversation
        self._session_finish(session)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\chatterbot\storage\sql_storage.py", line 396, in _session_finish
        session.commit()
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\session.py", line 943, in commit
        self.transaction.commit()
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\session.py", line 467, in commit
        self._prepare_impl()
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\session.py", line 447, in _prepare_impl
        self.session.flush()
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\session.py", line 2254, in flush
        self._flush(objects)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\session.py", line 2380, in _flush
        transaction.rollback(_capture_exception=True)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
        compat.reraise(exc_type, exc_value, exc_tb)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
        raise value
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\session.py", line 2344, in _flush
        flush_context.execute()
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 391, in execute
        rec.execute(self)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 507, in execute
        self.dependency_processor.process_saves(uow, states)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\dependency.py", line 1043, in process_saves
        False, uowcommit, "add"):
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\dependency.py", line 1132, in _synchronize
        self._verify_canload(child)
      File "C:\Users\Admin\Envs\eternityapi\lib\site-packages\sqlalchemy\orm\dependency.py", line 246, in _verify_canload
        "collection %s" % (self.prop, ))
    sqlalchemy.orm.exc.FlushError: Can't flush None value found in collection Conversation.statements

**Comment by gunthercox** [comment]
@r4nx Thank you for reporting this issue. I've decided to remove the Conversation model from ChatterBot to simplify the data representations that it uses (#1391). This bug should be resolved as of the next version that gets released. Please let me know if you have any questions.
