### ISSUE TITLE
ImportError: cannot import name 'ChatBot'

### ISSUE THREAD

**Issue by jayeshsk** [gunthercox/ChatterBot#1380]
@gunthercox
Everytime I'm running this code it is showing me this error..
ImportError: cannot import name 'ChatBot'

here's the code..

> from chatterbot import ChatBot
> from chatterbot.trainers import ListTrainers
> import os
> 
> bot= ChatBot('Bot')
> bot.set_trainers(ListTrainers)
> 
> for files in os.listdir('F:\Project Data\chatterbot-corpus-master\chatterbot_corpus\data\english'):
>     data=open('F:\Project Data\chatterbot-corpus-master\chatterbot_corpus\data\english'+files,'r').readlines()
>     bot.train(data)
> 
> while True:
>     message=input("USER:")
>     if(message.strip() != 'bye'):
>         reply=bot.get_response(message)
>         print("BOT:" + reply)
>     if(message.strip() == 'bye'):
>         print("BOT:BYE :-), hope to see you again")
>         break

**Comment by jayeshsk** [comment]
I have tried the above program both in VS code and pycharm.
for pycharm the error is:
`**ImportError: cannot import name 'ChatBot'**`

for VS code the error is:

> Traceback (most recent call last):
>   File "chat.py", line 2, in <module>
>     from chatterbot.trainer import ListTrainers
> ModuleNotFoundError: No module named 'chatterbot.trainer'

please help me with this....
`

**Comment by gunthercox** [comment]
@jayeshsk is it possible that you created a file named `chatterbot.py`? If this is the case, imports `from chatterbot` will fail.

**Comment by gunthercox** [comment]
Change `ListTrainers` to `ListTrainer`.

**Comment by jayeshsk** [comment]
@gunthercox 
now it is again showing the same error

![pycharm64_2018-08-27_22-01-10](https://user-images.githubusercontent.com/35068681/44672109-0ea59c80-aa45-11e8-808b-a9b5a2c32c2c.png)

**Comment by gunthercox** [comment]
In that screenshot, you have a `chatterbot.py` file. That is the cause of the import error you are seeing.

**Comment by jayeshsk** [comment]
@gunthercox 
the errors now say they can't access the file...
and sometimes it say can't import listtrainer...
there is lot of confusion.
can we have a teamviewer session,please?

**Comment by jayeshsk** [comment]
@gunthercox 

![pycharm64_2018-08-28_18-12-02](https://user-images.githubusercontent.com/35068681/44723598-140af180-aaee-11e8-9408-6e3f2a6e7e6f.png)
![explorer_2018-08-28_18-12-28](https://user-images.githubusercontent.com/35068681/44723596-13725b00-aaee-11e8-8a06-44e0d1a1957e.png)

now it is saying files don't exist....

**Comment by gunthercox** [comment]
Based on the error message, it looks like the path you've build isn't a valid file path to those yaml files. I think you are missing a trailing slash `/` in the initial string.

**Comment by MITeoRIte** [comment]
@jayeshsk 
Realise that the file its trying to find is "englishai.yml" from \data instead of "ai.yml" from \data\english\

So what you need to do is add a `\` on the line (which I have already done so for you) : `data=open('F:\Project Data\chatterbot-corpus-master\chatterbot_corpus\data\english\'+files,'r').readlines()`

**Comment by neelabhsriv** [comment]
Are you able to run the above code? I am also trying, however, I am getting an error. Kindly help
![image](https://user-images.githubusercontent.com/46059269/54000344-4bb2c000-4147-11e9-9d3e-045a9ba50aff.png)

**Comment by shivam2200** [comment]
![Screenshot (3)](https://user-images.githubusercontent.com/49568109/56230537-1f6d5600-609a-11e9-8700-173cb20576bc.png)
getting import error

**Comment by shivam2200** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/49568109/56230747-8c80eb80-609a-11e9-911c-b63e850cd96c.png)
this is code

**Comment by shivam2200** [comment]
this is the error
![Screenshot (5)](https://user-images.githubusercontent.com/49568109/56230834-bb975d00-609a-11e9-90cf-c0df7c4872c8.png)

**Comment by KarthiJi** [comment]
yea me too can anybody help wit this?

**Comment by gunthercox** [comment]
Hi @KarthiJi, the error `ImportError: cannot import name 'ChatBot'` can happen for a number of reasons. The most likely reason is that ChatterBot has not been installed on your system.

The easiest way to do this is by running the command `pip install chatterbot`.
In some cases Python 3 gets installed under the command entrypoint of `python3`, if this is the case you can install ChatterBot by running `python3 -m pip install chatterbot`

**Comment by shivam2200** [comment]
Thank you for the support 😄😄

**Comment by DRON1997** [comment]
What is the problem here , I can't even import chatbot.
![Screenshot (88)](https://user-images.githubusercontent.com/31847882/57902572-82affb00-7887-11e9-9bb7-3abf88c7880c.png)
![Screenshot (89)](https://user-images.githubusercontent.com/31847882/57902574-82affb00-7887-11e9-9c98-0241ea334547.png)

**Comment by onurgoker** [comment]
> @jayeshsk is it possible that you created a file named `chatterbot.py`? If this is the case, imports `from chatterbot` will fail.

Definitely my main problem was this one :)

**Comment by codePerfectPlus** [comment]
This Error Maybe due to Some reason.
- chatter is not installed try  ```pip install chatterbot```
- You are using a different environment. try to change the environment
- chatterbot is not in the path

**Comment by SuperSanglap** [comment]
H:\Python Projects> cmd /C "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\python.exe c:\Users\Sanglap\.vscode\extensions\ms-python.python-2020.7.96456\pythonFiles\lib\python\debugpy\launcher 61072 -- "h:\Python Projects\Test.py" "
Traceback (most recent call last):
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 434, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 831, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 563, in checkout
    rec = pool._do_get()
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 1355, in _do_get
    return self._create_connection()
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 379, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 508, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 722, in __connect
    pool.dispatch.connect(self.connection, self)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\event\attr.py", line 259, in __call__
    fn(*args, **kw)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 43, in set_sqlite_pragma
    dbapi_connection.execute('PRAGMA journal_mode=WAL')
sqlite3.OperationalError: cannot change into wal mode from within a transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "h:\Python Projects\Test.py", line 4, in <module>
    bot = ChatBot('Test')
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\chatterbot.py", line 41, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 46, in __init__
    if not self.engine.dialect.has_table(self.engine, 'Statement'):
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1357, in has_table
    connection, "table_info", table_name, schema=schema
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1799, in _get_table_pragma
    cursor = connection.execute(statement)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2143, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2192, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2232, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1528, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 434, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 831, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 563, in checkout
    rec = pool._do_get()
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 1355, in _do_get
    return self._create_connection()
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 379, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 508, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool.py", line 722, in __connect
    pool.dispatch.connect(self.connection, self)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\event\attr.py", line 259, in __call__
    fn(*args, **kw)
  File "C:\Users\Sanglap\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 43, in set_sqlite_pragma
    dbapi_connection.execute('PRAGMA journal_mode=WAL')
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) cannot change into wal mode from within a transaction (Background on this error at: http://sqlalche.me/e/e3q8)



Any Suggestion ?

**Comment by aaroha33** [comment]
![image](https://user-images.githubusercontent.com/35847769/95730002-4f031b80-0c9b-11eb-91b1-1215079c125b.png)
![image](https://user-images.githubusercontent.com/35847769/95730056-5de9ce00-0c9b-11eb-8cbd-7d39d1375551.png)
![image](https://user-images.githubusercontent.com/35847769/95730092-6510dc00-0c9b-11eb-8460-bc3d75e62330.png)
![image](https://user-images.githubusercontent.com/35847769/95730176-8376d780-0c9b-11eb-9464-d13f2defb541.png)
I have tried, different method, different environment, failed to import.
It's a problem about version of **PyYAML** , What I think. Any Suggestion ?

**Comment by laxmisundar** [comment]
I had the same issue.. it got solved when i followed 3 steps,

1. From command line i executed this code...
_python -m pip install chatterbot_

2. I installed spacy from command line
_pip install spacy_

3. I changed myfile name from chatterbot.py to talks.py

yay...!! Error gone.... :)

**Comment by wyneg** [comment]
> @jayeshsk is it possible that you created a file named `chatterbot.py`? If this is the case, imports `from chatterbot` will fail.

Hahaha, you made my day, thanks!

**Comment by erdebankadas** [comment]
ImportError: cannot import name 'chatBot' from partially initialized module 'chatterbot' (most likely due to a circular import) (c:\Users\Debanka\Desktop\chat\chatterbot.py) .

same also me.please help
