### ISSUE TITLE
List Trainer: [                    ] 0%Traceback (most recent call last):

### ISSUE THREAD

**Issue by lohitk27** [gunthercox/ChatterBot#1381]
whiel I'm running python chatbot_train.py  getting error 

List Trainer: [                    ] 0%Traceback (most recent call last):
  File "chatbot_train.py", line 18, in <module>
    setup()
  File "chatbot_train.py", line 14, in setup
    chatbot.train(convData)
  File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 110, in trai
n
    statement = self.get_or_create(text)
  File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 48, in get_o
r_create
    statement = self.storage.find(temp_statement.text)
  File "C:\Python27\lib\site-packages\chatterbot\storage\sql_storage.py", line 1
32, in find
    record = query.first()
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2888, in fi
rst
    ret = list(self[0:1])
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2680, in __
getitem__
    return list(res)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 98, in in
stances
    util.raise_from_cause(err)
  File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 265, in r
aise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 79, in in
stances
    rows = [proc(row) for row in fetch]
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 511, in _
instance
    loaded_instance, populate_existing, populators)
  File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 611, in _
populate_full
    dict_[key] = getter(row)
  File "C:\Python27\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1588, in
 process
    return loads(value)
ValueError: unsupported pickle protocol: 4

**Comment by lohitk27** [comment]
@gunthercox  kindly help me out with above error

**Comment by lohitk27** [comment]
@tentamen @gunthercox @dineshjoshy

while I'm running python chatbot_train.py getting error

List Trainer: [ ] 0%Traceback (most recent call last):
File "chatbot_train.py", line 18, in 
setup()
File "chatbot_train.py", line 14, in setup
chatbot.train(convData)
File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 110, in trai
n
statement = self.get_or_create(text)
File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 48, in get_o
r_create
statement = self.storage.find(temp_statement.text)
File "C:\Python27\lib\site-packages\chatterbot\storage\sql_storage.py", line 1
32, in find
record = query.first()
File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2888, in fi
rst
ret = list(self[0:1])
File "C:\Python27\lib\site-packages\sqlalchemy\orm\query.py", line 2680, in __
getitem__
return list(res)
File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 98, in in
stances
util.raise_from_cause(err)
File "C:\Python27\lib\site-packages\sqlalchemy\util\compat.py", line 265, in r
aise_from_cause
reraise(type(exception), exception, tb=exc_tb, cause=cause)
File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 79, in in
stances
rows = [proc(row) for row in fetch]
File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 511, in _
instance
loaded_instance, populate_existing, populators)
File "C:\Python27\lib\site-packages\sqlalchemy\orm\loading.py", line 611, in _
populate_full
dict_[key] = getter(row)
File "C:\Python27\lib\site-packages\sqlalchemy\sql\sqltypes.py", line 1588, in
process
return loads(value)
ValueError: unsupported pickle protocol: 4

**Comment by gunthercox** [comment]
The error you are encountering is because ChatterBot no longer supports Python 2.7. Upgrading to Python 3 is required.
