### ISSUE TITLE
LookupError: App 'tbots' doesn't have a 'Conversation' model.

### ISSUE THREAD

**Issue by elcolie** [gunthercox/ChatterBot#1386]
This error happens in `master` and `0.8.7`
django==2.1.1

```bash
django_1        | Traceback (most recent call last):
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/handlers.py", line 65, in __call__
django_1        |     return self.application(environ, start_response)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 142, in __call__
django_1        |     response = self.get_response(request)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 78, in get_response
django_1        |     response = self._middleware_chain(request)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 36, in inner
django_1        |     response = response_for_exception(request, exc)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 90, in response_for_exception
django_1        |     response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 125, in handle_uncaught_exception
django_1        |     return debug.technical_500_response(request, *exc_info)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django_extensions/management/technical_response.py", line 34, in null_technical_500_response
django_1        |     six.reraise(exc_type, exc_value, tb)
django_1        |   File "/usr/local/lib/python3.6/site-packages/six.py", line 692, in reraise
django_1        |     raise value.with_traceback(tb)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
django_1        |     response = get_response(request)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 126, in _get_response
django_1        |     response = self.process_exception_by_middleware(e, request)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 124, in _get_response
django_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
django_1        |   File "/usr/local/lib/python3.6/contextlib.py", line 52, in inner
django_1        |     return func(*args, **kwds)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
django_1        |     return self.dispatch(request, *args, **kwargs)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
django_1        |     return handler(request, *args, **kwargs)
django_1        |   File "/app/try_chatterbot/tbots/views.py", line 82, in get
django_1        |     conversation = self.get_conversation(request)
django_1        |   File "/app/try_chatterbot/tbots/views.py", line 41, in get_conversation
django_1        |     conversation_id = self.chatterbot.storage.create_conversation()
django_1        |   File "/usr/local/lib/python3.6/site-packages/chatterbot/storage/django_storage.py", line 173, in create_conversation
django_1        |     Conversation = self.get_model('conversation')
django_1        |   File "/usr/local/lib/python3.6/site-packages/chatterbot/storage/storage_adapter.py", line 34, in get_model
django_1        |     return get_model_method()
django_1        |   File "/usr/local/lib/python3.6/site-packages/chatterbot/storage/django_storage.py", line 30, in get_conversation_model
django_1        |     return apps.get_model(self.django_app_name, 'Conversation')
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 207, in get_model
django_1        |     return app_config.get_model(model_name, require_ready=require_ready)
django_1        |   File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 168, in get_model
django_1        |     "App '%s' doesn't have a '%s' model." % (self.label, model_name))
django_1        | LookupError: App 'tbots' doesn't have a 'Conversation' model.
```

I have no idea why `Django` couldn't figure out where the model is.

As a proof this is the in side the container. The table has been created.
```python
In [1]: Conversation.objects.all()
Out[1]: <QuerySet []>
```

However, when check with `showmigrations` it does not!
```bash
/app # python manage.py showmigrations
account
 [X] 0001_initial
 [X] 0002_email_max_length
admin
 [X] 0001_initial
 [X] 0002_logentry_remove_auto_add
 [X] 0003_logentry_add_action_flag_choices
auth
 [X] 0001_initial
 [X] 0002_alter_permission_name_max_length
 [X] 0003_alter_user_email_max_length
 [X] 0004_alter_user_username_opts
 [X] 0005_alter_user_last_login_null
 [X] 0006_require_contenttypes_0002
 [X] 0007_alter_validators_add_error_messages
 [X] 0008_alter_user_username_max_length
 [X] 0009_alter_user_last_name_max_length
contenttypes
 [X] 0001_initial
 [X] 0002_remove_content_type_name
django_chatterbot
 [X] 0001_initial
 [X] 0002_statement_extra_data
 [X] 0003_change_occurrence_default
 [X] 0004_rename_in_response_to
 [X] 0005_statement_created_at
 [X] 0006_create_conversation
 [X] 0007_response_created_at
 [X] 0008_update_conversations
 [X] 0009_tags
 [X] 0010_statement_text
 [X] 0011_blank_extra_data
sessions
 [X] 0001_initial
sites
 [X] 0001_initial
 [X] 0002_alter_domain_unique
 [X] 0003_set_site_domain_and_name
socialaccount
 [X] 0001_initial
 [X] 0002_token_max_lengths
 [X] 0003_extra_data_default_dict
tbots
 (no migrations)
users
 [X] 0001_initial
```

How to fix this?

**Comment by jackxie1011** [comment]
> Fount the solution.
> I have to move
> `from chatterbot.ext.django_chatterbot.models import Conversation, Response` to the top of the file. Do not import locally

Would you mind to tell me which file for "moving `from chatterbot.ext.django_chatterbot.models import Conversation, Response` to the top of the file"? Thanks!
