### ISSUE TITLE
LookupError: App 'tbots' doesn't have a 'Statement' model.

### ISSUE THREAD

**Issue by elcolie** [gunthercox/ChatterBot#1387]
I am trying to run `python manage.py train`

```bash
/app # python manage.py train
greetings.yml Training: [#                   ] 4%Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 165, in get_model
    return self.models[model_name.lower()]
KeyError: 'statement'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/src/chatterbot/chatterbot/ext/django_chatterbot/management/commands/train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
  File "/src/chatterbot/chatterbot/trainers.py", line 153, in train
    statement = self.get_or_create(text)
  File "/src/chatterbot/chatterbot/trainers.py", line 42, in get_or_create
    statement = self.chatbot.storage.find(temp_statement.text)
  File "/src/chatterbot/chatterbot/storage/django_storage.py", line 41, in find
    Statement = self.get_model('statement')
  File "/src/chatterbot/chatterbot/storage/storage_adapter.py", line 34, in get_model
    return get_model_method()
  File "/src/chatterbot/chatterbot/storage/django_storage.py", line 22, in get_statement_model
    return apps.get_model(self.django_app_name, 'Statement')
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 207, in get_model
    return app_config.get_model(model_name, require_ready=require_ready)
  File "/usr/local/lib/python3.6/site-packages/django/apps/config.py", line 168, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'tbots' doesn't have a 'Statement' model.
```

Any help would be appreciated

**Comment by elcolie** [comment]
@pylobot It is equivalent to `example_app` from [this](https://github.com/gunthercox/ChatterBot/blob/master/examples/django_app/example_app/settings.py)

**Comment by gunthercox** [comment]
@elcolie I can't recreate the issue you encountered. Are you sure you included `chatterbot.ext.django_chatterbot` in your `INSTALLED_APPS` setting?

Are you using your own models with ChatterBot or the ones that come built-in?

**Comment by elcolie** [comment]
Thank you very much for your attention.

**Comment by elcolie** [comment]
Project was  gone already.  Then I can not reproduce the error.
