### ISSUE TITLE
AttributeError: module 'chatterbot.storage' has no attribute 'JsonFileStorageAdapter'

### ISSUE THREAD

**Issue by ithjz** [gunthercox/ChatterBot#1417]
Traceback (most recent call last):
  File "E:\users\administrator\eclipse-workspace2\chatbot-deeplearning\2.py", line 20, in <module>
    output_adapter='chatterbot.output.TerminalAdapter'
  File "E:\ProgramData\Anaconda3\lib\site-packages\chatterbot\chatterbot.py", line 39, in __init__
    utils.validate_adapter_class(storage_adapter, StorageAdapter)
  File "E:\ProgramData\Anaconda3\lib\site-packages\chatterbot\utils.py", line 64, in validate_adapter_class
    if not issubclass(import_module(validate_class), adapter_class):
  File "E:\ProgramData\Anaconda3\lib\site-packages\chatterbot\utils.py", line 17, in import_module
    return getattr(module, module_parts[-1])
AttributeError: module 'chatterbot.storage' has no attribute 'JsonFileStorageAdapter'

**Comment by gunthercox** [comment]
Hi @ithjz, the `JsonFileStorageAdapter` class was removed from ChatterBot several versions ago.
I would suggest using the `SQLStorageAdapter` instead.
