### ISSUE TITLE
ImportError: No module named storage

### ISSUE THREAD

**Issue by dilip90** [gunthercox/ChatterBot#1458]
Hello Team,
I am getting below issue.
**Traceback (most recent call last):
  File "test1.py", line 1, in <module>
    from chatterbot import ChatBot
  File "/opt/PythonLibs/ChatterBot/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/opt/PythonLibs/ChatterBot/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ImportError: No module named storage**

**Comment by Jereemi** [comment]
> Hello Team,
> I am getting below issue.
> **Traceback (most recent call last): File "test1.py", line 1, in from chatterbot import ChatBot File "/opt/PythonLibs/ChatterBot/chatterbot/**init**.py", line 4, in from .chatterbot import ChatBot File "/opt/PythonLibs/ChatterBot/chatterbot/chatterbot.py", line 2, in from chatterbot.storage import StorageAdapter ImportError: No module named storage**

@dilip90 I guess you have written the name of the Storage Adapter wrong. It should be either **chatterbot.storage.SQLStorageAdapter**( for databases such as SQLite, MySQL or PostgreSQL ) or **chatterbot.storage.MongoDatabaseAdapter** for mongodb.

So you can change your line into: **from chatterbot.storage import SQLStorageAdapter**

**Comment by dilip90** [comment]
Let me check guys, then only can I update thanks for reply.

**Comment by rjunior8** [comment]
In python 3.7:

AttributeError: 'ChatBot' object has no attribute 'train'

**Comment by gunthercox** [comment]
Hi @rjunior8, if you are seeing that error you will need to modify your code slightly. Here is an example:

```python
from chatterbot.trainers import ListTrainer

conversation = [
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
]

trainer = ListTrainer(chatbot)

trainer.train(conversation)
```

**Comment by productOfInternet** [comment]
Traceback (most recent call last):
  File "example.py", line 1, in <module>
    from chatterbot import ChatBot
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ImportError: No module named storage

 
im having this error. 
can you help me with that.

**Comment by gunthercox** [comment]
@productOfInternet I can see in the error message that you posted that you are using Python 2.7. ChatterBot only works on Python 3. I recommend using Python 3.6 to avoid this error.

**Comment by YoTro** [comment]
> > Hello Team,
> > I am getting below issue.
> > **Traceback (most recent call last): File "test1.py", line 1, in from chatterbot import ChatBot File "/opt/PythonLibs/ChatterBot/chatterbot/**init**.py", line 4, in from .chatterbot import ChatBot File "/opt/PythonLibs/ChatterBot/chatterbot/chatterbot.py", line 2, in from chatterbot.storage import StorageAdapter ImportError: No module named storage**
> 
> @dilip90 I guess you have written the name of the Storage Adapter wrong. It should be either **chatterbot.storage.SQLStorageAdapter**( for databases such as SQLite, MySQL or PostgreSQL ) or **chatterbot.storage.MongoDatabaseAdapter** for mongodb.
> 
> So you can change your line into: **from chatterbot.storage import SQLStorageAdapter**

It can't help in Python 2.7.15/ Windows,still show 
"Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    import chatterbot
  File "D:\python27\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "D:\python27\lib\site-packages\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ImportError: No module named storage"

**Comment by dilip90** [comment]
Thanks.

**Comment by theanmolgoyal** [comment]
Hi Team,
I am getting below issue.
from chatterbot.storage import SQLStorageAdapter,
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package

**Comment by gunthercox** [comment]
Hi @theanmolgoyal Have you installed `chatterbot` or downloaded the source code? One of these two things must be done before you can import it into your project.

**Comment by theanmolgoyal** [comment]
I installed chatterbot through command prompt and download source code.

**Comment by gunthercox** [comment]
Okay, that's good to hear. I'm going to run down a list of a few of the most common reasons that people encounter the error `'chatterbot' is not a package`. Please take a look at these and let me know if any of them sound like they might be the cause in your situation.

1. You've created a new file called `chatterbot.py` and put your code in it. This is a common issue. The reason this will cause an error is because Python thinks that any imports `from chatterbot` should be pulled from the current file, instead of the `chatterbot` library that you want it to use. If this is the case, then you just need to rename the file you have created to something else.
2. You have multiple version of Python installed. This is another common issue that people run into. Try running your commands like this to make sure that you are using Python 3 when installing **and** running your code:

```
python3 -m pip install chatterbot
python3 my_example.py
```
