### ISSUE TITLE
ImportError: cannot import name ChatBot

### ISSUE THREAD

**Issue by Mrtenz** [gunthercox/ChatterBot#146]
I copied an example, but get this when executing it:
```
Traceback (most recent call last):
  File "chatterbot.py", line 1, in <module>
    from chatterbot import ChatBot
  File "/root/taartbot/chatterbot.py", line 1, in <module>
    from chatterbot import ChatBot
ImportError: cannot import name ChatBot
```

**Comment by gunthercox** [comment]
This is a circular import error. You named your file `chatterbot.py`, then imported _from chatterbot_.
To fix this rename your `chatterbot.py` in `/root/taartbot/` to something else.

**Comment by Alquimerico** [comment]
Thanks, I was having same problem

**Comment by gunthercox** [comment]
@DhaneshKumarHeerani If you are trying to [run the tests](http://chatterbot.readthedocs.io/en/latest/testing.html) for this project, please use the command `python runtests.py`, this will run the test suite for Django.

**Comment by DhaneshKumarHeerani** [comment]
yes i did but it's not running i checked it showing this error 


C:\Users\Dhanesh\Desktop\Check it Please\ChatterBot-master>python runtests.py
Traceback (most recent call last):
  File "runtests.py", line 16, in <module>
    django.setup()
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\__init__.py", line 17, in setup
    configure_logging(settings.LOGGING_CONFIG, settings.LOGGING)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\conf\__init__.py", line 55, in __getattr__
    self._setup(name)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\conf\__init__.py", line 43, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\site-packages\django\conf\__init__.py", line 99, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\Dhanesh\AppData\Local\Programs\Python\Python35\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 944, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'mysite'

**Comment by vkosuri** [comment]
try to add current directory your python path I am not sure which operating system you are using, this command will work on Ubuntu ``export PYTHONPATH=${PYTHONPATH:."

**Comment by krishnakumarmoorthy** [comment]
check the spelling once again.it is "ChatBot" not Chatbot.Hope it works fine

**Comment by OtacilioN** [comment]
LMAO I just lost 1 hour with this.
