### ISSUE TITLE
Twitter authentication

### ISSUE THREAD

**Issue by talentoscope** [gunthercox/ChatterBot#1464]
I updated to the latest alpha and now Twitter doesn't authenticate.
Nothing has changed. The settings.py file is present, and despite copying and pasting to a Python3 shell to see what the error was, it gives
TwitterError("The twitter.Api instance must be authenticated.")

The py file I am running from has the minor version changes such as trainer.train(), etc, and they're the same as the documentation latest, so it's not that.

Bug maybe?

**Comment by talentoscope** [comment]
`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xxx/ChatterBot-1.0.0a2/chatterbot/trainers.py", line 251, in train
    statements = self.get_statements()
  File "/home/xxx/ChatterBot-1.0.0a2/chatterbot/trainers.py", line 230, in get_statements
    random_word = self.random_word(self.random_seed_word, self.lang)
  File "/home/xxx/ChatterBot-1.0.0a2/chatterbot/trainers.py", line 197, in random_word
    random_tweets = self.api.GetSearch(term=base_word, count=5, lang=lang)
  File "/home/xxx/.local/lib/python3.6/site-packages/twitter/api.py", line 526, in GetSearch
    resp = self._RequestUrl(url, 'GET', data=parameters)
  File "/home/xxx/.local/lib/python3.6/site-packages/twitter/api.py", line 4941, in _RequestUrl
    raise TwitterError("The twitter.Api instance must be authenticated.")
twitter.error.TwitterError: The twitter.Api instance must be authenticated.
`

**Comment by gunthercox** [comment]
Hi @talentoscope I labeled this a bug. I'll try to make sure this gets fixed before the next release. Thank you to testing out the alpha release.

**Comment by JustinBack** [comment]
Will this ever get working again? It's still present and you are unable to use the twitter example.
