### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: statement.extra_data [SQL: 'SELECT statement.id AS statement_id, statement.text AS statement_text, statement.extra_data AS

### ISSUE THREAD

**Issue by richardjiafei** [gunthercox/ChatterBot#1493]
Hi,   I have a problem , Could you help me to check?  Thank you.
when I　run　the　following　code　by　hug　　　

hug -f bot_api.py

 bot_api.py　is as follows:

#!/usr/bin/env python
# coding: utf-8

# 
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import hug

deepThought = ChatBot("deepThought")
deepThought.set_trainer(ChatterBotCorpusTrainer)
# 
deepThought.train("chatterbot.corpus.chinese")  #

# API framework
@hug.get()
def get_response(user_input):
    response = deepThought.get_response(user_input).text
    return {"response":response}

the following error happens, I don't know why, thank you.:

ai.yml Training: [                    ] 2%Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: statement.extra_data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\Scripts\hug-script.py", line 10, in <module>
    sys.exit(development_runner.hug.interface.cli())
  File "d:\ProgramData\Anaconda3\lib\site-packages\hug\interface.py", line 551, in __call__
    raise exception
  File "d:\ProgramData\Anaconda3\lib\site-packages\hug\interface.py", line 547, in __call__
    result = self.output(self.interface(**pass_to_function), context)
  File "d:\ProgramData\Anaconda3\lib\site-packages\hug\interface.py", line 100, in __call__
    return __hug_internal_self._function(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\hug\development_runner.py", line 59, in hug
    api_module = importlib.machinery.SourceFileLoader(file.split(".")[0], file).load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "bot_api.py", line 12, in <module>
    deepThought.train("chatterbot.corpus.chinese")  # 语料库
  File "d:\ProgramData\Anaconda3\lib\site-packages\chatterbot\trainers.py", line 159, in train
    statement = self.get_or_create(text)
  File "d:\ProgramData\Anaconda3\lib\site-packages\chatterbot\trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
  File "d:\ProgramData\Anaconda3\lib\site-packages\chatterbot\storage\sql_storage.py", line 132, in find
    record = query.first()
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 2895, in first
    ret = list(self[0:1])
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 2687, in __getitem__
    return list(res)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 2995, in __iter__
    return self._execute_and_instances(context)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\orm\query.py", line 3018, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "d:\ProgramData\Anaconda3\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: statement.extra_data [SQL: 'SELECT statement.id AS statement_id, statement.text AS statement_text, statement.extra_data AS statement_extra_data \nFROM statement \nWHERE statement.text = ?\n LIMIT ? OFFSET ?'] [parameters: ('什么是ai', 1, 0)] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by gunthercox** [comment]
Hi @richardjiafei, this error message is occurring because the column `extra_data` was removed from the database in the latest version of ChatterBot.

**Comment by blueclouray** [comment]
> Hi @richardjiafei, this error message is occurring because the column `extra_data` was removed from the database in the latest version of ChatterBot.

I want to run the example in the readme file and I have the same problem. What should I do? Thank you

**Comment by gunthercox** [comment]
To run the current examples, you will need to install chatterbot `1.0.0a2`.

This can be done with `pip`. For example, run `pip install chatterbot==1.0.0a2`
