### ISSUE TITLE
ChatterBot running in python 2.7.15 - Failed

### ISSUE THREAD

**Issue by isi007** [gunthercox/ChatterBot#1514]
2.7.15 (default, May 15 2018, 15:37:31) 
[GCC 7.3.1 20180303 (Red Hat 7.3.1-5)]
Python Type "help", "copyright", "credits" or "license" for more information.
[evaluate FeedBack-Lerning.py]
Traceback (most recent call last):
  File "/home/me/Documents/PythonScript/FeedBack-Lerning.py", line 21, in <module>
    trainer.train("chatterbot.corpus.english")
  File "/home/me/.local/lib/python2.7/site-packages/chatterbot/trainers.py", line 143, in train
    corpora = self.corpus.load_corpus(corpus_path)
  File "/home/me/.local/lib/python2.7/site-packages/chatterbot_corpus/corpus.py", line 87, in load_corpus
    data_file_paths = self.list_corpus_files(dotted_path)
  File "/home/me/.local/lib/python2.7/site-packages/chatterbot_corpus/corpus.py", line 76, in list_corpus_files
    paths = glob.glob(corpus_path + '/**/*.' + CORPUS_EXTENSION, recursive=True)
TypeError: glob() got an unexpected keyword argument 'recursive'

**Comment by vkosuri** [comment]
@isi007 I think chatterbot is deprecated on ``python 2.7``, did you tried on ``python3``
