### ISSUE TITLE
Terminal example: database(?) not working?

### ISSUE THREAD

**Issue by oliviaguest** [gunthercox/ChatterBot#1516]
I am using the latest version of ChatterBox from github and I am trying to run ```terminal_example.py```. I get the following error, what's going wrong?

```
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    database_uri="./database.db"
  File "/usr/local/lib/python3.6/site-packages/chatterbot/chatterbot.py", line 43, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/chatterbot/utils.py", line 53, in initialize_class
    return Class(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/chatterbot/storage/sql_storage.py", line 35, in __init__
    self.engine = create_engine(self.database_uri, convert_unicode=True)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/__init__.py", line 425, in create_engine
    return strategy.create(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 50, in create
    u = url.make_url(name_or_url)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 211, in make_url
    return _parse_rfc1738_args(name_or_url)
  File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/url.py", line 270, in _parse_rfc1738_args
    "Could not parse rfc1738 URL from string '%s'" % name)
sqlalchemy.exc.ArgumentError: Could not parse rfc1738 URL from string './database.db'
```

**Comment by Laurelai** [comment]
Having the same problem.

**Comment by gunthercox** [comment]
It looks like the documentation is out of date. Please use a valid URL string instead. For example:

```
sqlite:///database.db
```

**Comment by oliviaguest** [comment]
That fixes it! Thank you. If useful here's a PR for the two files that need it: https://github.com/gunthercox/ChatterBot/pull/1519
