### ISSUE TITLE
Cant't train

### ISSUE THREAD

**Issue by Sxigames** [gunthercox/ChatterBot#1526]
I can't train the chatterbot when i try i get this error
```
ai.yml Training: [                    ] 1%Traceback (most recent call last):
  File "...", line 12, in <module>
    trainer.train("chatterbot.corpus.english")
  File "C:\...\chatterbot\trainers.py", line 159, in train
    statement = self.get_or_create(text)
  File "C:\...\chatterbot\trainers.py", line 48, in get_or_create
    statement = self.storage.find(temp_statement.text)
AttributeError: 'ChatBot' object has no attribute 'find'
```

**Comment by gunthercox** [comment]
Hi @Sxigames, could you try downgrading to version `0.8.6`?

**Comment by Sxigames** [comment]
> Hi @Sxigames, could you try downgrading to version `0.8.6`?
I downgraded and doesn't work

**Comment by gunthercox** [comment]
@Sxigames Could this be related to the version of Python you are using, similar to #1465?

**Comment by Sxigames** [comment]
@gunthercox I found the error
```PYTHON
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer


chatbot = ChatBot('Robert')


trainer = ChatterBotCorpusTrainer(chatbot)


chatbot.set_trainer(ChatterBotCorpusTrainer)
chatbot.train("chatterbot.corpus.english")

```
