### ISSUE TITLE
table statement has no column named search_text

### ISSUE THREAD

**Issue by statcom** [gunthercox/ChatterBot#1551]
When I ran basic_example.py or the example in main page, I got following error message.

```
(venv) C:\\ChatterBot-master>python example_chat.py 
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\name\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
Traceback (most recent call last):
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table statement has no column named search_text

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "example_chat.py", line 12, in <module>
    "Your flight has been booked."
  File "C:\\ChatterBot-master\chatterbot\trainers.py", line 124, in train
    self.chatbot.storage.create_many(statements_to_create)
  File "C:\\ChatterBot-master\chatterbot\storage\sql_storage.py", line 267, in create_many
    session.commit()
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 954, in commit
    self.transaction.commit()
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 467, in commit
    self._prepare_impl()
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 447, in _prepare_impl
    self.session.flush()
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2313, in flush
    self._flush(objects)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2440, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 249, in reraise
    raise value
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\session.py", line 2404, in _flush
    flush_context.execute()
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 395, in execute
    rec.execute(self)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 560, in execute
    uow
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\orm\persistence.py", line 872, in _emit_insert_statements
    execute(statement, params)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 948, in execute
    return meth(self, multiparams, params)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 269, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1060, in _execute_clauseelement
    compiled_sql, distilled_params
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1200, in _execute_context
    context)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1413, in _handle_dbapi_exception
    exc_info
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 265, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\util\compat.py", line 248, in reraise
    raise value.with_traceback(tb)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1193, in _execute_context
    context)
  File "C:\\ChatterBot-master\venv\lib\site-packages\sqlalchemy\engine\default.py", line 509, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table statement has no column named search_text [SQL: 'INSERT INTO statement (text, search_text, conversation, created_at, in_response_to, search_in_response_to, persona) VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: ('Hi, can I help you?', 'PRP:support', 'training', '2019-01-06 23:47:46.464106', None, '', '')] (Background on this error at: http://sqlalche.me/e/e3q8)

```

**Comment by gunthercox** [comment]
Hi @statcom, it sounds like this might be an issue in ChatterBot. I'll mark this as a possible bug and research it further as soon as I have a chance.
