### ISSUE TITLE
can not able to run server 

### ISSUE THREAD

**Issue by svijay7598** [gunthercox/ChatterBot#1567]
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fc03f8d3048>
Traceback (most recent call last):
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    self.check(display_num_errors=True)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/core/management/base.py", line 379, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/core/management/base.py", line 366, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/core/checks/registry.py", line 71, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/urls/resolvers.py", line 396, in check
    for pattern in self.url_patterns:
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/urls/resolvers.py", line 533, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/utils/functional.py", line 37, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/urls/resolvers.py", line 526, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/vijay/workspace/anomaly/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vijay/workspace/simple-django-login-and-register/source/app/urls.py", line 16, in <module>
    path('accounts/', include('accounts.urls')),
  File "/home/vijay/workspace/anomaly/lib/python3.5/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/vijay/workspace/anomaly/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/vijay/workspace/simple-django-login-and-register/source/accounts/urls.py", line 3, in <module>
    from .views import (
  File "/home/vijay/workspace/simple-django-login-and-register/source/accounts/views.py", line 110
    user.username = f'user_{user.id}'
                                    ^
SyntaxError: invalid syntax

**Comment by gunthercox** [comment]
Hi @svijay7598, please take a look at this line from the traceback you posted:
```
File "/home/vijay/workspace/simple-django-login-and-register/source/accounts/views.py", line 110
user.username = f'user{user.id}'
^
SyntaxError: invalid syntax
```

This means that line number 110 in the file `/home/vijay/workspace/simple-django-login-and-register/source/accounts/views.py` has some code that isn't formatted correctly.

More specifically, the line of code in this file `username = f'user{user.id}'` is only valid when using Python 3 or higher. I'm guessing that you are probably trying to use an older version of Python (2.7 for example) to run your Django application.
