### ISSUE TITLE
Issue in getting chat output

### ISSUE THREAD

**Issue by AmilaMadushan** [gunthercox/ChatterBot#1572]
I am using Ubuntu 16.04 server and I have created a flask application and hosted using apache_wsgi script.
Individually.
my python file as follows
```
chatbot = ChatBot(
    'Dan',
    storage_adapter="chatterbot.storage.SQLStorageAdapter"
)
chatbot.set_trainer(ChatterBotCorpusTrainer)
chatbot.train(
    "chatterbot.corpus.english.greetings",
    "chatterbot.corpus.english.science",
    "chatterbot.corpus.english.history",
    "chatterbot.corpus.english.literature"

)
def chat(text):
    response = chatbot.get_response(text)
    if response.confidence >= 0.8:
        return response
   else:
       pass
```
when i run it individually its running but when i use the flask app its giving a error

`
[Wed Jan 16 10:08:27.875683 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] mod_wsgi (pid=2137): Target WSGI script '/var/www/html/predictionmodel/index.wsgi' cannot be loaded as Python module.
[Wed Jan 16 10:08:27.875736 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] mod_wsgi (pid=2137): Exception occurred processing WSGI script '/var/www/html/predictionmodel/index.wsgi'.
[Wed Jan 16 10:08:27.875963 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] Traceback (most recent call last):
[Wed Jan 16 10:08:27.875993 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
[Wed Jan 16 10:08:27.875996 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return fn()
[Wed Jan 16 10:08:27.876000 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 403, in connect
[Wed Jan 16 10:08:27.876002 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return _ConnectionFairy._checkout(self)
[Wed Jan 16 10:08:27.876005 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 791, in _checkout
[Wed Jan 16 10:08:27.876007 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     fairy = _ConnectionRecord.checkout(pool)
[Wed Jan 16 10:08:27.876011 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
[Wed Jan 16 10:08:27.876013 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     rec = pool._do_get()
[Wed Jan 16 10:08:27.876016 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1287, in _do_get
[Wed Jan 16 10:08:27.876018 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return self._create_connection()
[Wed Jan 16 10:08:27.876021 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
[Wed Jan 16 10:08:27.876023 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return _ConnectionRecord(self)
[Wed Jan 16 10:08:27.876026 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
[Wed Jan 16 10:08:27.876028 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     self.__connect(first_connect_check=True)
[Wed Jan 16 10:08:27.876031 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 674, in __connect
[Wed Jan 16 10:08:27.876033 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     connection = pool._invoke_creator(self)
[Wed Jan 16 10:08:27.876036 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
[Wed Jan 16 10:08:27.876038 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return dialect.connect(*cargs, **cparams)
[Wed Jan 16 10:08:27.876042 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 412, in connect
[Wed Jan 16 10:08:27.876043 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return self.dbapi.connect(*cargs, **cparams)
[Wed Jan 16 10:08:27.876052 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] sqlite3.OperationalError: unable to open database file
[Wed Jan 16 10:08:27.876057 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] 
[Wed Jan 16 10:08:27.876059 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] The above exception was the direct cause of the following exception:
[Wed Jan 16 10:08:27.876065 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] 
[Wed Jan 16 10:08:27.876068 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] Traceback (most recent call last):
[Wed Jan 16 10:08:27.876112 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/var/www/html/predictionmodel/index.wsgi", line 8, in <module>
[Wed Jan 16 10:08:27.876115 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     from index import app as application
[Wed Jan 16 10:08:27.876118 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/var/www/html/predictionmodel/index.py", line 25, in <module>
[Wed Jan 16 10:08:27.876120 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     from bot import chat
[Wed Jan 16 10:08:27.876123 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/var/www/html/predictionmodel/bot.py", line 10, in <module>
[Wed Jan 16 10:08:27.876125 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     storage_adapter="chatterbot.storage.SQLStorageAdapter"
[Wed Jan 16 10:08:27.876128 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 44, in __init__
[Wed Jan 16 10:08:27.876130 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     self.storage = utils.initialize_class(storage_adapter, **kwargs)
[Wed Jan 16 10:08:27.876134 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/chatterbot/utils.py", line 33, in initialize_class
[Wed Jan 16 10:08:27.876136 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return Class(**kwargs)
[Wed Jan 16 10:08:27.876139 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/chatterbot/storage/sql_storage.py", line 77, in __init__
[Wed Jan 16 10:08:27.876141 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     if not self.engine.dialect.has_table(self.engine, 'Statement'):
[Wed Jan 16 10:08:27.876144 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 1181, in has_table
[Wed Jan 16 10:08:27.876146 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     connection, "table_info", table_name, schema=schema)
[Wed Jan 16 10:08:27.876149 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/dialects/sqlite/base.py", line 1577, in _get_table_pragma
[Wed Jan 16 10:08:27.876151 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     cursor = connection.execute(statement)
[Wed Jan 16 10:08:27.876155 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2074, in execute
[Wed Jan 16 10:08:27.876157 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     connection = self.contextual_connect(close_with_result=True)
[Wed Jan 16 10:08:27.876160 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2123, in contextual_connect
[Wed Jan 16 10:08:27.876162 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     self._wrap_pool_connect(self.pool.connect, None),
[Wed Jan 16 10:08:27.876165 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2162, in _wrap_pool_connect
[Wed Jan 16 10:08:27.876171 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     e, dialect, self)
[Wed Jan 16 10:08:27.876174 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception_noconnection
[Wed Jan 16 10:08:27.876176 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     exc_info
[Wed Jan 16 10:08:27.876179 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 265, in raise_from_cause
[Wed Jan 16 10:08:27.876181 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     reraise(type(exception), exception, tb=exc_tb, cause=cause)
[Wed Jan 16 10:08:27.876184 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/util/compat.py", line 248, in reraise
[Wed Jan 16 10:08:27.876186 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     raise value.with_traceback(tb)
[Wed Jan 16 10:08:27.876190 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/base.py", line 2158, in _wrap_pool_connect
[Wed Jan 16 10:08:27.876191 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return fn()
[Wed Jan 16 10:08:27.876195 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 403, in connect
[Wed Jan 16 10:08:27.876196 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return _ConnectionFairy._checkout(self)
[Wed Jan 16 10:08:27.876200 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 791, in _checkout
[Wed Jan 16 10:08:27.876201 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     fairy = _ConnectionRecord.checkout(pool)
[Wed Jan 16 10:08:27.876204 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 532, in checkout
[Wed Jan 16 10:08:27.876206 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     rec = pool._do_get()
[Wed Jan 16 10:08:27.876209 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 1287, in _do_get
[Wed Jan 16 10:08:27.876211 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return self._create_connection()
[Wed Jan 16 10:08:27.876214 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 350, in _create_connection
[Wed Jan 16 10:08:27.876216 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return _ConnectionRecord(self)
[Wed Jan 16 10:08:27.876219 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 477, in __init__
[Wed Jan 16 10:08:27.876221 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     self.__connect(first_connect_check=True)
[Wed Jan 16 10:08:27.876224 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/pool.py", line 674, in __connect
[Wed Jan 16 10:08:27.876226 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     connection = pool._invoke_creator(self)
[Wed Jan 16 10:08:27.876229 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/strategies.py", line 106, in connect
[Wed Jan 16 10:08:27.876234 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return dialect.connect(*cargs, **cparams)
[Wed Jan 16 10:08:27.876237 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]   File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py", line 412, in connect
[Wed Jan 16 10:08:27.876239 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358]     return self.dbapi.connect(*cargs, **cparams)
[Wed Jan 16 10:08:27.876246 2019] [wsgi:error] [pid 2137:tid 140160567879424] [client 71.6.232.4:41358] sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file (Background on this error at: http://sqlalche.me/e/e3q8)
`

**Comment by gunthercox** [comment]
Hi @AmilaMadushan This sounds like an error related to file permissions.

You can check the file permissions using `ls -l db.sqlite3`
