### ISSUE TITLE
 AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

### ISSUE THREAD

**Issue by CharlieChengtianyue** [gunthercox/ChatterBot#1574]
Hi team
these day i always encounter this problem below:
 AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'
i have installed numpy but why always some problems like this?
thanks

**Comment by CharlieChengtianyue** [comment]
numpy version: 1.16.0

**Comment by Bonzadog** [comment]
I have the same error after 
pip3 install numpy
python3
import numpy and I get
>>> import numpy as np
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/__init__.py", line 59, in <module>
    from . import numeric
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/numeric.py", line 3093, in <module>
    from . import fromnumeric
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/fromnumeric.py", line 17, in <module>
    from . import _methods
  File "/home/pi/.local/lib/python3.5/site-packages/numpy/core/_methods.py", line 158, in <module>
    _NDARRAY_ARRAY_FUNCTION = mu.ndarray.__array_function__
AttributeError: type object 'numpy.ndarray' has no attribute '__array_function__'

I see nothing that I am doint wrong......

Please assist....many thanks

**Comment by gunthercox** [comment]
@Bonzadog Can you check what version of numpy you have installed? Using version `1.11.1` seems to have fixed this for @CharlieChengtianyue.
