### ISSUE TITLE
'ChatBot' object has no attribute 'set_trainer'

### ISSUE THREAD

**Issue by bufferbox** [gunthercox/ChatterBot#1617]
I am using Python 3.6.7 and chatterbot 0.8.7

**Here's my code:**

from chatterbot.trainers import ListTrainer
from chatterbot import ChatBot

bot = ChatBot('Bob')

conv = open('chat.txt', 'r').readlines()
bot.set_trainer(ListTrainer)
bot.train(conv)
bot.train("chatterbot.corpus.english")

while True:
    request = input('You: ')
    response = bot.get_response(request)
    print('Bob: ', response)

The error:

Traceback (most recent call last):
  File "C:\Users\zarai\OneDrive\Documents\KACST\BobBot\chatpot.py", line 1, in <module>
    from chatterbot.trainers import ListTrainer
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\chatterbot.py", line 3, in <module>
    from chatterbot.logic import LogicAdapter
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\logic\__init__.py", line 1, in <module>
    from chatterbot.logic.logic_adapter import LogicAdapter
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\logic\logic_adapter.py", line 3, in <module>
    from chatterbot.search import IndexedTextSearch
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\search.py", line 1, in <module>
    from chatterbot.conversation import Statement
  File "C:\Users\zarai\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\conversation.py", line 1, in <module>
    from pytz import UTC
ModuleNotFoundError: No module named 'pytz'

**Comment by gunthercox** [comment]
Hi @bufferbox, I see that you also left a comment on this related issue: #1555. I hope one of the options described there helped solve your issue?
***
For the error you've posted above (`ModuleNotFoundError: No module named 'pytz'`) you just need to install the `pytz` library.

```
python -m pip install pytz
```

**Comment by AlexandreUser** [comment]
You can just do 
* pip install pytz
