### ISSUE TITLE
Issue In Training with Ubuntu Corpus

### ISSUE THREAD

**Issue by sarangjain40** [gunthercox/ChatterBot#1650]
My code 
import logging
from chatterbot import ChatBot
from chatterbot.trainers import UbuntuCorpusTrainer

# Enable info level logging
logging.basicConfig(level=logging.INFO)

chatbot = ChatBot('Example Bot')

trainer = UbuntuCorpusTrainer(chatbot)

# Start by training our bot with the Ubuntu corpus data
trainer.train()

# Now let's get a response to a greeting
response = chatbot.get_response('How are you doing today?')
print(response)

When I run this, I get following error

    self._popen = self._Popen(self)
  File "D:\Users\Sarang_Jain\Anaconda3\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "D:\Users\Sarang_Jain\Anaconda3\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "D:\Users\Sarang_Jain\Anaconda3\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "D:\Users\Sarang_Jain\Anaconda3\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "chatbot2.py", line 17, in <module>
    trainer.train()
  File "D:\Users\Sarang_Jain\Anaconda3\lib\site-packages\chat.

Please help me resolve this issue. 

My chatterbot version is 1.0.4

**Comment by sarangjain40** [comment]
sorry it seems its a windows issues. I googled and found out that it works fine on ubuntu. I am not an expert on windows so can anyone help me how to resolve this.

**Comment by sarangjain40** [comment]
so i found a fix to the problem. 

if __name__ == '__main__':
	freeze_support()
	trainer = UbuntuCorpusTrainer(chatbot)
	# Start by training our bot with the Ubuntu corpus data
	trainer.train()
