### ISSUE TITLE
bot=ChatBot("mybot")

### ISSUE THREAD

**Issue by saucyy90** [gunthercox/ChatterBot#1659]

**Comment by saucyy90** [comment]
getting below error while creating object for the chatbot 
bot=ChatBot("Ravi\'s Bot ")
Traceback (most recent call last):
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 768, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 1231, in _do_get
    return self._create_connection()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    bot=ChatBot("Ravi\'s Bot ")
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\chatterbot\chatterbot.py", line 37, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\chatterbot\storage\sql_storage.py", line 125, in __init__
    if not self.engine.dialect.has_table(self.engine, 'StatementTable'):
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1181, in has_table
    connection, "table_info", table_name, schema=schema)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1572, in _get_table_pragma
    cursor = connection.execute(statement)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2063, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 768, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 1231, in _do_get
    return self._create_connection()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
>>> bot=ChatBot("Ravi\'s Bot ")
Traceback (most recent call last):
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 768, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 1231, in _do_get
    return self._create_connection()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    bot=ChatBot("Ravi\'s Bot ")
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\chatterbot\chatterbot.py", line 37, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\chatterbot\storage\sql_storage.py", line 125, in __init__
    if not self.engine.dialect.has_table(self.engine, 'StatementTable'):
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1181, in has_table
    connection, "table_info", table_name, schema=schema)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1572, in _get_table_pragma
    cursor = connection.execute(statement)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2063, in execute
    connection = self.contextual_connect(close_with_result=True)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2112, in contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2151, in _wrap_pool_connect
    e, dialect, self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 1465, in _handle_dbapi_exception_noconnection
    exc_info
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\base.py", line 2147, in _wrap_pool_connect
    return fn()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 387, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 768, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 516, in checkout
    rec = pool._do_get()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 1231, in _do_get
    return self._create_connection()
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 333, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 461, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\pool.py", line 651, in __connect
    connection = pool._invoke_creator(self)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\strategies.py", line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "C:\Users\rkuma164\AppData\Roaming\Python\Python36\site-packages\sqlalchemy\engine\default.py", line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
