### ISSUE TITLE
Error on running python manage.py runserver 0x03D9C738

### ISSUE THREAD

**Issue by it97** [gunthercox/ChatterBot#1681]
I am getting the below mentioned error when running the server. Has anybody experienced it ?Thanks you !
C:\Users\Dell\Desktop\DoAn\web\discrete_thesis\discrete>python manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03D9C738>
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\commands\runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\management\base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\checks\registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\core\checks\model_checks.py", line 27, in check_all_models
    errors.extend(model.check(**kwargs))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\models\base.py", line 1200, in check
    errors.extend(cls._check_fields(**kwargs))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\models\base.py", line 1272, in _check_fields
    errors.extend(field.check(**kwargs))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\models\fields\__init__.py", line 894, in check
    errors = super().check(**kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\models\fields\__init__.py", line 206, in check
    errors.extend(self._check_backend_specific_checks(**kwargs))
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\models\fields\__init__.py", line 303, in _check_backend_specific_checks
    return connections[db].validation.check_field(self, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\base\validation.py", line 21, in check_field
    field_type = field.db_type(self.connection)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\models\fields\__init__.py", line 648, in db_type
    return connection.data_types[self.get_internal_type()] % data
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\mysql\base.py", line 133, in data_types
    if self.features.supports_microsecond_precision:
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\mysql\features.py", line 65, in supports_microsecond_precision
    return self.connection.mysql_version >= (5, 6, 4)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\utils\functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\mysql\base.py", line 345, in mysql_version
    with self.temporary_connection() as cursor:
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 576, in temporary_connection
    cursor = self.cursor()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 255, in cursor
    return self._cursor()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 232, in _cursor
    self.ensure_connection()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 216, in ensure_connection
    self.connect()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\base\base.py", line 194, in connect
    self.connection = self.get_new_connection(conn_params)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\backends\mysql\base.py", line 236, in get_new_connection
    return Database.connect(**conn_params)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\connections.py", line 325, in __init__
    self.connect()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\connections.py", line 599, in connect
    self._request_authentication()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\connections.py", line 882, in _request_authentication
    auth_packet = _auth.caching_sha2_password_auth(self, auth_packet)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\_auth.py", line 264, in caching_sha2_password_auth
    data = sha2_rsa_encrypt(conn.password, conn.salt, conn.server_public_key)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pymysql\_auth.py", line 142, in sha2_rsa_encrypt
    raise RuntimeError("cryptography is required for sha256_password or caching_sha2_password")
RuntimeError: cryptography is required for sha256_password or caching_sha2_password

**Comment by gunthercox** [comment]
> RuntimeError: cryptography is required for sha256_password or caching_sha2_password

I've googled your error and it looks like there are a number of reasons that this error might occur.
I think the most likely option is that the `cryptography` package is not installed.

```
pip install cryptography
```
Source: https://stackoverflow.com/a/54586797/1547223

***
I hope this helps.
