### ISSUE TITLE
sqlite3.OperationalError: table statement has no column named search_text

### ISSUE THREAD

**Issue by sshubhoo** [gunthercox/ChatterBot#1694]
List Trainer: [####################] 100%
Traceback (most recent call last):
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table statement has no column named search_text

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "chatbot_train.py", line 18, in <module>
    setup()
  File "chatbot_train.py", line 14, in setup
    trainer.train(conversation)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\trainers.py", line 120, in train
    self.chatbot.storage.create_many(statements_to_create)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\sql_storage.py", line 267, in create_many
    session.commit()
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\session.py", line 1023, in commit
    self.transaction.commit()
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\session.py", line 487, in commit
    self._prepare_impl()
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\session.py", line 466, in _prepare_impl
    self.session.flush()
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\session.py", line 2446, in flush
    self._flush(objects)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\session.py", line 2584, in _flush
    transaction.rollback(_capture_exception=True)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\langhelpers.py", line 67, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 277, in reraise
    raise value
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\session.py", line 2544, in _flush
    flush_context.execute()
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 416, in execute
    rec.execute(self)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 583, in execute
    uow,
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\persistence.py", line 245, in save_obj
    insert,
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\orm\persistence.py", line 1116, in _emit_insert_statements
    statement, params
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\sql\elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1240, in _execute_context
    e, statement, parameters, cursor, context
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\util\compat.py", line 276, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\base.py", line 1236, in _execute_context
    cursor, statement, parameters, context
  File "C:\Users\shubbane\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\engine\default.py", line 536, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table statement has no column named search_text [SQL: 'INSERT INTO statement (text, search_text, conversation, created_at, in_response_to, search_in_response_to, persona) VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: ('categories:', 'categories', 'training', '2019-04-05 03:06:33.030838', None, '', '')] (Background on this error at: http://sqlalche.me/e/e3q8)

**Comment by gunthercox** [comment]
Interesting, the error says that the statement table `has no column named search_text`.

Could you describe the steps that I can use to recreate this error?

**Comment by a461925358** [comment]
同样的错误啊,你解决没
