### ISSUE TITLE
ImportError: No module named storage

### ISSUE THREAD

**Issue by GauravBahadur** [gunthercox/ChatterBot#1717]
`python chatbot_train.py
Traceback (most recent call last):
  File "chatbot_train.py", line 1, in <module>
    from chatterbot import ChatBot
  File "/home/gaurav/.local/lib/python2.7/site-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/home/gaurav/.local/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ImportError: No module named storage`

I have read other answers but I didn't understand what to do! Can be a little more descriptive.
I am using Ubuntu and python 3.6. 
I have downloaded Chatterbot. I would really appreciate if you could help me.

**Comment by UniqueUname** [comment]
It looks like you are not using python 3.6
You have to run it with `python3` command. (also install chatterbot again with `pip3`)
