### ISSUE TITLE
Regex issue special character crasher Chatterbot 1.0.5

### ISSUE THREAD

**Issue by rafak360** [gunthercox/ChatterBot#1730]
My settings:
Chatterbot = 1.0.5
Python 3.7.3 (64 bit)
MongoDB 4.0.9 (64 bit)

Everything works fine I can set an entry like 'hello world' whatever, but when using a special character followed by anything such as '(a' or '(z', anything after '(', so I get the exception below, it seems this character '(' has a special meaning in regex, by the way chatterbot version 0.8.7 doesn't have that issue, also when downloading Chatterbot through pip, that misses chatterbot-corpus module which I had to download manually, and that changes PyYAML version to 3.13 from 5.1 (PyYAML version which comes with chatterbot 1.0.5) so I had to get back to 5.1 after getting chatterbot-corpus module.

The following error:
```
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\example\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\example\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
Traceback (most recent call last):
  File "D:\MyDocuments\Desktop\Testing.py", line 12, in <module>
    print(chatbot.get_response('hello (a'))
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 139, in get_response
    response = self.generate_response(input_statement, additional_response_selection_parameters)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 175, in generate_response
    output = adapter.process(input_statement, additional_response_selection_parameters)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\logic\best_match.py", line 29, in process
    closest_match = next(search_results, input_statement)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\search.py", line 74, in search
    for statement in statement_list:
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\mongodb.py", line 127, in filter
    kwargs['search_text'] = re.compile(or_regex)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\re.py", line 234, in compile
    return _compile(pattern, flags)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\re.py", line 286, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 930, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 426, in _parse_sub
    not nested and not items))
  File "C:\Users\example\AppData\Local\Programs\Python\Python37\lib\sre_parse.py", line 819, in _parse
    source.tell() - start)
re.error: missing ), unterminated subpattern at position 3
```
To reproduce this error, here's my code:
```
from chatterbot import ChatBot
from chatterbot.comparisons import levenshtein_distance
from chatterbot.response_selection import get_most_frequent_response

if __name__ == "__main__":
    
    chatbot = ChatBot('Bot64Test', logic_adapters=[{'import_path': 'chatterbot.logic.BestMatch'}],
                      preprocessors=['chatterbot.preprocessors.clean_whitespace', 'chatterbot.preprocessors.unescape_html'],
                      statement_comparison_function=levenshtein_distance, response_selection_method=get_most_frequent_response,
                      storage_adapter='chatterbot.storage.MongoDatabaseAdapter', database_uri='mongodb://localhost:27017/databasebot64test')

    print(chatbot.get_response('hello (a'))
```

An explicit way to fix that would be placing a back slash \ before '(' in my entry, however converting string to raw string didn't help, any ideas how to fix that error?

**EDIT:**
I did a few more tests without using MongoDB and worked fine so I just found out that error is related to `storage_adapter='chatterbot.storage.MongoDatabaseAdapter'`. That's strange because I use same MongoDB in chatterbot 0.8.7 and that works fine so what's wrong with chatterbot 1.0.5?

**EDIT:**
I went further and found out that the problem is located at 

> chatterbot\storage\mongodb.py", line 127, in filter
>     kwargs['search_text'] = re.compile(or_regex)

So I commented out that line then problem solved, but I'm not sure how harmful it could be, I mean any side effects by commenting out that line?

**Comment by rafak360** [comment]
I fixed this issue and made a pull request, gotta wait admin merge it, for those who don't have the updated chatterbot with this issue fixed yet so here's the solution:
at chatterbot\storage\mongodb.py, line 125, in filter

change that line to: `'({})'.format(word) for word in search_text_contains.split(' ')`

That line was just missing parentheses, so to support regexes with | in them, the expression must be parenthesized.

**Comment by rafak360** [comment]
I fixed it and made a pull request, so we gotta wait admin merge it, however for those who don't have an updated chatterbot with this issue fixed yet, you can fix it by changing a simple line at chatterbot\storage\mongodb.py", line 125, in filter.
Change that line to: `'{}'.format(re.escape(word)) for word in search_text_contains.split(' ')`
