### ISSUE TITLE
cannot import name 'util' from 'sqlalchemy'

### ISSUE THREAD

**Issue by mistaah** [gunthercox/ChatterBot#1752]
just running simple chatbot and getting this error Help

![Capture](https://user-images.githubusercontent.com/39772446/59352821-03ed9700-8d3b-11e9-9eec-1ceb600ff165.PNG)

Traceback (most recent call last):
  File "D:\Console Application\train.py", line 16, in <module>
    setup()
  File "D:\Console Application\train.py", line 8, in setup
    trainer='chatterbot.trainers.ListTrainer')
  File "C:\Users\khano\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 39, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\khano\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "C:\Users\khano\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\sql_storage.py", line 41, in __init__
    from sqlalchemy import create_engine
  File "C:\Users\khano\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
ImportError: cannot import name 'util' from 'sqlalchemy' (C:\Users\khano\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy\__init__.py)
>>>

**Comment by gunthercox** [comment]
I haven't seen this error before, but you might want to take a look the last section of the error message, it looks like the error isn't coming from chatterbot:

```
File "C:\Users\khano\AppData\Local\Programs\Python\Python37\lib\site-packages\sqlalchemy_init_.py", line 8, in 
from . import util as util # noqa
ImportError: cannot import name 'util' from 'sqlalchemy' 
```
