### ISSUE TITLE
Nltk corpus file being open is not a zip file error

### ISSUE THREAD

**Issue by Manav1918** [gunthercox/ChatterBot#1754]
> /usr/local/lib/python3.5/dist-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "terminal_example.py", line 20, in <module>
    database="../database.db"
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 84, in __init__
    self.initialize()
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 94, in initialize
    nltk_download_corpus('corpora/wordnet')
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 640, in find
    return find(modified_name, paths)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 626, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/local/lib/python3.5/dist-packages/nltk/compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 473, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/local/lib/python3.5/dist-packages/nltk/compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 992, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

**Comment by gunthercox** [comment]
The error message `zipfile.BadZipFile: File is not a zip file` usually indicates that one of the corpus files failed to download correctly. This can be fixed if you delete the existing ones and re-download them (they should be in a folder somewhere on your system called `nltk_data`.

**Comment by Manav1918** [comment]
Thank u sir.... I'll try

Pawan Kumar

**Comment by Manav1918** [comment]
It's working now. Thanx

Pawan Kumar Prachi

**Comment by gunthercox** [comment]
Glad to hear :+1:
