### ISSUE TITLE
AttributeError: 'ChatBot' object has no attribute 'set_trainer' and AttributeError: 'ChatBot' object has no attribute 'train'

### ISSUE THREAD

**Issue by mallazhu** [gunthercox/ChatterBot#1756]
Python 3.6.8 (default, Jan 14 2019, 11:02:34)
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chatterbot import ChatBot
>>> from chatterbot.trainers import ListTrainer
>>> my_bot = ChatBot("Training demo")
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
>>> my_bot.set_trainer(ListTrainer)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ChatBot' object has no attribute 'set_trainer'
>>> my_bot.train([
...     "你叫什么名字？",
...     "我叫ChatterBot。",
...     "今天天气真好",
...     "是啊，这种天气出去玩再好不过了。",
...     "那你有没有想去玩的地方？",
...     "我想去有山有水的地方。你呢？",
...     "没钱哪都不去",
...     "哈哈，这就比较尴尬了",
... ])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ChatBot' object has no attribute 'train'
>>>

**Comment by mallazhu** [comment]
Which handsome man and beautiful woman can help me?
