### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by zurachf** [gunthercox/ChatterBot#1792]
trying to run this keep getting error any ideas?

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import os
from os import system, name
from time import sleep

def clear():
	if name == 'nt':
		_ = system('cls')
	else:
		_ = system('clear')
print('Loading...\n'*1)
sleep(1)
clear()

def setup():
    bot= ChatBot('Bot')
    wait = clear()
    trainer = ChatterBotCorpusTrainer(bot)

    corpus_path = 'D:/#1/test/'

    for file in os.listdir(corpus_path):
        trainer.train(corpus_path + file)
    name = input("Pls enter your name to begin:")
    print('Welcome', name,'ask me anything you like!')

    while True:
        message = input(name + ":")
        #print(message)
        if message.strip() == 'Bye':
            print('ChatBot: Bye')
            break
        else:
            reply = bot.get_response(message)
            print('ChatBot:', reply)

setup()

ERROR:

Traceback (most recent call last):
  File "D:\#1\scraping websites\chatbot_train.py", line 1, in <module>
    from chatterbot import ChatBot #import the chatbot
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosHypernymTagger
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\tagging.py", line 8, in <module>
    import spacy
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 12, in <module>
    from .cli.info import info as cli_info
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\__init__.py", line 6, in <module>
    from .train import train  # noqa: F401
  File "C:\Users\zurac\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\cli\train.py", line 18, in <module>
    from ..gold import GoldCorpus
  File "strings.pxd", line 23, in init spacy.gold
ImportError: DLL load failed: The specified module could not be found.

Process returned 1 (0x1)        execution time : 1.600 s

**Comment by HassanSheraz** [comment]
hi dear how you have solved this problem?

**Comment by HassanSheraz** [comment]
@zurachf help me please

**Comment by zurachf** [comment]
Didn't solve it, Tried it with Ubuntu instead and it worked 🤔

**Comment by HassanSheraz** [comment]
@zurachf  i was facing same problem but solved just uninstall anaconda and remove directory from c and installed again problem solved

**Comment by rtferreiro** [comment]
@HassanSheraz could you give more details on how you solved this problem?
