### ISSUE TITLE
Custom YML file training problem.

### ISSUE THREAD

**Issue by ItZ-Debaditya** [gunthercox/ChatterBot#1799]
I have created my own custom YML file named myfile.yml and I wanted to train my bot with it.
I pasted my YML file in the folder which contains other YML files on which it is already trained. the address of the folder is as : 
```
C:\Users\debo\AppData\Local\Packages\CanonicalGroupLimited.Ubuntu18.04onWindows_79rhkp1fndgsc\LocalState\rootfs

\home\debo_ubuntu\.local\lib\python3.6\site-packages\chatterbot_corpus\data\english
```
 I wrote the py file in sublime text and ran it through ubuntu terminal. 
my code for the bot is:
``` Python
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

bot = ChatBot(
    "Chat Bot",
    storage_adapter="chatterbot.storage.SQLStorageAdapter",
    logic_adapters=[
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter',
        'chatterbot.logic.BestMatch'
    ],
    database="botData.sqlite3"
)

trainer = ChatterBotCorpusTrainer(bot)

trainer.train("chatterbot.corpus.english")

# The following loop will execute each time the user enters input
while True:
        user_input = input()
        if user_input !="stop" : 
           bot_response = bot.get_response(user_input)
           print(bot_response)

        else:
           break
           print('exit')
```
Upon running it in the terminal it was showing an error that it could not find any file named myfile.yml. So I copied the content of myfile.yml and pasted in ai.yml but it is still showing an error as: 
```  Bash
Traceback (most recent call last):
  File "chatbot_response.py", line 44, in <module>
    "chatterbot.corpus.english"
  File "/home/debo_ubuntu/.local/lib/python3.6/site-packages/chatterbot/trainers.py", line 138, in train
    for corpus, categories, file_path in load_corpus(*data_file_paths):
  File "/home/debo_ubuntu/.local/lib/python3.6/site-packages/chatterbot/corpus.py", line 63, in load_corpus
    corpus_data = read_corpus(file_path)
  File "/home/debo_ubuntu/.local/lib/python3.6/site-packages/chatterbot/corpus.py", line 37, in read_corpus
    with io.open(file_name, encoding='utf-8') as data_file:
**PermissionError: [Errno 13] Permission denied: '/home/debo_ubuntu/.local/lib/python3.6/site-packages/chatterbot_corpus/data/english/ai.yml'**
```

Remember that previously the bot was being trained with all the pre-existing yml files and it was running with no error and giving satisfactory results. 

Please Help me out of this situation. I am currently involved in a project which extensively uses this chatbot.

THANK YOU.

**Comment by vkosuri** [comment]
by looking tracers chatterbot unable to read corpus or yaml file. Please check where do you have exact privileges to read corpus file.

**Comment by AdmiralMills** [comment]
Hello I have been having a similar problem. 
@vkosuri 
I used the same format for YAML files as what is inside the chatterbot.corpus.english file. I inserted a custom YAML file in it but when I try to train the bot it will only respond with the first possible response to the user input instead of getting a random response. Is there a way to get around that? It will not get random responses from the premade corpus files either so it is probably something inside my program.

`from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

from chatterbot.response_selection import get_random_response

my_bot = ChatBot(name='Test Bot',read_only = True,
                 storage_adapter="chatterbot.storage.SQLStorageAdapter",
                 response_selection_method=get_random_response,
                 logic_adapters=[
        {
            'import_path': 'chatterbot.logic.SpecificResponseAdapter',
            'input_text': 'empty',
            'output_text': ''
        },
        {   
            'import_path': 'chatterbot.logic.BestMatch',
            'default_response': 'i honestly have no idea how to respond to that',
            'maximum_similarity_threshold': 0.9
        },
        {
            'import_path': 'chatterbot.logic.MathematicalEvaluation'
        }
        
        ],
        database = "db.sqlite3"
    )

trainer = ChatterBotCorpusTrainer(my_bot)

trainer.train(
    "chatterbot.corpus.english"
)

while True:
    try:
        user_input = input()

        bot_response = my_bot.get_response(user_input)

        print(bot_response)

    # Press ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break`

Can you see what the issue could be? I have been trying many different methods but this seems to get me the closest to what I am hoping will happen albeit the lack of multiple responses.
Any help is greatly appreciated.

**Comment by AdmiralMills** [comment]
I see, I realized what the issue is. For a YAML file to work I need to format it as follows:
'''
category:
- random
conversations:
- - Pickle
  - Are weird cucumbers
- - Pickle
  - What about them?
'''
I had it formatted as:
'''
category:
- random
conversations:
- - Pickle
  - Are weird cucumbers
  - cow
  - fish
'''

I hope that it able to be overcome in the future but that is how it must be for now.
Thanks anyway. I hope this helps someone else.
Happy Holidays!
