### ISSUE TITLE
Trying to MySQL as backend with Django 1.11 and Python 2.7

### ISSUE THREAD

**Issue by anilkumar2612** [gunthercox/ChatterBot#1807]
Applying mogbot.0001_initial...Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\amarati\python\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\amarati\python\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\amarati\python\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\amarati\python\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Users\amarati\python\lib\site-packages\django\core\management\commands\migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "C:\Users\amarati\python\lib\site-packages\django\db\migrations\executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "C:\Users\amarati\python\lib\site-packages\django\db\migrations\executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "C:\Users\amarati\python\lib\site-packages\django\db\migrations\executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "C:\Users\amarati\python\lib\site-packages\django\db\migrations\migration.py", line 119, in apply
    operation.state_forwards(self.app_label, project_state)
  File "C:\Users\amarati\python\lib\site-packages\django\db\migrations\operations\fields.py", line 74, in state_forwards
    state.models[app_label, self.model_name_lower].fields.append((self.name, field))
KeyError: (u'mogbot', u'response')

It was working fine with sqlite but was trying to migrate these error happened. 
I tweaked the models file and moved the model directly into django app. here are the models files
[models.txt](https://github.com/gunthercox/ChatterBot/files/3552132/models.txt)
[abstract_models.txt](https://github.com/gunthercox/ChatterBot/files/3552133/abstract_models.txt)

**Comment by anilkumar2612** [comment]
These are my app settings -


CHATTERBOT = {
    'name':'Tech Support Bot',
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'storage_adapter': 'chatterbot.storage.DjangoStorageAdapter',
    'input_adapter': 'chatterbot.input.VariableInputTypeAdapter',
    'output_adapter': 'chatterbot.output.OutputAdapter',
    'training_data': [
        'chatterbot.corpus.english.greetings'
       ],
    'logic_adapters':[
            {
            'import_path':'chatterbot.logic.BestMatch'
            },
            {
            'import_path':'chatterbot.logic.LowConfidenceAdapter',
            'threshold':0.7,
            'default_response':'I am sorry, but I do not understand.'
            }
        ],
    'django_app_name': 'mogbot'
}

**Comment by anilkumar2612** [comment]
got it resolved.. thank you very much

**Comment by vkosuri** [comment]
Glad to hear it was resolved
