### ISSUE TITLE
how to add own list in chatterbot.logic.TimeLogicAdapter

### ISSUE THREAD

**Issue by sohamnandi007** [gunthercox/ChatterBot#1829]
I want to add my own list for chatterbot.logic.TimeLogicAdapter but probably getting syntax error at the import path. please help me out..! please also tell what is **krawgs nad how to insert or use one i am not getting it by reading the documentation

``` Python
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from tkinter import *
import pyttsx3 as pp
import os


engine = pp.init()
voices = engine.getProperty('voices')
print(voices)

engine.setProperty('voice', voices[1].id)

time_positive=['what is the time right now','what is the current time','what is the time now','what’s the time','what time is it',
'what time is it now','do you know what time it is','could you tell me the time, please','what is the time','will you tell me the time',
'tell me the time','time','show me the time']

time_negative=['what is','what are you doing','what’s up','could you','do you','what’s the','will you','tell me','show me','current','do you']

def speak(word):
    engine.say(word)
    engine.runAndWait()


bot = ChatBot( "my Bot", read_only=True,
    logic_adapters=[
{'chatterbot.logic.MathematicalEvaluation','chatterbot.logic.UnitConversion','chatterbot.logic.BestMatch'},
    {
        'import_path': 'chatterbot.logic.TimeLogicAdapter',
        'positive': 'time_positive',
        'negative': 'time_negative'
    }
    ] 
    )
trainer = ListTrainer(bot)

for _file in os.listdir('files'):
    chats = open('files/' + _file, 'r').readlines()
    
    trainer.train(chats)



#now training thebot with the help of `trainer`

main= Tk()

main.geometry("500x650")

main.title("My chat bot")
img = PhotoImage(file="logo.png")
photoL=Label(main,image= img)

photoL.pack(pady=5)

def ask_from_bot():
    query = textF.get()
    with open('text.txt', "a") as f:
        f.write (query + '\n');
    answer_from_bot = bot.get_response(query)
    with open('text.txt', "a") as f:
        f.write (str(answer_from_bot) + '\n');
    msgs.insert(END, "you: " + query)
    msgs.insert(END, "bot: " + str(answer_from_bot))
    textF.delete(0, END)
    msgs.yview(END)
    speak(answer_from_bot)

frame= Frame(main)

sc = Scrollbar(frame)
msgs = Listbox(frame,width=80,height=20, yscrollcommand=sc.set)#scrollbar issue

sc.pack(side=RIGHT, fill=Y)
msgs.pack(side=LEFT, fill=BOTH, pady=10)

frame.pack()

#creating text field
textF = Entry(main, font=("Verdana", 20))
textF.pack(fill=X, pady=10)
btn=Button(main, text="Ask from Bot", font=("Verdana", 20), command=ask_from_bot)
btn.pack()

#creating a function
def enter_function(event):
    btn.invoke()

#going to bing window with enter key
main.bind('<Return>', enter_function)

main.mainloop()
```

**Comment by sohamnandi007** [comment]
> 
> 
> Instead of using quotes use names for example
> 
> ```python
> bot = ChatBot( "my Bot", read_only=True,
>     logic_adapters=[
>         {
>             'chatterbot.logic.MathematicalEvaluation',
>             'chatterbot.logic.UnitConversion',
>             'chatterbot.logic.BestMatch'
>         },
>         {
>             'import_path': 'chatterbot.logic.TimeLogicAdapter',
>             'positive': time_positive,
>             'negative': time_negative
>         }
>     ]

@vkosuri @rmdort @quan-nh 
@ryancollingwood  still not woring
getting this error:

Traceback (most recent call last):
  File "main.py", line 31, in <module>
    'negative': time_negative
  File "C:\Users\soham\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 37, in __init__
    utils.validate_adapter_class(adapter, LogicAdapter)
  File "C:\Users\soham\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 78, in validate_adapter_class
    if not issubclass(import_module(validate_class), adapter_class):
  File "C:\Users\soham\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 14, in import_module
    module_parts = dotted_path.split('.')
AttributeError: 'set' object has no attribute 'split'

**Comment by sohamnandi007** [comment]
**Thank you @gunthercox @ryancollingwood @quan-nh @rmdort @vkosuri** .. I tried out the solution. Finally, I got the answer.
I would like to request you, please include this example in the documentation for others - **how to add own list in "chatterbot.logic.TimeLogicAdapter" and call it** 

Thank you. 

here is my final code:
```

from chatterbot import ChatBot #import the chatbot
from chatterbot.trainers import ListTrainer #method to train chatbot
from chatterbot.trainers import ChatterBotCorpusTrainer
import os

# import logging
# logging.basicConfig(level=logging.INFO)

#here is how to create your own time list
time_positive = ['what is the time right now','time','clock','what is the current time', 'what is the time now', 'what’s the time', 'what time is it', 
'what time is it now', 'do you know what time it is', 'could you tell me the time, please', 'what is the time', 'will you tell me the time', 
'tell me the time','time please', 'show me the time', 'what is time', 'whats on the clock', 'show me the clock',
 'what is the time','what is on the clock','tell me time','time','clock',]

time_negative = ['what are you doing', 'what’s up','when is time','who is time' 'could you', 'do you', 'what’s', 'will you', 'tell me', 'show me', 'current', 'do', 'now', 
'will', 'show', 'tell','me', 'could', 'what', 'whats', 'i have time', 'who', 'who is', 'hardtime','when','what is','how',
'how is','when is','who is time','how is time','how is time','when is time']

bot = ChatBot(
    'Example Bot', read_only=True,
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.BestMatch',
            'default_response': 'I am sorry, but I do not understand.',
            'maximum_similarity_threshold': 0.75
        },
        { #here is how to call the TimeLogicAdapter when you create your own list
            'import_path': 'chatterbot.logic.TimeLogicAdapter',
            'positive': time_positive,
            'negative': time_negative
        }
    ]
)

trainer = ListTrainer(bot) #set the trainer

for _file in os.listdir('files'):
    chats = open('files/' + _file, 'r').readlines()
    
    trainer.train(chats)


filename = input ("write your name: ");
while True:
    request =input("you: ") 
    with open(filename, "a") as f:
        f.write (request + '\n');

    response = bot.get_response(request)
    print("bot: " + str(response))

    with open(filename, "a") as f:
        f.write (str(response) + '\n');
```
