### ISSUE TITLE
ValueError: Extra Data

### ISSUE THREAD

**Issue by mackgrenfell** [gunthercox/ChatterBot#183]
Hello,

I'm getting this error whenever I try to train or get a response from chatterbot, any suggestions?

Traceback (most recent call last):
  File "C:\Users\Mack\Documents\Python Scripts\Kd\qtdev.py", line 33, in <module>
    chatbot.train("chatterbot.corpus.english.conversations")
  File "D:\Users\Mack\Anaconda\lib\site-packages\chatterbot\training\trainers.py", line 48, in train
    trainer.train(pair)
  File "D:\Users\Mack\Anaconda\lib\site-packages\chatterbot\training\trainers.py", line 22, in train
    statement = self.storage.find(text)
  File "D:\Users\Mack\Anaconda\lib\site-packages\chatterbot\adapters\storage\jsondatabase.py", line 26, in find
    values = self.database.data(key=statement_text)
  File "D:\Users\Mack\Anaconda\lib\site-packages\jsondb\db.py", line 72, in data
    return self._get_content(key)
  File "D:\Users\Mack\Anaconda\lib\site-packages\jsondb\db.py", line 26, in _get_content
    obj = read_data(self.path)
  File "D:\Users\Mack\Anaconda\lib\site-packages\jsondb\file_writer.py", line 11, in read_data
    obj = decode(content)
  File "D:\Users\Mack\Anaconda\lib\site-packages\jsondb\compat.py", line 22, in decode
    return json_decode(value)
  File "D:\Users\Mack\Anaconda\lib\json\__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "D:\Users\Mack\Anaconda\lib\json\decoder.py", line 369, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 4338846 - line 1 column 4342418 (char 4338845 - 4342417)

Many thanks!

**Comment by mackgrenfell** [comment]
Solved. Database cleared. A bit embarrassing.
