### ISSUE TITLE
ChatterBot does not get trained with ubuntu corpus

### ISSUE THREAD

**Issue by demosthenesk** [gunthercox/ChatterBot#1832]
I can not train the bot with ubuntu corpus.
my code is:
```
# import ChatBot
from chatterbot import ChatBot
# import Trainer
from chatterbot.trainers import UbuntuCorpusTrainer

bot = ChatBot('Zeus')

# Training
trainer = UbuntuCorpusTrainer(bot)
print("url: ", trainer.data_download_url)
print("data dir: ", trainer.data_directory)
print("extracted dir: ", trainer.extracted_data_directory)
print("is downloaded: ", trainer.is_downloaded(trainer.data_directory))
print("is extracted: ", trainer.is_extracted(trainer.extracted_data_directory))
trainer.train()

# Get a response to an input statement
bot.get_response("Hello, how are you today?")

while True:
    # Input from user
    message = input('You: ')
    # if message is not "Bye"
    if message.strip() != 'Bye':
        reply = bot.get_response(message)
        print('Zeus:', reply)
        # if message is "Bye"
    if message.strip() == 'Bye':
        print('Zeus: Bye')
        break

```
And the output is:

> /usr/bin/python3.7 /home/user/Documents/python-workspace/chatbot/UbuntuCorpus.py
> [nltk_data] Downloading package averaged_perceptron_tagger to
> [nltk_data]     /home/user/nltk_data...
> [nltk_data]   Package averaged_perceptron_tagger is already up-to-
> [nltk_data]       date!
> [nltk_data] Downloading package stopwords to /home/user/nltk_data...
> [nltk_data]   Package stopwords is already up-to-date!
> url:  http://cs.mcgill.ca/~jpineau/datasets/ubuntu-corpus-1.0/ubuntu_dialogs.tgz
> data dir:  /home/user/ubuntu_data
> extracted dir:  /home/user/ubuntu_data/ubuntu_dialogs
> is downloaded:  True
> is extracted:  True
> Training took 0.13010787963867188 seconds.
> You: 
> 
The bot is not trained with ubuntu corpus...

**Comment by Benji377** [comment]
This is what I get when executing your code:

> [nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\benbe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\benbe\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
url:  http://cs.mcgill.ca/~jpineau/datasets/ubuntu-corpus-1.0/ubuntu_dialogs.tgz
data dir:  C:\Users\benbe\ubuntu_data
extracted dir:  C:\Users\benbe\ubuntu_data\ubuntu_dialogs
is downloaded:  True
is extracted:  True
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\benbe\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\benbe\AppData\Roaming\nltk_data...
url:  http://cs.mcgill.ca/~jpineau/datasets/ubuntu-corpus-1.0/ubuntu_dialogs.tgz
data dir:  C:\Users\benbe\ubuntu_data
extracted dir:  C:\Users\benbe\ubuntu_data\ubuntu_dialogs
is downloaded:  True
is extracted:  True
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Coding\PyProjects\Sociality\Sociality3\Test\test2\tester.py", line 15, in <module>
    trainer.train()
  File "C:\Users\benbe\.virtualenvs\benbe-ZCclz55H\lib\site-packages\chatterbot\trainers.py", line 342, in train
    manager = Manager()
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\managers.py", line 513, in start
    self._process.start()
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\process.py", line 105, in start
    self._popen = self._Popen(self)
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\popen_spawn_win32.py", line 33, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\benbe\AppData\Local\Programs\Python\Python36\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
