### ISSUE TITLE
My computer no install chatterbot

### ISSUE THREAD

**Issue by Guigalaverna** [gunthercox/ChatterBot#1846]
Hi devs

My computer no install 

Hello developers my chatterbot are not on my windows machine i don't know why but i came here on github to ask for a help from you

Error :

`ERROR: Command errored out with exit status 1:
   command: 'c:\users\fabio alexandre\appdata\local\programs\python\python38-32\python.exe' 'c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Fabio Alexandre\AppData\Local\Temp\pip-build-env-qg054q1u\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (229 lines):
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/d9/de/554b6310ac87c5b921bc45634b07b11394fe63bc4cb5176f5240addf18ab/setuptools-41.6.0-py2.py3-none-any.whl
  Collecting wheel<0.33.0,>0.32.0
    Using cached https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
  Collecting Cython
    Using cached https://files.pythonhosted.org/packages/a5/1f/c7c5450c60a90ce058b47ecf60bb5be2bfe46f952ed1d3b95d1d677588be/Cython-0.29.13.tar.gz
  Collecting cymem<2.1.0,>=2.0.2
    Using cached https://files.pythonhosted.org/packages/8b/dc/0976e04cc46f86e0dd3ee3797ec68057eaafebf31daca9a076dc138b9920/cymem-2.0.2.tar.gz
  Collecting preshed<2.1.0,>=2.0.1
    Using cached https://files.pythonhosted.org/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://files.pythonhosted.org/packages/22/e9/411be1845f1ac07ae3bc40a4b19ba401819baed4fa63b4f5ef28b2300eb4/murmurhash-1.0.2.tar.gz
  Collecting thinc<7.1.0,>=7.0.8
    Using cached https://files.pythonhosted.org/packages/92/39/ea2a3d5b87fd52fc865fd1ceb7b91dca1f85e227d53e7a086d260f6bcb93/thinc-7.0.8.tar.gz
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\fabio alexandre\appdata\local\programs\python\python38-32\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Fabio Alexandre\\AppData\\Local\\Temp\\pip-install-w4ylp251\\thinc\\setup.py'"'"'; __file__='"'"'C:\\Users\\Fabio Alexandre\\AppData\\Local\\Temp\\pip-install-w4ylp251\\thinc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Fabio Alexandre\AppData\Local\Temp\pip-install-w4ylp251\thinc\pip-egg-info'
           cwd: C:\Users\Fabio Alexandre\AppData\Local\Temp\pip-install-w4ylp251\thinc\
      Complete output (209 lines):
      Could not locate executable g77
      Could not locate executable f77
      Could not locate executable ifort
      Could not locate executable ifl
      Could not locate executable f90
      Could not locate executable DF
      Could not locate executable efl
      Could not locate executable gfortran
      Could not locate executable f95
      Could not locate executable g95
      Could not locate executable efort
      Could not locate executable efc
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
      'svnversion' nÆo ‚ reconhecido como um comando interno
      ou externo, um programa oper vel ou um arquivo em lotes.
      non-existing path in 'numpy\\distutils': 'site.cfg'
      Running from numpy source directory.
      C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\setup.py:418: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\system_info.py:690: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        self.calc_info()
      C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\system_info.py:690: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        self.calc_info()
      C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\system_info.py:690: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        self.calc_info()
      C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\system_info.py:1712: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        if getattr(self, '_calc_info_{}'.format(lapack))():
      c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      Traceback (most recent call last):
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
          self.run_command("egg_info")
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\command\egg_info.py", line 26, in run
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\command\build_src.py", line 142, in run
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\command\build_src.py", line 150, in build_sources
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\command\build_src.py", line 267, in build_py_modules_sources
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\misc_util.py", line 2270, in generate_config_py
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\dir_util.py", line 70, in mkpath
          os.mkdir(head, mode)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 310, in wrap
          path = self._remap_input(name, path, *args, **kw)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 452, in _remap_input
          self._violation(operation, os.path.realpath(path), *args, **kw)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 407, in _violation
          raise SandboxViolation(operation, args, kw)
      setuptools.sandbox.SandboxViolation: SandboxViolation: mkdir('C:\\Users\\FABIOA~1\\AppData\\Local\\Temp\\easy_install-gw42ee35\\numpy-1.17.3\\build', 511) {}

      The package setup script has attempted to modify files on your system
      that are not within the EasyInstall build area, and has been aborted.

      This package cannot be safely installed by EasyInstall, and may not
      support alternate installation locations even if you run its setup
      script by hand.  Please inform the package's author and the EasyInstall
      maintainers to find out if a fix or workaround is available.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
          yield saved
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\setup.py", line 443, in <module>
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\setup.py", line 435, in setup_package
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\core.py", line 171, in setup
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: SandboxViolation: mkdir('C:\\Users\\FABIOA~1\\AppData\\Local\\Temp\\easy_install-gw42ee35\\numpy-1.17.3\\build', 511) {}

      The package setup script has attempted to modify files on your system
      that are not within the EasyInstall build area, and has been aborted.

      This package cannot be safely installed by EasyInstall, and may not
      support alternate installation locations even if you run its setup
      script by hand.  Please inform the package's author and the EasyInstall
      maintainers to find out if a fix or workaround is available.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
          run_setup(setup_script, args)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
          raise
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
          yield saved
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\setup.py", line 443, in <module>
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\setup.py", line 435, in setup_package
        File "C:\Users\FABIOA~1\AppData\Local\Temp\easy_install-gw42ee35\numpy-1.17.3\numpy\distutils\core.py", line 171, in setup
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\distutils\core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: SandboxViolation: mkdir('C:\\Users\\FABIOA~1\\AppData\\Local\\Temp\\easy_install-gw42ee35\\numpy-1.17.3\\build', 511) {}

      The package setup script has attempted to modify files on your system
      that are not within the EasyInstall build area, and has been aborted.

      This package cannot be safely installed by EasyInstall, and may not
      support alternate installation locations even if you run its setup
      script by hand.  Please inform the package's author and the EasyInstall
      maintainers to find out if a fix or workaround is available.

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\Fabio Alexandre\AppData\Local\Temp\pip-install-w4ylp251\thinc\setup.py", line 261, in <module>
          setup_package()
        File "C:\Users\Fabio Alexandre\AppData\Local\Temp\pip-install-w4ylp251\thinc\setup.py", line 201, in setup_package
          setup(
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
          return installer(requirement)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
          raise DistutilsError("Setup script exited with %s" % (v.args[0],))
      distutils.errors.DistutilsError: Setup script exited with error: SandboxViolation: mkdir('C:\\Users\\FABIOA~1\\AppData\\Local\\Temp\\easy_install-gw42ee35\\numpy-1.17.3\\build', 511) {}

      The package setup script has attempted to modify files on your system
      that are not within the EasyInstall build area, and has been aborted.

      This package cannot be safely installed by EasyInstall, and may not
      support alternate installation locations even if you run its setup
      script by hand.  Please inform the package's author and the EasyInstall
      maintainers to find out if a fix or workaround is available.

      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\fabio alexandre\appdata\local\programs\python\python38-32\python.exe' 'c:\users\fabio alexandre\appdata\local\programs\python\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\Fabio Alexandre\AppData\Local\Temp\pip-build-env-qg054q1u\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.`

**Comment by thewasta** [comment]
Use Python 3.7 and may sure it's x64 and to make sure use `--no-cache-dir` to prevent use of cache

**Comment by sohamnandi007** [comment]
Hello @Guigalaverna, I would suggest reinstall python 3.7.2 also keep in mind to delete the cache file after uninstalling. So,
delete the pip folder from C:\Users\soham\AppData\Local\pip and
delete the old python setup files from C:\Users\soham\AppData\Local\Programs\Python
then reinstall python 3.7.2
then pip install chatterbot
it will work

**Comment by PreeteshPal** [comment]
Hi, i have tried the above but still it's not working, locust is not installing, it giving me error while installing

Collecting locustio                                                               Using cached locustio-0.13.5-py2.py3-none-any.whl (261 kB)                    Collecting six>=1.10.0                                                            Using cached six-1.14.0-py2.py3-none-any.whl (10 kB)                          Collecting flask>=0.10.1                                                          Using cached Flask-1.1.1-py2.py3-none-any.whl (94 kB)                         Collecting geventhttpclient-wheels==1.3.1.dev2                                    Using cached geventhttpclient-wheels-1.3.1.dev2.tar.gz (54 kB)                Collecting pyzmq>=16.0.2                                                          Using cached pyzmq-18.1.1-cp38-cp38-win_amd64.whl (1.1 MB)                    Collecting requests>=2.9.1                                                        Using cached requests-2.22.0-py2.py3-none-any.whl (57 kB)                     Collecting gevent==1.5a2                                                          Using cached gevent-1.5a2.tar.gz (5.4 MB)                                       Installing build dependencies ... error                                         ERROR: Command errored out with exit status 1:                                   command: 'c:\python\python38\python.exe' 'c:\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\PREETESH\AppData\Local\Temp\pip-build-env-slaqnt27\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 0.29.13' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet>=0.4.14 ; platform_python_implementation == '"'"'CPython'"'"''                                                                            cwd: None                                                                  Complete output (28 lines):                                                     Collecting setuptools>=40.8.0                                                     Using cached setuptools-45.1.0-py3-none-any.whl (583 kB)                      Collecting wheel                                                                  Using cached wheel-0.33.6-py2.py3-none-any.whl (21 kB)                        Collecting Cython>=0.29.13                                                        Using cached Cython-0.29.14-cp38-cp38-win_amd64.whl (1.7 MB)                  Collecting cffi>=1.12.3                                                           Using cached cffi-1.13.2-cp38-cp38-win_amd64.whl (175 kB)                     Collecting greenlet>=0.4.14                                                       Using cached greenlet-0.4.15.tar.gz (59 kB)                                   Collecting pycparser                                                              Using cached pycparser-2.19.tar.gz (158 kB)                                   Installing collected packages: setuptools, wheel, Cython, pycparser, cffi, greenlet                                                                                 Running setup.py install for pycparser: started                                 Running setup.py install for pycparser: finished with status 'done'             Running setup.py install for greenlet: started                                  Running setup.py install for greenlet: finished with status 'error'             ERROR: Command errored out with exit status 1:                                   command: 'c:\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PREETESH\\AppData\\Local\\Temp\\pip-install-v9nsyg2f\\greenlet\\setup.py'"'"'; __file__='"'"'C:\\Users\\PREETESH\\AppData\\Local\\Temp\\pip-install-v9nsyg2f\\greenlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PREETESH\AppData\Local\Temp\pip-record-ltlrwa5r\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\PREETESH\AppData\Local\Temp\pip-build-env-slaqnt27\overlay' --compile --install-headers 'C:\Users\PREETESH\AppData\Local\Temp\pip-build-env-slaqnt27\overlay\Include\greenlet'                         cwd: C:\Users\PREETESH\AppData\Local\Temp\pip-install-v9nsyg2f\greenlet\                                                                                   Complete output (5 lines):                                                      running install                                                                 running build                                                                   running build_ext                                                               building 'greenlet' extension                                                   error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/                     ----------------------------------------                                    ERROR: Command errored out with exit status 1: 'c:\python\python38\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\PREETESH\\AppData\\Local\\Temp\\pip-install-v9nsyg2f\\greenlet\\setup.py'"'"'; __file__='"'"'C:\\Users\\PREETESH\\AppData\\Local\\Temp\\pip-install-v9nsyg2f\\greenlet\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\PREETESH\AppData\Local\Temp\pip-record-ltlrwa5r\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\PREETESH\AppData\Local\Temp\pip-build-env-slaqnt27\overlay' --compile --install-headers 'C:\Users\PREETESH\AppData\Local\Temp\pip-build-env-slaqnt27\overlay\Include\greenlet' Check the logs for full command output.                       ----------------------------------------                                      ERROR: Command errored out with exit status 1: 'c:\python\python38\python.exe' 'c:\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\PREETESH\AppData\Local\Temp\pip-build-env-slaqnt27\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools >= 40.8.0' wheel 'Cython >= 0.29.13' 'cffi >= 1.12.3 ; platform_python_implementation == '"'"'CPython'"'"'' 'greenlet>=0.4.14 ; platform_python_implementation == '"'"'CPython'"'"'' Check the logs for full command output.                                                                          


Can anyone please help in that, thanks
