### ISSUE TITLE
Ubuntu Corpus Training error on windows

### ISSUE THREAD

**Issue by neilkerman** [gunthercox/ChatterBot#1874]
Hi, 
I am trying to implement ubuntu corpus trainer on my code, however I'm getting the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 114, in _main
    prepare(preparation_data)
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\sbhat\PycharmProjects\Harrison\harrison.py", line 16, in <module>
    trainer.train()
  File "C:\Users\sbhat\PycharmProjects\Harrison\venv\lib\site-packages\chatterbot\trainers.py", line 342, in train
    manager = Manager()
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 56, in Manager
    m.start()
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\managers.py", line 563, in start
    self._process.start()
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\popen_spawn_win32.py", line 46, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\sbhat\AppData\Local\Programs\Python\Python37\lib\multiprocessing\spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

And here's my code:

from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.trainers import UbuntuCorpusTrainer
import logging

logging.basicConfig(level=logging.INFO)

chatbot = ChatBot('Harrison')

trainer = UbuntuCorpusTrainer(chatbot)
#trainer2 = ChatterBotCorpusTrainer(chatbot)

#trainer2.train(
    #'chatterbot.corpus.english'
#)
trainer.train()
#trainer2.train()

while True:
    response = chatbot.get_response(input("Enter Query: "))
    print(response)

I would be highly obliged if anyone could help me solve this error, thanks.
Neil

**Comment by ahmedkhalf** [comment]
I have the same error :(

**Comment by RandolphNimmer** [comment]
Also having this problem
