### ISSUE TITLE
I am getting a error in installing chatterbot

### ISSUE THREAD

**Issue by aniruddha1111** [gunthercox/ChatterBot#1895]

**Comment by aniruddha1111** [comment]
ERROR: Command errored out with exit status 1:
   command: 'c:\users\andym.k\appdata\local\programs\python\python38\python.exe' 'c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\ANDYM.K\AppData\Local\Temp\pip-build-env-rmikjajf\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (219 lines):
  Collecting setuptools
    Using cached https://files.pythonhosted.org/packages/af/e7/02db816dc88c598281bacebbb7ccf2c9f1a6164942e88f1a0fded8643659/setuptools-45.0.0-py2.py3-none-any.whl
  Collecting wheel<0.33.0,>0.32.0
    Using cached https://files.pythonhosted.org/packages/ff/47/1dfa4795e24fd6f93d5d58602dd716c3f101cfd5a77cd9acbe519b44a0a9/wheel-0.32.3-py2.py3-none-any.whl
  Collecting Cython
    Using cached https://files.pythonhosted.org/packages/41/2c/9d873fc8d1be29af12a1d41707461399327396da10e50e183754aa4136b9/Cython-0.29.14-cp38-cp38-win_amd64.whl
  Collecting cymem<2.1.0,>=2.0.2
    Using cached https://files.pythonhosted.org/packages/8c/1f/43be34e4decc602fae2bda73b05525bc49deff44baeb95611b23a2929195/cymem-2.0.3-cp38-cp38-win_amd64.whl
  Collecting preshed<2.1.0,>=2.0.1
    Using cached https://files.pythonhosted.org/packages/0b/14/c9aa735cb9c131545fc9e23031baccb87041ac9215b3d75f99e3cf18f6a3/preshed-2.0.1.tar.gz
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached https://files.pythonhosted.org/packages/5b/73/129c1aed56c88a446c70e4eda186fe014bfb8330478e5e257cc923bd3e15/murmurhash-1.0.2-cp38-cp38-win_amd64.whl
  Collecting thinc<7.1.0,>=7.0.8
    Using cached https://files.pythonhosted.org/packages/92/39/ea2a3d5b87fd52fc865fd1ceb7b91dca1f85e227d53e7a086d260f6bcb93/thinc-7.0.8.tar.gz
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\andym.k\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ANDYM.K\\AppData\\Local\\Temp\\pip-install-kekm0x57\\thinc\\setup.py'"'"'; __file__='"'"'C:\\Users\\ANDYM.K\\AppData\\Local\\Temp\\pip-install-kekm0x57\\thinc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
           cwd: C:\Users\ANDYM.K\AppData\Local\Temp\pip-install-kekm0x57\thinc\
      Complete output (197 lines):
      Processing numpy/random\_bounded_integers.pxd.in
      Processing numpy/random\mtrand.pyx
      Processing numpy/random\_bit_generator.pyx
      Processing numpy/random\_bounded_integers.pyx.in
      Processing numpy/random\_common.pyx
      Processing numpy/random\_generator.pyx
      Processing numpy/random\_mt19937.pyx
      Processing numpy/random\_pcg64.pyx
      Processing numpy/random\_philox.pyx
      Processing numpy/random\_sfc64.pyx
      Cythonizing sources
      Could not locate executable g77
      Could not locate executable f77
      Could not locate executable ifort
      Could not locate executable ifl
      Could not locate executable f90
      Could not locate executable DF
      Could not locate executable efl
      Could not locate executable gfortran
      Could not locate executable f95
      Could not locate executable g95
      Could not locate executable efort
      Could not locate executable efc
      Could not locate executable flang
      don't know how to compile Fortran code on platform 'nt'
      'svnversion' is not recognized as an internal or external command,
      operable program or batch file.
      non-existing path in 'numpy\\distutils': 'site.cfg'
      Running from numpy source directory.
      C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\setup.py:461: UserWarning: Unrecognized setuptools command, proceeding with generating Cython sources and expanding templates
        run_build = parse_setuppy_commands()
      C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\system_info.py:1896: UserWarning:
          Optimized (vendor) Blas libraries are not found.
          Falls back to netlib Blas library which has worse performance.
          A better performance should be easily gained by switching
          Blas library.
        if self._calc_info(blas):
      C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\system_info.py:1896: UserWarning:
          Blas (http://www.netlib.org/blas/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [blas]) or by setting
          the BLAS environment variable.
        if self._calc_info(blas):
      C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\system_info.py:1896: UserWarning:
          Blas (http://www.netlib.org/blas/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [blas_src]) or by setting
          the BLAS_SRC environment variable.
        if self._calc_info(blas):
      C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\system_info.py:1730: UserWarning:
          Lapack (http://www.netlib.org/lapack/) libraries not found.
          Directories to search for the libraries can be specified in the
          numpy/distutils/site.cfg file (section [lapack]) or by setting
          the LAPACK environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\system_info.py:1730: UserWarning:
          Lapack (http://www.netlib.org/lapack/) sources not found.
          Directories to search for the sources can be specified in the
          numpy/distutils/site.cfg file (section [lapack_src]) or by setting
          the LAPACK_SRC environment variable.
        return getattr(self, '_calc_info_{}'.format(name))()
      c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\dist.py:274: UserWarning: Unknown distribution option: 'define_macros'
        warnings.warn(msg)
      Traceback (most recent call last):
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 489, in _find_latest_available_vc_ver
          return self.find_available_vc_vers()[-1]
      IndexError: list index out of range

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\bdist_egg.py", line 163, in run
          self.run_command("egg_info")
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\command\egg_info.py", line 26, in run
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\command\build_src.py", line 146, in run
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\command\build_src.py", line 157, in build_sources
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\command\build_src.py", line 290, in build_library_sources
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\command\build_src.py", line 380, in generate_sources
        File "numpy\core\setup.py", line 656, in get_mathlib_info
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\command\config.py", line 241, in try_link
          self._check_compiler()
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\command\config.py", line 54, in _check_compiler
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\_msvccompiler.py", line 253, in initialize
          vc_env = _get_vc_env(plat_spec)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 185, in msvc14_get_vc_env
          return EnvironmentInfo(plat_spec, vc_min_ver=14.0).return_env()
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 843, in __init__
          self.si = SystemInfo(self.ri, vc_ver)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 485, in __init__
          self.vc_ver = vc_ver or self._find_latest_available_vc_ver()
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\msvc.py", line 492, in _find_latest_available_vc_ver
          raise distutils.errors.DistutilsPlatformError(err)
      distutils.errors.DistutilsPlatformError: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
          yield saved
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\setup.py", line 488, in <module>
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\setup.py", line 480, in setup_package
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\core.py", line 171, in setup
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1144, in run_setup
          run_setup(setup_script, args)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 253, in run_setup
          raise
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\contextlib.py", line 131, in __exit__
          self.gen.throw(type, value, traceback)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 166, in save_modules
          saved_exc.resume()
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 141, in resume
          six.reraise(type, exc, self._tb)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\_vendor\six.py", line 685, in reraise
          raise value.with_traceback(tb)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 154, in save_modules
          yield saved
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 195, in setup_context
          yield
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 250, in run_setup
          _execfile(setup_script, ns)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\sandbox.py", line 45, in _execfile
          exec(code, globals, locals)
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\setup.py", line 488, in <module>
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\setup.py", line 480, in setup_package
        File "C:\Users\ANDYM.K\AppData\Local\Temp\easy_install-3bww7yag\numpy-1.18.1\numpy\distutils\core.py", line 171, in setup
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 145, in setup
          return distutils.core.setup(**attrs)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\distutils\core.py", line 163, in setup
          raise SystemExit("error: " + str(msg))
      SystemExit: error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\ANDYM.K\AppData\Local\Temp\pip-install-kekm0x57\thinc\setup.py", line 261, in <module>
          setup_package()
        File "C:\Users\ANDYM.K\AppData\Local\Temp\pip-install-kekm0x57\thinc\setup.py", line 201, in setup_package
          setup(
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
          return installer(requirement)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 679, in easy_install
          return self.install_item(spec, dist.location, tmpdir, deps)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 705, in install_item
          dists = self.install_eggs(spec, download, tmpdir)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 890, in install_eggs
          return self.build_and_install(setup_script, setup_base)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1158, in build_and_install
          self.run_setup(setup_script, setup_base, args)
        File "c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 1146, in run_setup
          raise DistutilsError("Setup script exited with %s" % (v.args[0],))
      distutils.errors.DistutilsError: Setup script exited with error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
  You should consider upgrading via the 'python -m pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\andym.k\appdata\local\programs\python\python38\python.exe' 'c:\users\andym.k\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\ANDYM.K\AppData\Local\Temp\pip-build-env-rmikjajf\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.
