### ISSUE TITLE
AttributeError: 'dict' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by TimPchelintsev** [gunthercox/ChatterBot#192]
When using mongodb, got this error:
```python
Traceback (most recent call last):
  File "examples/terminal_mongo_example.py", line 19, in <module>
    bot_input = bot.get_response(None)
  File "/Users/timofey/Projects/ChatterBot/chatterbot/chatterbot.py", line 136, in get_response
    confidence, response = self.logic.process(input_statement)
  File "/Users/timofey/Projects/ChatterBot/chatterbot/adapters/logic/multi_adapter.py", line 27, in process
    confidence, output = adapter.process(statement)
  File "/Users/timofey/Projects/ChatterBot/chatterbot/adapters/logic/base_match.py", line 47, in process
    self.context.storage.update(closest_match)
  File "/Users/timofey/Projects/ChatterBot/chatterbot/adapters/storage/mongodb.py", line 126, in update
    data = statement.serialize()
  File "/Users/timofey/Projects/ChatterBot/chatterbot/conversation/statement.py", line 81, in serialize
    data["in_response_to"].append(response.serialize())
AttributeError: 'dict' object has no attribute 'serialize'
```
Seems it is because of mongo adapter custom get_response_statements realization with no deserealize_responses call before making a Statement classes from dicts.

Managed to fix it via #191

Thanks for great lib!

**Comment by futetest** [comment]
Hi

I was getting the same error as you. Used your fix but now its throwing new error, could you please look into it.

`Traceback (most recent call last):
  File "mongoBot.py", line 19, in <module>
    bot_input = bot.get_response(None)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 136, in get_response
    confidence, response = self.logic.process(input_statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/logic/multi_adapter.py", line 27, in process
    confidence, output = adapter.process(statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/logic/base_match.py", line 44, in process
    confidence, closest_match = self.get(input_statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/logic/closest_meaning.py", line 113, in get
    similarity = self.get_similarity(input_statement.text, statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/adapters/logic/closest_meaning.py", line 82, in get_similarity
    return total_similarity/len(tokens2)
ZeroDivisionError: integer division or modulo by zero
`
