### ISSUE TITLE
"AttributeError: 'str' object has no attribute 'isoformat'" when using chatterbot with MySQL database and charset set to utf8

### ISSUE THREAD

**Issue by farooqkz** [gunthercox/ChatterBot#1927]
Hello. When trying to use Chatterbot with Persian language and setting charset to UTF-8, I get this error when using MySQL instead of SQLite:
```
Traceback (most recent call last):
  File "example.py", line 5, in <module>
    print(C.get_response("سلام"))
  File "/home/farooqkz/.local/lib/python3.6/site-packages/chatterbot/chatterbot.py", line 121, in get_response
    response = self.generate_response(input_statement, additional_response_selection_parameters)
  File "/home/farooqkz/.local/lib/python3.6/site-packages/chatterbot/chatterbot.py", line 154, in generate_response
    output = adapter.process(input_statement, additional_response_selection_parameters)
  File "/home/farooqkz/.local/lib/python3.6/site-packages/chatterbot/logic/best_match.py", line 29, in process
    closest_match = next(search_results, input_statement)
  File "/home/farooqkz/.local/lib/python3.6/site-packages/chatterbot/search.py", line 74, in search
    for statement in statement_list:
  File "/home/farooqkz/.local/lib/python3.6/site-packages/chatterbot/storage/sql_storage.py", line 175, in filter
    yield self.model_to_object(statement)
  File "/home/farooqkz/.local/lib/python3.6/site-packages/chatterbot/storage/sql_storage.py", line 71, in model_to_object
    return StatementObject(**statement.serialize())
  File "/home/farooqkz/.local/lib/python3.6/site-packages/chatterbot/conversation.py", line 33, in serialize
    'created_at': self.created_at.isoformat().split('+', 1)[0],
AttributeError: 'str' object has no attribute 'isoformat'
```
Here's my code:
```python
import chatterbot
db_uri = "mysql://user:password@localhost/mydb?charset=utf8"
adapter = "chatterbot.storage.SQLStorageAdapter"
C = chatterbot.ChatBot("Joe", database_uri = db_uri, storage_adapter = adapter)
print(C.get_response("سلام"))
```

**Comment by gunthercox** [comment]
I believe this issue has been resolved in newer versions of ChatterBot. Namely it looks like the current logic uses a default for `created_at` if one is not provided.

I realize this is an old issue, so I'm going to close this off for now, but feel free to let me know if issues persist.
