### ISSUE TITLE
problem when calling custom adapter

### ISSUE THREAD

**Issue by mcallejas95** [gunthercox/ChatterBot#1936]
Hi good day!

I am something new to chatterbot, I am currently following this documentation: [Docs](https://chatterbot.readthedocs.io/en/stable/logic/create-a-logic-adapter.html) in order to create a logical adapter to not accept rude input, until Now I have not been lucky.

This is my mistake:

`Traceback (most recent call last):
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\MTI\Documents\MTI\chatbot\chatbot-covid19\app.py", line 16, in getResponse
    respuesta_chat = getResultBot(pregunta_cliente, entrenar_act)
  File "C:\Users\MTI\Documents\MTI\chatbot\chatbot-covid19\main_core.py", line 40, in getResultBot
    respuesta = chatbot.get_response(pregunta)
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\chatterbot\chatterbot.py", line 139, in get_response
    response = self.generate_response(input_statement, additional_response_selection_parameters)
  File "C:\Users\MTI\Documents\MTI\chatbot\covid19\lib\site-packages\chatterbot\chatterbot.py", line 175, in generate_response
    output = adapter.process(input_statement, additional_response_selection_parameters)
TypeError: process() takes 2 positional arguments but 3 were given`

this is my code: 

- Config. Chatbot

`chatbot = ChatBot(
    "Covid-19",
    storage_adapter="chatterbot.storage.SQLStorageAdapter",
    database="./database.sqlite5", 
    trainer="chatterbot.trainers.ListTrainer",

    logic_adapters=[
        {
           "import_path": "chatterbot.logic.BestMatch",
           "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
           "response_selection_method": "chatterbot.response_selection.get_most_frequent_response"
        },
        {
           "import_path": "my_adapter.MyLogicAdapter1"
       }
    ],
    read_only=entrenamiento
)`

- Logic Adapter

`class MyLogicAdapter1(LogicAdapter):

	def __init__(self, chatbot, **kwargs):
		super().__init__(chatbot, **kwargs)

	def can_process(self, statement):
		word_list = ['stupid', 'idiot']
		for word in word_list:
			if word in statement.text:
				print('valido groseria')
				return True
		return False

	def process(self, statement, **kwargs):
		response = Statement(text='¡Heeeey!')
		confidence = 1
		return confidence, response`

in advance I appreciate your help :/

**Comment by CathalButler** [comment]
I second this, same issue and really need a fix!

**Comment by CathalButler** [comment]
I found the issue,

Change 
 `def process(self, statement, **kwargs):` in MyLogicAdapter1 class 
to 
` def process(self, statement, additional_response_selection_parameters):`
