### ISSUE TITLE
keyError:'chatterbot'

### ISSUE THREAD

**Issue by mxnxsh** [gunthercox/ChatterBot#1940]
C:\Users\manis>python -m chatterbot --version
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\manis\AppData\Roaming\Python\Python37\site-packages\chatterbot\__main__.py", line 20, in <module>
    print(get_chatterbot_version())
  File "C:\Users\manis\AppData\Roaming\Python\Python37\site-packages\chatterbot\__main__.py", line 15, in get_chatterbot_version
    return config['chatterbot']['version']
  File "C:\ProgramData\Anaconda3\lib\configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'chatterbot'

#after installing chatterbot i'm not able to check it version after giving the command it get keyError:"chatterbot"

**Comment by songproducer** [comment]
I'm also experiencing this

**Comment by songproducer** [comment]
git clone https://github.com/gunthercox/ChatterBot.git
python3 setup.py install
fixed for me

**Comment by mallikarjunasai995** [comment]
If u have installed through Anaconda Editor. please change the directory to ChatterBot folder and check for the version.

**Comment by mxnxsh** [comment]
> git clone https://github.com/gunthercox/ChatterBot.git
> python3 setup.py install
> fixed for me

this work fine

**Comment by anurag-git1** [comment]
i also experiencing this

**Comment by serialmetrics** [comment]
After running the following, I am only able to successfully check the version in the download directory: ~/path_to_chatterbot



git clone https://github.com/gunthercox/ChatterBot.git
python3 setup.py install
fixed for me
