### ISSUE TITLE
Unable to install ChatterBot In windows 10 python.

### ISSUE THREAD

**Issue by LS255** [gunthercox/ChatterBot#1962]
C:\Users\L. S. (Alas)>pip install chatterbot
Collecting chatterbot
  Using cached ChatterBot-1.0.5-py2.py3-none-any.whl (67 kB)
Collecting pint>=0.8.1
  Using cached Pint-0.11-py2.py3-none-any.whl (186 kB)
Collecting pymongo<4.0,>=3.3
  Using cached pymongo-3.10.1-cp38-cp38-win_amd64.whl (355 kB)
Collecting pyyaml<5.2,>=5.1
  Using cached PyYAML-5.1.2.tar.gz (265 kB)
Collecting python-dateutil<2.8,>=2.7
  Using cached python_dateutil-2.7.5-py2.py3-none-any.whl (225 kB)
Collecting pytz
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
     |████████████████████████████████| 510 kB 93 kB/s
Collecting spacy<2.2,>=2.1
  Using cached spacy-2.1.9.tar.gz (30.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\l. s. (alas)\appdata\local\programs\python\python38\python.exe' 'c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\L. S. (Alas)\AppData\Local\Temp\pip-build-env-_d3der4w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'
       cwd: None
  Complete output (65 lines):
  Collecting setuptools
    Using cached setuptools-46.1.3-py3-none-any.whl (582 kB)
  Collecting wheel<0.33.0,>0.32.0
    Using cached wheel-0.32.3-py2.py3-none-any.whl (21 kB)
  Collecting Cython
    Using cached Cython-0.29.17-cp38-cp38-win_amd64.whl (1.7 MB)
  Collecting cymem<2.1.0,>=2.0.2
    Using cached cymem-2.0.3-cp38-cp38-win_amd64.whl (33 kB)
  Collecting preshed<2.1.0,>=2.0.1
    Using cached preshed-2.0.1.tar.gz (113 kB)
  Collecting murmurhash<1.1.0,>=0.28.0
    Using cached murmurhash-1.0.2-cp38-cp38-win_amd64.whl (20 kB)
  Collecting thinc<7.1.0,>=7.0.8
    Using cached thinc-7.0.8.tar.gz (1.9 MB)
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\l. s. (alas)\appdata\local\programs\python\python38\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\L. S. (Alas)\\AppData\\Local\\Temp\\pip-install-580m_hj8\\thinc\\setup.py'"'"'; __file__='"'"'C:\\Users\\L. S. (Alas)\\AppData\\Local\\Temp\\pip-install-580m_hj8\\thinc\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\L. S. (Alas)\AppData\Local\Temp\pip-install-580m_hj8\thinc\pip-egg-info'
           cwd: C:\Users\L. S. (Alas)\AppData\Local\Temp\pip-install-580m_hj8\thinc\
      Complete output (45 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\L. S. (Alas)\AppData\Local\Temp\pip-install-580m_hj8\thinc\setup.py", line 261, in <module>
          setup_package()
        File "C:\Users\L. S. (Alas)\AppData\Local\Temp\pip-install-580m_hj8\thinc\setup.py", line 201, in setup_package
          setup(
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 144, in setup
          _install_setup_requires(attrs)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
          dist.fetch_build_eggs(dist.setup_requires)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 716, in fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 780, in resolve
          dist = best[req.key] = env.best_match(
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
          return self.obtain(req, installer)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
          return installer(requirement)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\dist.py", line 786, in fetch_build_egg
          return cmd.easy_install(req)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\command\easy_install.py", line 665, in easy_install
          dist = self.package_index.fetch_distribution(
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\package_index.py", line 655, in fetch_distribution
          dist = find(requirement)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\package_index.py", line 635, in find
          loc = self.download(dist.location, tmpdir)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\package_index.py", line 579, in download
          found = self._download_url(scheme.group(1), spec, tmpdir)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\package_index.py", line 824, in _download_url
          return self._attempt_download(url, filename)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\package_index.py", line 830, in _attempt_download
          headers = self._download_to(url, filename)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\setuptools\package_index.py", line 745, in _download_to
          block = fp.read(bs)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\http\client.py", line 454, in read
          n = self.readinto(b)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\http\client.py", line 498, in readinto
          n = self.fp.readinto(b)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\socket.py", line 669, in readinto
          return self._sock.recv_into(b)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\ssl.py", line 1241, in recv_into
          return self.read(nbytes, buffer)
        File "c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\ssl.py", line 1099, in read
          return self._sslobj.read(len, buffer)
      socket.timeout: The read operation timed out
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\l. s. (alas)\appdata\local\programs\python\python38\python.exe' 'c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\L. S. (Alas)\AppData\Local\Temp\pip-build-env-_d3der4w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

ERROR: Command errored out with exit status 1: 'c:\users\l. s. (alas)\appdata\local\programs\python\python38\python.exe' 'c:\users\l. s. (alas)\appdata\local\programs\python\python38\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\L. S. (Alas)\AppData\Local\Temp\pip-build-env-_d3der4w\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output.

please help I am using python3.8.2

**Comment by vkosuri** [comment]
could you try install sapcy2.1, ``pip3 install sapcy<2.1``

**Comment by LS255** [comment]
Visual Studio c++ build tool is necessary for installing chatterbot? ?
    Please reply. As well as possible.

Please....

**Comment by vkosuri** [comment]
Yes Few modules required, i am not sure which modules

**Comment by LS255** [comment]
ERROR: Command ereored out with exit status 1 : Python setup.py egg_info

  This is the error. Please help how to solve it.

**Comment by vkosuri** [comment]
try to install ``pip3 install --upgrade spacy<=2.1``
