### ISSUE TITLE
ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by Kolterdyx** [gunthercox/ChatterBot#1971]
I am trying to make a simple chatbot to interact with my computer, but when I try to run my code i get the following error:

```
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from chatterbot import ChatBot
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/chatterbot/storage/__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/chatterbot/storage/storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosHypernymTagger
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/chatterbot/tagging.py", line 3, in <module>
    from chatterbot import utils
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/chatterbot/utils.py", line 4, in <module>
    from nltk.corpus import wordnet
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/__init__.py", line 149, in <module>
    from nltk.translate import *
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/translate/__init__.py", line 23, in <module>
    from nltk.translate.meteor_score import meteor_score as meteor
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/translate/meteor_score.py", line 10, in <module>
    from nltk.stem.porter import PorterStemmer
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/stem/__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/stem/snowball.py", line 29, in <module>
    from nltk.corpus import stopwords
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/corpus/__init__.py", line 66, in <module>
    from nltk.corpus.reader import *
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/corpus/reader/__init__.py", line 105, in <module>
    from nltk.corpus.reader.panlex_lite import *
  File "/home/kolterdyx/.local/lib/python3.6/site-packages/nltk/corpus/reader/panlex_lite.py", line 15, in <module>
    import sqlite3
  File "/usr/local/lib/python3.6/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.6/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

I have tried installing with pip, from github, reinstalling, upgrading, and installing dependencies manually, but I always get the same error.

**Comment by ignertic** [comment]
By any chance you are running this on an IoT device like a rasberry-pi?

**Comment by Kolterdyx** [comment]
I am running on ParrotSec OS 4.9 amd64 (Debian based)

**Comment by ignertic** [comment]
try running it with python3.7
