### ISSUE TITLE
I cant compiler

### ISSUE THREAD

**Issue by Danmo1311** [gunthercox/ChatterBot#1982]
bro, I am trying to compile the example that appears in the documentation but it does not let me get this error in all the projects that I do with chatterbot
from ChatterBot import ChatBot ModuleNotFoundError: No module named 'ChatterBot'

**Comment by c-chaitanya** [comment]
Hi,
Firstly have you installed chatterbot using `pip install chatterbot` or `pip3 install chatterbot`? Make sure you're using the same pip version to install chatterbot as of your python version.
eg: In my case `pip3.6 install chatterbot` for `python3.6`.

If your installation was successful but still facing issues post additional content to reproduce the error. Include your python version and chatterbot version also.

To know the current version chatterbot use command `python -m chatterbot --version` or `python3 -m chatterbot --version`

If unable to get chatterbot version, try to install using `pip install -U chatterbot` or `pip3 install -U chatterbot`

**Comment by Danmo1311** [comment]
version python 3.8
C:\Users\josem> python -m chatterbot --version
1.0.4

C:\Users\josem>python C:\Users\josem\Documents\bot\examplebot.py
Traceback (most recent call last):
  File "C:\Users\josem\Documents\bot\examplebot.py", line 4, in <module>
    chatbot = ChatBot('Ron Obvious')
  File "C:\python\lib\site-packages\chatterbot\chatterbot.py", line 34, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\python\lib\site-packages\chatterbot\utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)
  File "C:\python\lib\site-packages\chatterbot\storage\sql_storage.py", line 22, in __init__
    from sqlalchemy import create_engine
  File "C:\python\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "C:\python\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "C:\python\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "C:\python\lib\site-packages\sqlalchemy\util\compat.py", line 264, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

![Captura](https://user-images.githubusercontent.com/33797741/82720924-ad444900-9c7d-11ea-9e22-601b23af7938.JPG)

**Comment by c-chaitanya** [comment]
The error seems to be in clock method in time module. Seems like the module is depreciated in python3.8. For a quick fix, to get your work done, use python3.7 or 3.6
