### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: 'chatterbot.ext.django_chatterbot' must supply a name attribute.

### ISSUE THREAD

**Issue by YuzhouZhang** [gunthercox/ChatterBot#1983]
After I integrate with Django, I got this exception when I execute "python manager.py runserver":

> Traceback (most recent call last):
>   File "C:\Users\mamajingjie\AppData\Local\Programs\Python\Python36\lib\site-packages\django\apps\config.py", line 149, in create
>     app_name = cls.name
> AttributeError: type object 'AppConfig' has no attribute 'name'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "manage.py", line 21, in <module>
>     main()
>   File "manage.py", line 17, in main
>     execute_from_command_line(sys.argv)
>   File "C:\Users\mamajingjie\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
>     utility.execute()
>   File "C:\Users\mamajingjie\AppData\Local\Programs\Python\Python36\lib\site-packages\django\core\management\__init__.py", line 357, in execute
>     django.setup()
>   File "C:\Users\mamajingjie\AppData\Local\Programs\Python\Python36\lib\site-packages\django\__init__.py", line 24, in setup
>     apps.populate(settings.INSTALLED_APPS)
>   File "C:\Users\mamajingjie\AppData\Local\Programs\Python\Python36\lib\site-packages\django\apps\registry.py", line 91, in populate
>     app_config = AppConfig.create(entry)
>   File "C:\Users\mamajingjie\AppData\Local\Programs\Python\Python36\lib\site-packages\django\apps\config.py", line 152, in create
>     "'%s' must supply a name attribute." % entry)
> django.core.exceptions.ImproperlyConfigured: 'chatterbot.ext.django_chatterbot' must supply a name attribute.

**Comment by SystemDZ** [comment]
You confused class name with it's attribute

in your **settings.py** then **INSTALLED_APPS**
change **AppConfig** to **ApiConfig**

**Comment by toffeeandlisa** [comment]
I don't know if answering this after one year is against the rules of github, but you are an anonimous hero. Thanks.
