### ISSUE TITLE
TypeError: object of type 'bool' has no len()

### ISSUE THREAD

**Issue by EternalDusk** [gunthercox/ChatterBot#2004]
Training myown.yml: [##                  ] 12% Traceback (most recent call last):
  File "robotchatbotthing.py", line 10, in <module>
    trainer.train("chatterbot.corpus.custom.myown")
  File "C:\Users\stamp\Desktop\Neural Network Studies\chattingbot\chatterbot\trainers.py", line 154, in train
    statement_search_text = self.chatbot.storage.tagger.get_text_index_string(text)
  File "C:\Users\stamp\Desktop\Neural Network Studies\chattingbot\chatterbot\tagging.py", line 34, in get_text_index_string
    if len(text) <= 2:
TypeError: object of type 'bool' has no len()

Training on 12,505 lines of data, wondering why it gets this message ONLY at 12%
I looked at the lines and 12% is lines 1,500 to 1,625 of the myai.yml file

**Comment by EternalDusk** [comment]
Turns out just having the response 'No' breaks the training system xD
