### ISSUE TITLE
Error in training Custom YML file : UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1243: invalid start byte

### ISSUE THREAD

**Issue by abhiramkadali** [gunthercox/ChatterBot#2007]
Hi,

I'm struggling to train my chatbot on a custom YML file . My code is mentioned below for your perusal. 
Any help is appreciated.

import csv
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

import logging
logging.basicConfig(level=logging.INFO)

successCount = 0

with open("data/trainingData.yml", 'w') as f:
    f.write("categories:\r\n")
    f.write("- Conversations")
    f.write("\r\nconversations:")
    with open("data/trp_faq_dataset.csv") as g:
        lines = csv.reader(g)
        for line in lines:
            if line[0] and line[1]:
                successCount += 1
                f.write("\r\n--"+line[0])
                f.write("\r\n -"+line[1])
                
"""
#Clear the previous conversations
if os.path.exists("botData.sqlite3"):
    os.remove("botData.sqlite3")
    print("Clearing the previous conversations")
"""
trp_bot = ChatBot("Talent_Referral_Program",
                  preprocessors = ['chatterbot.preprocessors.clean_whitespace'],
                  storage_adapter="chatterbot.storage.SQLStorageAdapter",
                  database="botData.sqlite3",
                  logic_adapters = [{
                                     "import_path": "chatterbot.logic.BestMatch",
                                     "default_response" : "I'm not sure about your inquiry, please contact US TRP team via outlook @ustalentreferralprogram@deloitte.com"
                                     }])

#trp_bot.set_trainer(ChatterBotCorpusTrainer)
#trp_bot.train("data/trainingData.yml")

trainer = ChatterBotCorpusTrainer(trp_bot)
trainer.train("data/trainingData.yml")

    
print("\n \n Hello user, how may I help you.......... \n \n")
print("Please enter your query here \n \n")

when I run the above code, I'm getting an error as below
trainer = ChatterBotCorpusTrainer(trp_bot)
trainer.train("data/trainingData.yml")
Traceback (most recent call last):

  File "<ipython-input-22-466ff0ff486a>", line 2, in <module>
    trainer.train("data/trainingData.yml")

  File "C:\Users\akadali\Anaconda\lib\site-packages\chatterbot\trainers.py", line 143, in train
    corpora = self.corpus.load_corpus(corpus_path)

  File "C:\Users\akadali\Anaconda\lib\site-packages\chatterbot_corpus\corpus.py", line 93, in load_corpus
    corpus_data = self.read_corpus(file_path)

  File "C:\Users\akadali\Anaconda\lib\site-packages\chatterbot_corpus\corpus.py", line 62, in read_corpus
    data = yaml.load(data_file)

  File "C:\Users\akadali\Anaconda\lib\site-packages\yaml\__init__.py", line 70, in load
    loader = Loader(stream)

  File "C:\Users\akadali\Anaconda\lib\site-packages\yaml\loader.py", line 34, in __init__
    Reader.__init__(self, stream)

  File "C:\Users\akadali\Anaconda\lib\site-packages\yaml\reader.py", line 85, in __init__
    self.determine_encoding()

  File "C:\Users\akadali\Anaconda\lib\site-packages\yaml\reader.py", line 124, in determine_encoding
    self.update_raw()

  File "C:\Users\akadali\Anaconda\lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)

  File "C:\Users\akadali\Anaconda\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)

UnicodeDecodeError: 'utf-8' codec can't decode byte 0x92 in position 1243: invalid start byte

Any help is very much appreciated.

**Comment by AtomynosAtom** [comment]
It is probably because that byte is not utf-8. It is the fancy quote `’` that causes that issue. [This guy explains it well.](https://stackoverflow.com/questions/46000191/utf-8-codec-cant-decode-byte-0x92-in-position-18-invalid-start-byte) He says to Decode it as `Windows codepage 1252` instead, where 0x92 is a fancy quote, `’`.
