### ISSUE TITLE
error in chatbot code

### ISSUE THREAD

**Issue by Aniket573** [gunthercox/ChatterBot#2019]
getting error while running code in pydev in eclipse
I have python 3.8.2 installed.
Traceback (most recent call last):
  File "D:\Users\ABiswa14\eclipse-workspace\PyDev\src\chatbot.py", line 6, in <module>
    bot = ChatBot('Terminal',storage_adapter='chatterbot.storage.SQLStorageAdapter',
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\chatterbot.py", line 34, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\storage\sql_storage.py", line 22, in __init__
    from sqlalchemy import create_engine
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "D:\Users\ABiswa14\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 264, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'

code:
from chatterbot import ChatBot
# Uncomment the following lines to enable verbose logging
# import logging
# logging.basicConfig(level=logging.INFO)
# Create a new instance of a ChatBot
bot = ChatBot('Terminal',storage_adapter='chatterbot.storage.SQLStorageAdapter',
logic_adapters=[
'chatterbot.logic.MathematicalEvaluation',
'chatterbot.logic.TimeLogicAdapter',
'chatterbot.logic.BestMatch'
],
database_uri='sqlite:///database.db'
)
print('Type something to begin...')
# The following loop will execute each time the user enters input
while True:
    try:
        user_input = input()
        bot_response = bot.get_response(user_input)
        print(bot_response)
# Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break

**Comment by gunthercox** [comment]
The error is correct:
```
AttributeError: module 'time' has no attribute 'clock'
```

In Python 3.8 the `time` module does not have a `clock` attribute. This is because ChatterBot doesn't support Python 3.8 yet.

**Comment by Aniket573** [comment]
Can you tell Which version it supports?

**Comment by gunthercox** [comment]
3.7 is the latest version ChatterBot currently supports, but anything down to 3.4 should work.

**Comment by gunthercox** [comment]
I've released version 1.0.7 which adds support for Python 3.8.
