### ISSUE TITLE
OSError: can't find model "en"

### ISSUE THREAD

**Issue by Mineinjava** [gunthercox/ChatterBot#2022]
Im trying to make a simple discord chatbot, and I keep getting the error: `OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.`
I have installed chatterBot using `pypy` and am using python 3.7.3, using a Mac

<details>
  <summary>Traceback (show)</summary>
  

```py
Traceback (most recent call last):
  File "/Users/mineinjava/Documents/ChatterBot AI/bot.py", line 7, in <module>
    cBot = ChatBot('AI')
  File "/Library/Python/3.7/site-packages/chatterbot/chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "/Library/Python/3.7/site-packages/chatterbot/utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "/Library/Python/3.7/site-packages/chatterbot/storage/sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "/Library/Python/3.7/site-packages/chatterbot/storage/storage_adapter.py", line 23, in __init__
    'tagger_language', languages.ENG
  File "/Library/Python/3.7/site-packages/chatterbot/tagging.py", line 26, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "/Library/Python/3.7/site-packages/spacy/__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "/Library/Python/3.7/site-packages/spacy/util.py", line 139, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

</details>

**Comment by gunthercox** [comment]
Spacy provides functionality where you can link a model to an alias, such as `en_core_web_sm` to `en`.

Here are a few examples to get you started:
```
python -m spacy link en_core_web_sm en
```

```
python -m spacy link de_core_news_sm de
```
