### ISSUE TITLE
bad escape \p at position 257

### ISSUE THREAD

**Issue by ZZY2357** [gunthercox/ChatterBot#2030]
My code:
```python
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatbot = ChatBot("Ron Obvious")

conversation = [
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
]

trainer = ListTrainer(chatbot)

trainer.train(conversation)

while True:
	response = chatbot.get_response(input(': '))
	print(response)

```
error:
```
❯ python .\__main__.py
C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\util.py:275: UserWarning: [W031] Model 'en_core_web_sm' (2.0.0) requires spaCy v2.0 and is incompatible with the current spaCy version (2.3.2). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate
  warnings.warn(warn_msg)
Traceback (most recent call last):
  File ".\__main__.py", line 4, in <module>
    chatbot = ChatBot("Ron Obvious")
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot\storage\storage_adapter.py", line 20, in __init__
    self.tagger = PosLemmaTagger(language=kwargs.get(
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\chatterbot\tagging.py", line 13, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\util.py", line 168, in load_model
    return load_model_from_link(name, **overrides)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\util.py", line 185, in load_model_from_link
    return cls.load(**overrides)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\data\en\__init__.py", line 12, in load
    return load_model_from_init_py(__file__, **overrides)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\util.py", line 239, in load_model_from_init_py
    return load_model_from_path(data_path, meta, **overrides)
from_path
    return nlp.from_disk(model_path, exclude=disable)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\language.py", line 974, in from_disk
    util.from_disk(path, deserializers, exclude)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\util.py", line 690, in from_disk
    reader(path / key)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\site-packages\spacy\language.py", line 960, in <lambda>
    deserializers["tokenizer"] = lambda p: self.tokenizer.from_disk(
  File "tokenizer.pyx", line 558, in spacy.tokenizer.Tokenizer.from_disk
  File "tokenizer.pyx", line 606, in spacy.tokenizer.Tokenizer.from_bytes
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\re.py", line 250, in compile
    return _compile(pattern, flags)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\re.py", line 302, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\sre_parse.py", line 554, in _parse
    code1 = _class_escape(source, this)
  File "C:\Users\ZZY23\AppData\Local\Programs\Python\Python38\lib\sre_parse.py", line 349, in _class_escape
    raise source.error('bad escape %s' % escape, len(escape))
re.error: bad escape \p at position 257
```

**Comment by LEE-JYOUNG** [comment]
See the error log:
` serWarning: [W031] Model 'en_core_web_sm' (2.0.0) requires spaCy v2.0 and is incompatible with the current spaCy version (2.3.2). This may lead to unexpected results or runtime errors. To resolve this, download a newer compatible model or retrain your custom model with the current spaCy version. For more details and available updates, run: python -m spacy validate`

It means the model version is incompatible with your spaCy version, it can be solved with this:
`python -m spacy download en_core_web_sm'

**Comment by ZZY2357** [comment]
Thank you, it works. 😄
