### ISSUE TITLE
Issue with time.clock 

### ISSUE THREAD

**Issue by ayushmodi-038** [gunthercox/ChatterBot#2046]
Got an exception -

chatbot = ChatBot('Ron Obvious')
Traceback (most recent call last):

  File "<ipython-input-6-a1741da6c5bd>", line 1, in <module>
    chatbot = ChatBot('Ron Obvious')

  File "C:\Anaconda\lib\site-packages\chatterbot\chatterbot.py", line 34, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)

  File "C:\Anaconda\lib\site-packages\chatterbot\utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)

  File "C:\Anaconda\lib\site-packages\chatterbot\storage\sql_storage.py", line 22, in __init__
    from sqlalchemy import create_engine

  File "C:\Anaconda\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa

  File "C:\Anaconda\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa

  File "C:\Anaconda\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types

  File "C:\Anaconda\lib\site-packages\sqlalchemy\util\compat.py", line 264, in <module>
    time_func = time.clock

AttributeError: module 'time' has no attribute 'clock'

I have changed the code to this for temporary fix. because here win32==True but time.clock is not identified
if win32 or jython:
    try:
        time_func = time.clock
    except:
        time_func = time.time
else:
    time_func = time.time

**Comment by Tlevi16** [comment]
same here

**Comment by daniyalas** [comment]
same here
