### ISSUE TITLE
Issue using this library 

### ISSUE THREAD

**Issue by Tlevi16** [gunthercox/ChatterBot#2058]
I literally copy-pasted the code from this library's README.md file, but still, I get this exception. why is this happening! what wrong did I do ???????

`Traceback (most recent call last):
  File "main.py", line 32, in <module>
    main() 
  File "main.py", line 9, in main
    AI = ChatBot(
  File "C:\Users\lloye\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\chatterbot.py", line 34, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\lloye\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\utils.py", line 54, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\lloye\AppData\Local\Programs\Python\Python38-32\lib\site-packages\chatterbot\storage\sql_storage.py", line 22, in __init__
    from sqlalchemy import create_engine
  File "C:\Users\lloye\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\__init__.py", line 8, in <module>
    from . import util as _util  # noqa
  File "C:\Users\lloye\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\__init__.py", line 14, in <module>
    from ._collections import coerce_generator_arg  # noqa
  File "C:\Users\lloye\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\_collections.py", line 16, in <module>
    from .compat import binary_types
  File "C:\Users\lloye\AppData\Local\Programs\Python\Python38-32\lib\site-packages\sqlalchemy\util\compat.py", line 264, in <module>
    time_func = time.clock
AttributeError: module 'time' has no attribute 'clock'`

an answer would be appreciated 

And I am using python 3.8

**Comment by bobloy** [comment]
You need to update your `sqlalchemy` package.
`pip install "sqlalchemy>=1.3,<1.4"`
