### ISSUE TITLE
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

### ISSUE THREAD

**Issue by ratnasankeerthanreddy** [gunthercox/ChatterBot#2059]
``` from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('Ron Obvious')

# Create a new trainer for the chatbot
trainer = ChatterBotCorpusTrainer(chatbot)

# Train the chatbot based on the english corpus
trainer.train("chatterbot.corpus.english")

# Get a response to an input statement
chatbot.get_response("Hello, how are you today?")```




output as 


---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-1-f8d70b5b4e6a> in <module>
      2 from chatterbot.trainers import ChatterBotCorpusTrainer
      3 
----> 4 chatbot = ChatBot('Ron Obvious')
      5 
      6 # Create a new trainer for the chatbot

~\Anaconda3\lib\site-packages\chatterbot\chatterbot.py in __init__(self, name, **kwargs)
     26         self.logic_adapters = []
     27 
---> 28         self.storage = utils.initialize_class(storage_adapter, **kwargs)
     29 
     30         primary_search_algorithm = IndexedTextSearch(self, **kwargs)

~\Anaconda3\lib\site-packages\chatterbot\utils.py in initialize_class(data, *args, **kwargs)
     31         Class = import_module(data)
     32 
---> 33         return Class(*args, **kwargs)
     34 
     35 

~\Anaconda3\lib\site-packages\chatterbot\storage\sql_storage.py in __init__(self, **kwargs)
     18 
     19     def __init__(self, **kwargs):
---> 20         super().__init__(**kwargs)
     21 
     22         from sqlalchemy import create_engine

~\Anaconda3\lib\site-packages\chatterbot\storage\storage_adapter.py in __init__(self, *args, **kwargs)
     19 
     20         self.tagger = PosLemmaTagger(language=kwargs.get(
---> 21             'tagger_language', languages.ENG
     22         ))
     23 

~\Anaconda3\lib\site-packages\chatterbot\tagging.py in __init__(self, language)
     11         self.punctuation_table = str.maketrans(dict.fromkeys(string.punctuation))
     12 
---> 13         self.nlp = spacy.load(self.language.ISO_639_1.lower())
     14 
     15     def get_bigram_pair_string(self, text):

~\Anaconda3\lib\site-packages\spacy\__init__.py in load(name, **overrides)
     28     if depr_path not in (True, False, None):
     29         deprecation_warning(Warnings.W001.format(path=depr_path))
---> 30     return util.load_model(name, **overrides)
     31 
     32 

~\Anaconda3\lib\site-packages\spacy\util.py in load_model(name, **overrides)
    167     elif hasattr(name, "exists"):  # Path or Path-like to model data
    168         return load_model_from_path(name, **overrides)
--> 169     raise IOError(Errors.E050.format(name=name))
    170 
    171 

OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by Bertik23** [comment]
Same problem
```
Traceback (most recent call last):
  File "d:\Python\TheBot\chatbot.py", line 4, in <module>
    chatbot = ChatBot('TheBot')
  File "C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\chatterbot\storage\storage_adapter.py", line 21, in __init__
    'tagger_language', languages.ENG
  File "C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\chatterbot\tagging.py", line 13, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\alber\AppData\Roaming\Python\Python37\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```
With Python 3.7.6

**Comment by Bertik23** [comment]
Oh never mind #2039 solved it

**Comment by ratnasankeerthanreddy** [comment]
using the command "python -m spacy download en" still facing the same error

**Comment by ratnasankeerthanreddy** [comment]
when the same code is run in colab it is working fine ..
but when it runs in pc we are facing this issue..
i think there is a bug in the module

**Comment by AnAnalogGuy** [comment]
No, no bug in the module. When you read the above mentioned ticket, you will find you have to either create a symlink to the "en" library or you have to copy it to the right directory. It's just not finding the file where it expects it to be. 
Btw, this has nothing to do with ChatterBox at all, as the model belongs to spacy.

**Comment by ratnasankeerthanreddy** [comment]
thanks for the clarification @AnAnalogGuy

**Comment by ChristianTremblay** [comment]
Added a comment on issue #2066 related to this.

**Comment by sanjayanbu** [comment]
use anaconda navigator create new virtual environment name it tensorflow_development
install nltk, tensorflow, sklearn, numpy==1.19.3, chatterbot , chatterbot_corpus 

for certain libraries use pip install to install chatterbot==0.8.7, chatterbot_corpus==1.1.4

launch the newly created env and use it for all machine learning development it will definitely work bec conda takes care of all the dependency issuses

**Comment by adityaasthana1** [comment]
Solved this problem.
Open PowerShell with Admin Access and run
`
python -m spacy link en_core_web_sm en
`

This should work.

**Comment by UBISOFT-1** [comment]
@adityaasthana1 Confirm this works but gives me this SQL Error
Can you help me with that.
OS:Windows 10 Version	10.0.19042 Build 19042
Python Version: 3.6
```
Traceback (most recent call last):
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\impl.py", line 241, in _do_get
    return self._create_connection()
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 668, in __connect
    pool.dispatch.connect(self.connection, self)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\event\attr.py", line 261, in __call__
    fn(*args, **kw)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 43, in set_sqlite_pragma
    dbapi_connection.execute('PRAGMA journal_mode=WAL')
sqlite3.OperationalError: cannot change into wal mode from within a transaction

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/Namaz/PycharmProjects/RAT/CHAT-BOT.py", line 7, in <module>
    database_uri='sqlite:///database.sqlite3'
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 46, in __init__
    if not self.engine.dialect.has_table(self.engine, 'Statement'):
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 1666, in has_table
    connection, "table_info", table_name, schema=schema
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\dialects\sqlite\base.py", line 2180, in _get_table_pragma
    cursor = connection.execute(statement)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2234, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2302, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2340, in _wrap_pool_connect
    e, dialect, self
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1584, in _handle_dbapi_exception_noconnection
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 182, in raise_
    raise exception
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 2336, in _wrap_pool_connect
    return fn()
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 364, in connect
    return _ConnectionFairy._checkout(self)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 778, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 495, in checkout
    rec = pool._do_get()
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\impl.py", line 241, in _do_get
    return self._create_connection()
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 309, in _create_connection
    return _ConnectionRecord(self)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 440, in __init__
    self.__connect(first_connect_check=True)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\pool\base.py", line 668, in __connect
    pool.dispatch.connect(self.connection, self)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\sqlalchemy\event\attr.py", line 261, in __call__
    fn(*args, **kw)
  File "C:\Users\Namaz\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 43, in set_sqlite_pragma
    dbapi_connection.execute('PRAGMA journal_mode=WAL')
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) cannot change into wal mode from within a transaction
(Background on this error at: http://sqlalche.me/e/13/e3q8)

Process finished with exit code 1
```

**Comment by AnAnalogGuy** [comment]
@UBISOFT-1  Could help to see the code snipplet to see what you're actually doing.

**Comment by AnAnalogGuy** [comment]
From: https://docs.sqlalchemy.org/en/13/errors.html#error-e3q8

OperationalError

> Exception raised for errors that are related to the database’s operation and not necessarily under the control of the programmer, e.g. an unexpected disconnect occurs, the data source name is not found, a transaction could not be processed, a memory allocation error occurred during processing, etc.
> 
> This error is a DBAPI Error and originates from the database driver (DBAPI), not SQLAlchemy itself.
> 
> The OperationalError is the most common (but not the only) error class used by drivers in the context of the database connection being dropped, or not being able to connect to the database. For tips on how to deal with this, see the section Dealing with Disconnects.

**Comment by peileppe** [comment]
First

$ python -m spacy info
to verify that indeed the model 'en' was missing

Then this is what fixed it for me

$ python -m spacy download en

Python version 3.6.9

More elaborate answer posted at https://github.com/codeperfectplus/Python-ChatBot/issues/2
