### ISSUE TITLE
AttributeError: type object 'ChatBot' has no attribute 'storage'

### ISSUE THREAD

**Issue by ilikeapple12** [gunthercox/ChatterBot#2062]
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
import nltk
import os
import discord
from discord.ext import commands
import asyncio
import random

client = commands.Bot(command_prefix = '-')
client.remove_command('help')
client.variable = None

@client.event
async def on_ready():
    await client.change_presence(status = discord.Status.online)
    print('Bot is ready.')

bot = ChatBot(
    'Norman',
    storage_adapter='chatterbot.storage.SQLStorageAdapter',
    logic_adapters=[
        'chatterbot.logic.MathematicalEvaluation',
        'chatterbot.logic.TimeLogicAdapter'
    ],
    database_uri='sqlite:///database.sqlite3'
)
trainer = ListTrainer(ChatBot)

trainer.train([
    "Hello",
    "Hi there!",
    "How are you doing?",
    "I'm doing great.",
    "That is good to hear",
    "Thank you.",
    "You're welcome."
])

i'm getting the error "AttributeError: type object 'ChatBot' has no attribute 'storage'"
please help ;-;

**Comment by pradeepmaurya** [comment]
In my case Error is showing as when installing chatterbot in python


**_ERROR: Command errored out with exit status 1:                                                                           command: 'c:\program files (x86)\python38-32\python.exe' 'c:\program files (x86)\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-build-env-n2kijn1z\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0'              cwd: None                                                                                                          Complete output (61 lines):                                                                                             Collecting setuptools                                                                                                     Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)                                                              Collecting wheel<0.33.0,>0.32.0                                                                                           Using cached wheel-0.32.3-py2.py3-none-any.whl (21 kB)                                                                Collecting Cython                                                                                                         Using cached Cython-0.29.21-cp38-cp38-win32.whl (1.6 MB)                                                              Collecting cymem<2.1.0,>=2.0.2                                                                                            Using cached cymem-2.0.3.tar.gz (51 kB)                                                                               Collecting preshed<2.1.0,>=2.0.1                                                                                          Using cached preshed-2.0.1.tar.gz (113 kB)                                                                            Collecting murmurhash<1.1.0,>=0.28.0                                                                                      Using cached murmurhash-1.0.2.tar.gz (35 kB)                                                                          Collecting thinc<7.1.0,>=7.0.8                                                                                            Using cached thinc-7.0.8.tar.gz (1.9 MB)                                                                              Collecting blis<0.3.0,>=0.2.1                                                                                             Using cached blis-0.2.4.tar.gz (1.5 MB)                                                                               Collecting wasabi<1.1.0,>=0.0.9                                                                                           Using cached wasabi-0.8.0-py3-none-any.whl (23 kB)                                                                    Collecting srsly<1.1.0,>=0.0.6                                                                                            Using cached srsly-1.0.2.tar.gz (192 kB)                                                                              Collecting numpy>=1.7.0                                                                                                   Using cached numpy-1.19.2-cp38-cp38-win32.whl (10.9 MB)                                                               Collecting plac<1.0.0,>=0.9.6                                                                                             Using cached plac-0.9.6-py2.py3-none-any.whl (20 kB)                                                                  Collecting tqdm<5.0.0,>=4.10.0                                                                                            Using cached tqdm-4.50.2-py2.py3-none-any.whl (70 kB)                                                                 Using legacy setup.py install for cymem, since package 'wheel' is not installed.                                        Using legacy setup.py install for preshed, since package 'wheel' is not installed.                                      Using legacy setup.py install for murmurhash, since package 'wheel' is not installed.                                   Using legacy setup.py install for thinc, since package 'wheel' is not installed.                                        Using legacy setup.py install for blis, since package 'wheel' is not installed.                                         Using legacy setup.py install for srsly, since package 'wheel' is not installed.                                        Installing collected packages: setuptools, wheel, Cython, cymem, preshed, murmurhash, numpy, blis, wasabi, srsly, plac, tqdm, thinc                                                                                                                 Running setup.py install for cymem: started                                                                             Running setup.py install for cymem: finished with status 'error'                                                        ERROR: Command errored out with exit status 1:                                                                           command: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pradeep maurya\\AppData\\Local\\Temp\\pip-install-6u5r4xhq\\cymem\\setup.py'"'"'; __file__='"'"'C:\\Users\\pradeep maurya\\AppData\\Local\\Temp\\pip-install-6u5r4xhq\\cymem\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-record-52z9kcdy\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-build-env-n2kijn1z\overlay' --compile --install-headers 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-build-env-n2kijn1z\overlay\Include\cymem'                            cwd: C:\Users\pradeep maurya\AppData\Local\Temp\pip-install-6u5r4xhq\cymem\                                        Complete output (18 lines):                                                                                             WARNING: The wheel package is not available.                                                                            running install                                                                                                         running build                                                                                                           running build_py                                                                                                        creating build                                                                                                          creating build\lib.win32-3.8                                                                                            creating build\lib.win32-3.8\cymem                                                                                      copying cymem\about.py -> build\lib.win32-3.8\cymem                                                                     copying cymem\__init__.py -> build\lib.win32-3.8\cymem                                                                  package init file 'cymem\tests\__init__.py' not found (or not a regular file)                                           creating build\lib.win32-3.8\cymem\tests                                                                                copying cymem\tests\test_import.py -> build\lib.win32-3.8\cymem\tests                                                   copying cymem\cymem.pyx -> build\lib.win32-3.8\cymem                                                                    copying cymem\cymem.pxd -> build\lib.win32-3.8\cymem                                                                    copying cymem\__init__.pxd -> build\lib.win32-3.8\cymem                                                                 running build_ext                                                                                                       building 'cymem.cymem' extension                                                                                        error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/                                                                                                        ----------------------------------------                                                                            ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python38-32\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\pradeep maurya\\AppData\\Local\\Temp\\pip-install-6u5r4xhq\\cymem\\setup.py'"'"'; __file__='"'"'C:\\Users\\pradeep maurya\\AppData\\Local\\Temp\\pip-install-6u5r4xhq\\cymem\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-record-52z9kcdy\install-record.txt' --single-version-externally-managed --prefix 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-build-env-n2kijn1z\overlay' --compile --install-headers 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-build-env-n2kijn1z\overlay\Include\cymem' Check the logs for full command output.                                                                  WARNING: You are using pip version 20.1.1; however, version 20.2.4 is available.                                        You should consider upgrading via the 'c:\program files (x86)\python38-32\python.exe -m pip install --upgrade pip' command.                                                                                                                     ----------------------------------------                                                                              ERROR: Command errored out with exit status 1: 'c:\program files (x86)\python38-32\python.exe' 'c:\program files (x86)\python38-32\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\pradeep maurya\AppData\Local\Temp\pip-build-env-n2kijn1z\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools 'wheel>0.32.0,<0.33.0' Cython 'cymem>=2.0.2,<2.1.0' 'preshed>=2.0.1,<2.1.0' 'murmurhash>=0.28.0,<1.1.0' 'thinc>=7.0.8,<7.1.0' Check the logs for full command output._**

**Comment by bobloy** [comment]
> In my case Error is showing as when installing chatterbot in python
That is a completely different issue pradeepmaurya. Install the microsoft build tools like the error say to do. Then make your own issue if you're still having problems.

**Comment by tc-poland** [comment]
that is my error
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/socketserver.py", line 320, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 351, in process_request
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.6/socketserver.py", line 364, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.6/socketserver.py", line 724, in __init__
    self.handle()
  File "/usr/local/lib/python3.6/http/server.py", line 418, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.6/http/server.py", line 406, in handle_one_request
    method()
  File "/var/www/totalcoding.pl/bot/lhcHandler.py", line 106, in do_GET
    answer = self.bot.getAnswer(''.join(query_components["id"]),''.join(query_components["q"]),''.join(query_components["ct"]))
  File "/var/www/totalcoding.pl/bot/lhcChatBot.py", line 90, in getAnswer
    bot = self.getBot(instanceId, context)
  File "/var/www/totalcoding.pl/bot/lhcChatBot.py", line 85, in getBot
    database_uri=self.settings['DB_URL']+self.settings['DATABASE_PREFIX'] + "-" + instanceId+"-"+context
  File "/var/www/totalcoding.pl/bot/lhc_chatbot.py", line 16, in __init__
    primary_search_algorithm = IndexedTextSearch(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/chatterbot/search.py", line 24, in __init__
    language=self.chatbot.storage.tagger.language
AttributeError: 'ChatBot' object has no attribute 'storage'`

**Comment by AnAnalogGuy** [comment]
If i correctly remember, the API of the/some StorageAdapters have changed, with the newest version. Please check the API documentation for the version of ChatterBox you are using.

**Comment by gunthercox** [comment]
Can confirm. `self.storage` is now a valid attribute on the `ChatBot` class.
