### ISSUE TITLE
Not Working: Can't find model 'en'.

### ISSUE THREAD

**Issue by Pro100rus32** [gunthercox/ChatterBot#2066]
Code:

```
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('Ron Obvious')

# Create a new trainer for the chatbot
trainer = ChatterBotCorpusTrainer(chatbot)

# Train the chatbot based on the english corpus
trainer.train("chatterbot.corpus.english")

# Get a response to an input statement
chatbot.get_response("Hello, how are you today?")
```

Output:
```
Traceback (most recent call last):
  File "E:\ChatBotAI\AiCharli.py", line 4, in <module>
    chatbot = ChatBot('Ron Obvious')
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 21, in __init__
    'tagger_language', languages.ENG
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\tagging.py", line 13, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 30, in load
    return util.load_model(name, **overrides)
  File "C:\Users\andre\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\util.py", line 175, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
```

**Comment by msghera** [comment]
This is not a **Chatterbot** error, rather belongs to **Spacy**. You can find the import of space [here](https://github.com/gunthercox/ChatterBot/blob/d911b4ac46e122308a759ea6ec67b666136e3026/chatterbot/comparisons.py#L121). 

You may find you expected solution [here](https://github.com/explosion/spaCy/issues/4577).

**Comment by ChristianTremblay** [comment]
Had this issue and fixed it by forcing **en_core_web_sm** when loading space.load()

Would be nice to have some kind of control over this with a try except block maybe.... try **en** and if it fails... use complete library name. 

Could also be an argument passed to Chatbot ?

**Comment by mkkeffeler** [comment]
```
python3 -m spacy download en
```
fixed this for me
