### ISSUE TITLE
ModuleNotFoundError: No module named 'chatterbot_corpus'

### ISSUE THREAD

**Issue by Simon8282005** [gunthercox/ChatterBot#2070]
I install the ChatterBot and write a simple program follow the tutorial, but when I run it, it show the error below:
```
Traceback (most recent call last):
  File "/home/simon/Documents/Files/Coding/Coding Files/Python/Daily/Day 65/Chatter Bot.py", line 1, in <module>
    from chatterbot import ChatBot
  File "/home/simon/.local/lib/python3.8/site-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/home/simon/.local/lib/python3.8/site-packages/chatterbot/chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "/home/simon/.local/lib/python3.8/site-packages/chatterbot/storage/__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "/home/simon/.local/lib/python3.8/site-packages/chatterbot/storage/storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosHypernymTagger
  File "/home/simon/.local/lib/python3.8/site-packages/chatterbot/tagging.py", line 4, in <module>
    from chatterbot.tokenizers import get_sentence_tokenizer
  File "/home/simon/.local/lib/python3.8/site-packages/chatterbot/tokenizers.py", line 4, in <module>
    from chatterbot.corpus import load_corpus, list_corpus_files
  File "/home/simon/.local/lib/python3.8/site-packages/chatterbot/corpus.py", line 5, in <module>
    from chatterbot_corpus.corpus import DATA_DIRECTORY
ModuleNotFoundError: No module named 'chatterbot_corpus'
```
I'm no idea why it shows this error because ChatterBot is installed successfully.

**Comment by solartune** [comment]
What version have you installed?
It seems it has been dealt with in the latest stable version (1.0.8)
https://github.com/gunthercox/ChatterBot/blob/1.0.8/chatterbot/corpus.py#L8

**Comment by beucismis** [comment]
What is the solution?
