### ISSUE TITLE
Traceback (most recent call last):  ModuleNotFoundError: No module named 'spacy'

### ISSUE THREAD

**Issue by PedroPlayH** [gunthercox/ChatterBot#2071]
Traceback (most recent call last):
  File "C:/Users/Pedro/PycharmProjects/Tests3.6.8/ChatterBot.py", line 1, in <module>
    from chatterbot import ChatBot
  File "C:\Users\Pedro\PycharmProjects\Tests3.6.8\venv\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "C:\Users\Pedro\PycharmProjects\Tests3.6.8\venv\lib\site-packages\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
  File "C:\Users\Pedro\PycharmProjects\Tests3.6.8\venv\lib\site-packages\chatterbot\storage\__init__.py", line 1, in <module>
    from chatterbot.storage.storage_adapter import StorageAdapter
  File "C:\Users\Pedro\PycharmProjects\Tests3.6.8\venv\lib\site-packages\chatterbot\storage\storage_adapter.py", line 3, in <module>
    from chatterbot.tagging import PosLemmaTagger
  File "C:\Users\Pedro\PycharmProjects\Tests3.6.8\venv\lib\site-packages\chatterbot\tagging.py", line 3, in <module>
    import spacy
ModuleNotFoundError: No module named 'spacy'

**Dont know how to fix this, can someone help me?**

**Comment by solartune** [comment]
Spacy is a package https://spacy.io

And it's included in the dev requirements https://github.com/gunthercox/ChatterBot/blob/master/dev-requirements.txt#L9

I'm not sure what are you doing exactly but if you need the package just install it.

**Comment by alessio-lavore** [comment]
I have the same error, but when a try to install manually the package "spacy" I received another error.

**Comment by gunthercox** [comment]
As of the version 1.2.1 release of `chatterbot`, the `spacy` package will be added as a primary dependency of ChatterBot. This should prevent future issues like this from occuring.

But yes, the correct suggested action here to fix the issue would have been to install `spacy` directly via `pip`
