### ISSUE TITLE
sqlite3.OperationalError when starting chatterbot

### ISSUE THREAD

**Issue by nickums** [gunthercox/ChatterBot#2093]
installed chatterbot #==1.0.4 0n my windows10 python3.8, with some dependency problems:
RROR: pip's dependency resolver does not currently take into account all the packages that are installed. 
This behaviour is the source of the following dependency conflicts.
imgaug 0.4.0 requires opencv-python, which is not installed.
tf-models-official 2.3.0 requires google-cloud-bigquery>=0.31.0, which is not installed.
tf-models-official 2.3.0 requires opencv-python-headless, which is not installed.
parlai 0.9.3 requires docutils<0.16, but you have docutils 0.16 which is incompatible.
tf-models-official 2.3.0 requires tensorflow>=2.3.0, but you have tensorflow 2.2.0 which is incompatible.
Successfully installed chatterbot-1.0.4 chatterbot-corpus-1.2.0 pint-0.16.1 python-dateutil-2.7.5
I cannot install bigquery or headless - another problem .
Anyway, it seemed to be going well loading the .yml stuff but then:
.....
Training ai.yml: [####################] 99%
Training ai.yml: [####################] 100%

Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    self.dialect.do_execute(
  File "C:\Python\Python38\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: table statement has no column named search_text

**Comment by nickums** [comment]
sorry, shd have included the code:
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatbot = ChatBot('Ron Obvious')

# Create a new trainer for the chatbot
trainer = ChatterBotCorpusTrainer(chatbot)

# Train the chatbot based on the english corpus
trainer.train("chatterbot.corpus.english")
