### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by haow85** [gunthercox/ChatterBot#2113]
I appended some new Chinese training corpus text to the original ai.yml file in the corpus directory, but got the following error:

`Training ai.yml: [                    ] 0%Traceback (most recent call last):
  File "chat.py", line 6, in <module>
    trainer.train("chatterbot.corpus.chinese")
  File "/usr/local/lib/python3.6/dist-packages/ChatterBot-1.1.0a7-py3.6.egg/chatterbot/trainers.py", line 154, in train
  File "/usr/local/lib/python3.6/dist-packages/ChatterBot-1.1.0a7-py3.6.egg/chatterbot/tagging.py", line 34, in get_text_index_string
TypeError: object of type 'NoneType' has no len()`

Do you know how to fix this problem ?

**Comment by gunthercox** [comment]
This is an old issue so I'm going to close it off. Without seeing a sample of the change that was made to the corpus file it is difficult to know exactly what caused the error here.
