### ISSUE TITLE
StrogeAdapter problems

### ISSUE THREAD

**Issue by ahmet-soner** [gunthercox/ChatterBot#2127]
Traceback (most recent call last):
  File "C:\Users\MYSTIC\Desktop\chatterbot\ChatBot.py", line 1, in <module>
    from chatterbot import ChatBot
  File "C:\Users\MYSTIC\Desktop\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package
**********************************************************************************************************
What is the solution ?

**Comment by intercontoni** [comment]
Tray this...

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer

chatterbot.storage'; 'chatterbot' is not a package....

I uses this...

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer

**Comment by ahmet-soner** [comment]
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer
from chatterbot.trainers import ChatterBotCorpusTrainer
*************************************************************************
Traceback (most recent call last):
  File "ChatBot.py", line 1, in <module>
    from chatterbot import ChatBot
  File
"C:\Users\MYSTIC\AppData\Roaming\Python\Python38\site-packages\chatterbot
\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is
not a
 package

C:\Users\MYSTIC\AppData\Roaming\Python\Python38\site-packages\chatterbot>
***************************************************************************************************
Hi intercontoni

StrogaAdapter got me in trouble
Where did you create the file called ChatBot.py?
I wonder if I created my wrong directory


intercontoni <notifications@github.com>, 21 Şub 2021 Paz, 05:17 tarihinde
şunu yazdı:

**Comment by intercontoni** [comment]
Oh.... I see your problem...

Not is ChaBot.py .... is chabot.py

on the Application root.

It is a physical address to your application on a server that corresponds with its URI. 

Put the chatbot.py here

**Comment by intercontoni** [comment]
Oh.... I see your problem...

Not is ChaBot.py .... is chabot.py

on the Application root.

It is a physical address to your application on a server that corresponds with its URI. 

Put the chatbot.py here

**Comment by intercontoni** [comment]
line 1, in
from chatterbot import ChatBot

This is good...

And you need to put chaterbot.py in C:\Users\MYSTIC\Desktop\chatterbot\chatboy.py 

Remember....  ChatBot.py not work... work chatbot.py 

ChatBot.py is a file in the folder inside ir the site-packages 

Let me know bro...

**Comment by intercontoni** [comment]
line 1, in
from chatterbot import ChatBot

This is good...

And you need to put chaterbot.py in C:\Users\MYSTIC\Desktop\chatterbot\chatboy.py 

Remember....  ChatBot.py not work... work chatbot.py 

ChatBot.py is a file in the folder inside ir fue site-packages 

Le me know bro...

**Comment by intercontoni** [comment]
line 1, in
from chatterbot import ChatBot

This is good...

And you need to put chaterbot.py in C:\Users\MYSTIC\Desktop\chatterbot\chatboy.py 

Remember....  ChatBot.py not work... work chatbot.py 

ChatBot.py is a file in the folder inside ir the site-packages 

Let me know bro...

**Comment by ahmet-soner** [comment]
😭😭😭
Traceback (most recent call last):
  File "C:\Users\MYSTIC\Desktop\chatterbot\chatboy.py", line 1, in <module>
    from chatterbot import ChatBot
  File "C:\Users\MYSTIC\Desktop\chatterbot\chatterbot.py", line 2, in
<module>
    from chatterbot.storage import StorageAdapter
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is
not a package
****************************************************************************************************************
>>> *I feel like the most clumsy person in the world*
>>> *Thank you so much for your time for me, you are good people*


intercontoni <notifications@github.com>, 21 Şub 2021 Paz, 16:47 tarihinde
şunu yazdı:

**Comment by intercontoni** [comment]
I used hosting linux share vps...  
i don't know what do you used...

Do you have installed chatterbot?

Used pip freeze and see the list...

If not have used

 python -m pip install chatterbot

Hummm do you have ...

C:\Users\MYSTIC\Desktop\chatterbot\chatboy.py

chatboy ??

What is a code for chatboy.py ???

Le me see...

 C:\Users\MYSTIC\Desktop\chatterbot\chatterbot.py

What is a code inside the chatterbot.py ???

Le me see...

I used all in one file .py .... the name app.py

This is a code I am have...

````
import os
import sys
from flask import Flask, render_template, request
from sys import version
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.trainers import ListTrainer

sys.path.insert(0, os.path.dirname(__file__))

app = Flask(__name__)

chatbot = ChatBot('Toni', storage_adapter='chatterbot.storage.SQLStorageAdapter',
database_uri='sqlite:///database.sqlite3')

trainer = (ListTrainer)
trainer = ChatterBotCorpusTrainer(chatbot)

trainer.train("chatterbot.corpus.english")

@app.route("/")
def home():    
    return render_template("elultimo.html") 
    
@app.route("/get")
def get_bot_response():    
    userText = request.args.get('msg')    
    return str(bot.get_response(userText)) 
    
if __name__ == "__main__":
     app.run()

````
My chatterbot is the name Toni and the folder root is the name toni

in ssh work... but I have problem in the page... not response https://intercongreso.vps.co.ve/toni

I am invertigate what happen... if you used my app.py and work for you let me know please.. I don't have computer... for used localhost in my computer...

I work whit my Phone :)

Good look...

**Comment by intercontoni** [comment]
I used hosting linux share vps...  
i don't know what do you used...

Do you have installed chatterbot?

Used pip freeze and see the list...

If not have used

 python -m pip install chatterbot

Hummm do you have ...

C:\Users\MYSTIC\Desktop\chatterbot\chatboy.py

chatboy ??

What is a code for chatboy.py ???

Le me see...

 C:\Users\MYSTIC\Desktop\chatterbot\chatterbot.py

What is a code inside the chatterbot.py ???

Le me see...

I used all in one file .py .... the name app.py

This is a code I am have...

````
import os
import sys
from flask import Flask, render_template, request
from sys import version
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
from chatterbot.trainers import ListTrainer

sys.path.insert(0, os.path.dirname(__file__))

app = Flask(__name__)

chatbot = ChatBot('Toni', storage_adapter='chatterbot.storage.SQLStorageAdapter',
database_uri='sqlite:///database.sqlite3')

trainer = (ListTrainer)
trainer = ChatterBotCorpusTrainer(chatbot)

trainer.train("chatterbot.corpus.english")

@app.route("/")
def home():    
    return render_template("elultimo.html") 
    
@app.route("/get")
def get_bot_response():    
    userText = request.args.get('msg')    
    return str(bot.get_response(userText)) 
    
if __name__ == "__main__":
     app.run()

````
My chatterbot is the name Toni and the folder root is the name toni

in ssh work... but I have problem in the page... not response https://intercongreso.vps.co.ve/toni

I am invertigate what happen... if you used my app.py and work for you let me know please.. I don't have computer... for used localhost in my computer...

I work whit my Phone :)

Good look...

**Comment by ahmet-soner** [comment]
Ben laptopla çalışıyorum, eğer sizin için sakıncası yoksa teamviewer ile
benim laptopa bağlanıp kurulum yapabilirmisiniz.
Bu ara Toni güzel gözüküyor
chatterbotu aktif hale getiremedim

intercontoni <notifications@github.com>, 21 Şub 2021 Paz, 19:59 tarihinde
şunu yazdı:

**Comment by intercontoni** [comment]
Whatsapp üzerinden konuşmayı deneyelim

Lütfen https://intercongreso.vps.co.ve adresine gidin

sayfanın altında whatsapp göreceksiniz ... aşağıda ...
