### ISSUE TITLE
Bug in the storage adapter [postgres]

### ISSUE THREAD

**Issue by fccoelho** [gunthercox/ChatterBot#2134]
The storage adapter code is buggy, I am getting this error no matter what configuration I try:

```python
File "/usr/local/lib/python3.8/site-packages/chatterbot/storage/sql_storage.py", line 43, in set_sqlite_pragma
    dbapi_connection.execute('PRAGMA journal_mode=WAL')
AttributeError: 'psycopg2.extensions.connection' object has no attribute 'execute'
```
I really don't need this feature. Can I disable it?

**Comment by AnAnalogGuy** [comment]
I don't know the problem but it doesn't look like an issue in chatterbot. Are you sure your squlite db is working correctly?

**Comment by gunthercox** [comment]
I realize this is an older issue so I'm going to close it off, but I just reviewed ChatterBot's postgres compatibility and can confirm that the exception mentioned here has been resolved.

I did find a separate issue **(that will be fixed as of ChatterBot version `1.2.6`)**:

```python
Traceback (most recent call last):
  File "/home/robot/Desktop/GitHub/ChatterBot/examples/terminal_example.py", line 13, in <module>
    bot = ChatBot(
          ^^^^^^^^
  File "/site-packages/chatterbot/chatterbot.py", line 62, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/site-packages/chatterbot/utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/site-packages/chatterbot/storage/sql_storage.py", line 47, in __init__
    if not inspect(self.engine).has_table(self.engine, 'statement'):
```

**Notes:**

Confirmed fix with:
* `chatterbot 1.2.6`
* `psycopg2-binary 2.9.10`
* `postgres:16` (Docker image)
