### ISSUE TITLE
'ChatBot' object has no attribute 'find'

### ISSUE THREAD

**Issue by EthanChenster** [gunthercox/ChatterBot#2165]
While running this

`from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatbot = ChatBot('Charlie')

trainer = ListTrainer(chatbot)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

response = chatbot.get_response('I would like to book a flight.')

print(response)`

I got 

`/opt/virtualenvs/python3/lib/python3.8/site-packages/chatterbot/storage/jsonfile.py:24: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  warnings.warn(
Traceback (most recent call last):
  File "main.py", line 9, in <module>
    trainer.train([
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chatterbot/trainers.py", line 82, in train
    statement = self.get_or_create(text)
  File "/opt/virtualenvs/python3/lib/python3.8/site-packages/chatterbot/trainers.py", line 25, in get_or_create
    statement = self.storage.find(statement_text)
AttributeError: 'ChatBot' object has no attribute 'find'`

Is there any solution to this?

**Comment by gunthercox** [comment]
This is an old issue, but `find` was a deprecated function name in storage adapters that has since been replaced by a similar but more flexible `filter` function. I believe this should be fixed in newer versions of ChatterBot.
