### ISSUE TITLE
Unable to install, anywhere

### ISSUE THREAD

**Issue by MistakingManx** [gunthercox/ChatterBot#2172]
pip install, pip3 install, both end up failing (pip3 gets a lot further though)
So I tried to manually install it from the GitHub as instructed and got this error.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/chatterbot/__main__.py", line 20, in <module>
    print(get_chatterbot_version())
  File "/usr/local/lib/python3.6/dist-packages/chatterbot/__main__.py", line 15, in get_chatterbot_version
    return config['chatterbot']['version']
  File "/usr/lib/python3.6/configparser.py", line 959, in __getitem__
    raise KeyError(key)
KeyError: 'chatterbot'
```

Could you help me install it?

**Comment by cryokesh34** [comment]
Try specifying the version of chatterbot. The somewhat stable version of chatterbot is 1.0.4. So the command will be: "pip install chatterbot==1.0.4". Also, be aware, that after installation you have to "pip install pytz" to be able to use it.
