### ISSUE TITLE
errors while checking chatterbot version

### ISSUE THREAD

**Issue by anukaal** [gunthercox/ChatterBot#2181]
python -m chatterbot --version
Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.9/site-packages/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/usr/local/lib/python3.9/site-packages/chatterbot/chatterbot.py", line 3, in <module>
    from chatterbot.logic import LogicAdapter
  File "/usr/local/lib/python3.9/site-packages/chatterbot/logic/__init__.py", line 1, in <module>
    from chatterbot.logic.logic_adapter import LogicAdapter
  File "/usr/local/lib/python3.9/site-packages/chatterbot/logic/logic_adapter.py", line 3, in <module>
    from chatterbot.search import IndexedTextSearch
  File "/usr/local/lib/python3.9/site-packages/chatterbot/search.py", line 1, in <module>
    from chatterbot.conversation import Statement
  File "/usr/local/lib/python3.9/site-packages/chatterbot/conversation.py", line 1, in <module>
    from pytz import UTC
ModuleNotFoundError: No module named 'pytz'

**Comment by cryokesh34** [comment]
Seems like you are missing a module. Try `pip install pytz`.

**Comment by EgyptianM** [comment]
Same issue and the module is installed

        `C:\Users\Original\Downloads>pip install pytz
          Requirement already satisfied: pytz in c:\users\original\appdata\local\packages\pythonsoftwarefoundation.python.3.7_qbz5n2kfra8p0\localcache\local-packages\python37\site-packages (2021.3)`
