### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while decoding a JSON array from a unicode string

### ISSUE THREAD

**Issue by z4nD4R** [gunthercox/ChatterBot#219]
Hi All,

I'm starting with ChatterBot and so I've followed the doc. - http://chatterbot.readthedocs.io/en/latest/training.html#set-trainer. 

Unfortunatelly I failed in very begginig:

```python
from chatterbot import ChatBot
from chatterbot.training.trainers import ListTrainer

chatterbot = ChatBot("Training Example")
chatterbot.set_trainer(ListTrainer)

chatterbot.train([
    "How are you?",
    "I am good.",
    "That is good to hear.",
    "Thank you",
    "You are welcome.",
])
```

I've got:

```python
Traceback (most recent call last):
  File "createJson.py", line 52, in <module>
    u"You are welcome.",
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/chatterbot/training/trainers.py", line 36, in train
    self.storage.update(statement)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/chatterbot/adapters/storage/jsondatabase.py", line 126, in update
    self.database.data(key=statement.text, value=data)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/db.py", line 76, in data
    self._set_content(key, value)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/db.py", line 37, in _set_content
    obj = self._get_content()
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/db.py", line 26, in _get_content
    obj = read_data(self.path)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/file_writer.py", line 11, in read_data
    obj = decode(content)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/compat.py", line 22, in decode
    return json_decode(value)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
RecursionError: maximum recursion depth exceeded while decoding a JSON array from a unicode string
```

Any help is highly appreciated.

Thank you.

**Comment by mbarisa** [comment]
Hey, I did not try it out but you have a typo in your JSON, at the end of your array you have a colon, you should remove it so it looks like:

chatterbot.train([
"How are you?",
"I am good.",
"That is good to hear.",
"Thank you",
"You are welcome."
])

Please let me know if that was helpful

**Comment by z4nD4R** [comment]
@mbarisa : I've tried also withou the colon, but the result is the same. Looks like some deep issue in JSON and how it parse or handle string into array. Didn't have time to go to deep.

 File "createJson.py", line 52, in <module>
    u"You are welcome."
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/chatterbot/training/trainers.py", line 36, in train
    self.storage.update(statement)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/chatterbot/adapters/storage/jsondatabase.py", line 126, in update
    self.database.data(key=statement.text, value=data)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/db.py", line 76, in data
    self._set_content(key, value)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/db.py", line 37, in _set_content
    obj = self._get_content()
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/db.py", line 26, in _get_content
    obj = read_data(self.path)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/file_writer.py", line 11, in read_data
    obj = decode(content)
  File "/home/ms/sataData/Progr/python/jarvis/virtualenv/boot/lib/python3.5/site-packages/jsondb/compat.py", line 22, in decode
    return json_decode(value)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
RecursionError: maximum recursion depth exceeded while decoding a JSON array from a unicode string

**Comment by gunthercox** [comment]
Hi @z4nD4R, I cannot replicate your issue with the code you posted. I'm going to close this issue off for now, but feel free to reopen it if you continue to run into the problem.
