### ISSUE TITLE
a problem occurred when I tried to run the example 

### ISSUE THREAD

**Issue by samsam3215** [gunthercox/ChatterBot#2208]
hi, my name is peter and I'm new to python.
I got some errors when I tried to run the simple example after I installed chatterbot. could please advise how can I fix the problem? 
the errors are shown below:

Traceback (most recent call last):
  File "D:\test.py", line 5, in <module>
    chatbot = ChatBot('Charlie')
  File "D:\Python\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "D:\Python\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "D:\Python\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "D:\Python\lib\site-packages\chatterbot\storage\storage_adapter.py", line 23, in __init__
    'tagger_language', languages.ENG
  File "D:\Python\lib\site-packages\chatterbot\tagging.py", line 26, in __init__
    self.nlp = spacy.load(self.language.ISO_639_1.lower())
  File "D:\Python\lib\site-packages\spacy\__init__.py", line 27, in load
    return util.load_model(name, **overrides)
  File "D:\Python\lib\site-packages\spacy\util.py", line 139, in load_model
    raise IOError(Errors.E050.format(name=name))
OSError: [E050] Can't find model 'en'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.

**Comment by Diego448** [comment]
Please see [this](https://github.com/gunthercox/ChatterBot/issues/2120) thread this is the fastest way to solve your issue
