### ISSUE TITLE
Error with the Simple Example

### ISSUE THREAD

**Issue by NotRambi** [gunthercox/ChatterBot#2253]
Hello everybody, after having installed the chatterbot package I tried to execute this code (copied from the chatterbot site):

from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer

chatbot = ChatBot('Charlie')

trainer = ListTrainer(chatbot)

trainer.train([
    "Hi, can I help you?",
    "Sure, I'd like to book a flight to Iceland.",
    "Your flight has been booked."
])

response = chatbot.get_response('I would like to book a flight.')
print(response)

but I received this error:

Traceback (most recent call last):
  File "provabot.py", line 5, in <module>
    chatbot = ChatBot('Charlie')
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__
    super().__init__(**kwargs)
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\storage\storage_adapter.py", line 23, in __init__
    'tagger_language', languages.ENG
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\site-packages\chatterbot\tagging.py", line 20, in __init__
    import spacy
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\site-packages\spacy\__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\site-packages\thinc\__init__.py", line 5, in <module>
    import numpy  # noqa: F401
  File "C:\Users\aless\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py", line 148, in <module>
    from . import _distributor_init
  File "C:\Users\aless\AppData\Roaming\Python\Python37\site-packages\numpy\_distributor_init.py", line 26, in <module>
    WinDLL(os.path.abspath(filename))
  File "C:\Users\aless\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 non è un'applicazione di Win32 valida

(is in Italian, the last line says "%1 is not a valid Win32's application ")

I have win11 64bit
Python 3.7 64bit

**Comment by gunthercox** [comment]
I believe this may have been related to an outdated dependency of `spacy`. The latest version of ChatterBot uses a newer version of that package which should resolve this issue.
