### ISSUE TITLE
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package

### ISSUE THREAD

**Issue by ivasve** [gunthercox/ChatterBot#2258]
This issue has been here before, it's closed, but I haven't found a solution there. I installed chatterbot with 'clone' from Github. Then I created a new file ChatterBot/chatterbot2.py. I copied all the commands from the Chatterbot.io Docs and ran the files. I received this error for the original file chatterbot.py (which I downloaded from Github). How can I solve it? Thanks a lot. 
```
Traceback (most recent call last):
  File "...\ChatterBot\chatterbot\chatterbot2.py", line 1, in <module>
    from chatterbot import ChatBot
  File "...\ChatterBot\chatterbot\chatterbot.py", line 2, in <module>
    from chatterbot.storage import StorageAdapter
ModuleNotFoundError: No module named 'chatterbot.storage'; 'chatterbot' is not a package
```

**Comment by gunthercox** [comment]
I believe this might have been a packaging issue with older versions of ChatterBot. It should be resolved now so I'm going to close this issue off.
