### ISSUE TITLE
Cannot find english file

### ISSUE THREAD

**Issue by sudocpMATHdotPY** [gunthercox/ChatterBot#2272]
Traceback (most recent call last):
  File "C:\Users\USER\Downloads\BotPeople\bot.py", line 33, in <module>
    train()
  File "C:\Users\USER\Downloads\BotPeople\bot.py", line 25, in train
    trainer.train("chatterbot.corpus.english")
  File "C:\Users\USER\Downloads\BotPeople\chatterbot\trainers.py", line 135, in train
    for corpus, categories, file_path in load_corpus(*data_file_paths):
  File "C:\Users\USER\Downloads\BotPeople\chatterbot\corpus.py", line 84, in load_corpus
    corpus_data = read_corpus(file_path)
  File "C:\Users\USER\Downloads\BotPeople\chatterbot\corpus.py", line 58, in read_corpus
    with io.open(file_name, encoding='utf-8') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\USER\\chatterbot_corpus\\data\\english'

I installed the package normally using pip

**Comment by zikavirustofu** [comment]
getting the same issues too 

`from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

# Create a chatbot
chatbot = ChatBot('MyBot')

# Train the chatbot using the ChatterBot Corpus
trainer = ChatterBotCorpusTrainer(chatbot)
trainer.train('chatterbot.corpus.english')

# Get a response from the chatbot
response = chatbot.get_response('Hello, how are you?')
print(response)`

i get the exact same errors

was using python 3.7.9
en_core_web_sm 3.5.0
spacy 3.5.1

**Comment by gunthercox** [comment]
I realize this is an old issue, but I believe this has been resolved in newer versions of the `chatterbot-corpus` package. Please let me know if issues persist.
