### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by BubbleBubblePlayz** [gunthercox/ChatterBot#2285]
My code has my file added but I have no clue what is going on. 
```# Save the conversations to a corpus file
with open('conversations.corpus.json', 'w') as f:
    json.dump(conversations, f)

# Train the chatbot on the corpus file
trainer.train('conversations.corpus.json')

**Comment by BubbleBubblePlayz** [comment]
OK I have fixed that problem but now there is a new error.
```/home/runner/Chatbot-1/venv/lib/python3.8/site-packages/chatterbot/storage/jsonfile.py:24: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  warnings.warn(
Traceback (most recent call last):
  File "main.py", line 27, in <module>
    trainer.train('/home/runner/Chatbot-1/conversations.corpus.json')
  File "/home/runner/Chatbot-1/venv/lib/python3.8/site-packages/chatterbot/trainers.py", line 114, in train
    corpus_data = self.corpus.load_corpus(corpus)
  File "/home/runner/Chatbot-1/venv/lib/python3.8/site-packages/chatterbot_corpus/corpus.py", line 73, in load_corpus
    for key in list(corpus.keys()):
AttributeError: 'list' object has no attribute 'keys'
