### ISSUE TITLE
missing argument in load() function

### ISSUE THREAD

**Issue by arya2910** [gunthercox/ChatterBot#2298]
Traceback (most recent call last):
  File "chat.py", line 24, in <module>
    trainer.train('/home/gt43/Downloads/projects/chatterbot/operator.yml')
  File "/home/gt43/Downloads/projects/chatterbot/myenv/lib/python3.7/site-packages/chatterbot/trainers.py", line 135, in train
    for corpus, categories, file_path in load_corpus(*data_file_paths):
  File "/home/gt43/Downloads/projects/chatterbot/myenv/lib/python3.7/site-packages/chatterbot/corpus.py", line 84, in load_corpus
    corpus_data = read_corpus(file_path)
  File "/home/gt43/Downloads/projects/chatterbot/myenv/lib/python3.7/site-packages/chatterbot/corpus.py", line 59, in read_corpus
    return yaml.load(data_file)
TypeError: load() missing 1 required positional argument: 'Loader'

**Comment by arya2910** [comment]
solved the error it reuire pyyaml version 5.4
