### ISSUE TITLE
Does ChatterBot work with Python 3.6?

### ISSUE THREAD

**Issue by ThePythonDev** [gunthercox/ChatterBot#2369]
Hello, I want to make an AI Chatbot that learns from the user on ubuntu but when I try to install ChatterBot with pip3
it errors out with 
```
Collecting pyyaml<5.4,>=5.3 (from chatterbot)
  Using cached https://files.pythonhosted.org/packages/64/c2/b80047c7ac2478f9501676c988a5411ed5572f35d1beff9cae07d321512c/PyYAML-5.3.1.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/PyYAML.egg-info
    writing pip-egg-info/PyYAML.egg-info/PKG-INFO
    writing dependency_links to pip-egg-info/PyYAML.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/PyYAML.egg-info/top_level.txt
    writing manifest file 'pip-egg-info/PyYAML.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-aotwku3h/pyyaml/setup.py", line 314, in <module>
        python_requires='>=2.7, !=3.0.*, !=3.1.*, !=3.2.*, !=3.3.*, !=3.4.*',
      File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 278, in run
        self.find_sources()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 293, in find_sources
        mm.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 524, in run
        self.add_defaults()
      File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 560, in add_defaults
        sdist.add_defaults(self)
      File "/usr/lib/python3/dist-packages/setuptools/command/py36compat.py", line 36, in add_defaults
        self._add_defaults_ext()
      File "/usr/lib/python3/dist-packages/setuptools/command/py36compat.py", line 120, in _add_defaults_ext
        self.filelist.extend(build_ext.get_source_files())
      File "/tmp/pip-build-aotwku3h/pyyaml/setup.py", line 199, in get_source_files
        self.cython_sources(ext.sources, ext)
      File "/usr/lib/python3.6/distutils/cmd.py", line 103, in __getattr__
        raise AttributeError(attr)
    AttributeError: cython_sources
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-aotwku3h/pyyaml/
``
```
I am thinking this is because Pyyaml is not compatible with python 3.6.9 but I don't know how to fix this.
so long story short how do I install ChatterBot on python 3.6.9

**Comment by ThePythonDev** [comment]
UPDATE:
some how I was able to install on RPI 4. I will leave this open for others having this problem

**Comment by gunthercox** [comment]
Support for Python 3.6 has been dropped in see #2389. Version 3.9 will be the oldest supported version for now, with plans to add support for newer versions coming soon.
