### ISSUE TITLE
Chatter bot error

### ISSUE THREAD

**Issue by hamzakiyani98** [gunthercox/ChatterBot#2372]
Traceback (most recent call last):
  File "untitled0.py", line 17, in <module>
    database_uri='sqlite:///database.sqlite3'
  File "C:\Users\Kuham\anaconda3\envs\chatbot_37\lib\site-packages\chatterbot\chatterbot.py", line 28, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\Kuham\anaconda3\envs\chatbot_37\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(*args, **kwargs)
  File "C:\Users\Kuham\anaconda3\envs\chatbot_37\lib\site-packages\chatterbot\storage\sql_storage.py", line 20, in __init__

**Comment by skstanwar** [comment]
which Python version you using ?
