### ISSUE TITLE
Error in installing Chatterbot.

### ISSUE THREAD

**Issue by Prajapati-Shubham** [gunthercox/ChatterBot#2382]
Collecting chatterbot
  Using cached ChatterBot-1.0.5-py2.py3-none-any.whl.metadata (8.1 kB)
Collecting mathparse<0.2,>=0.1 (from chatterbot)
  Using cached mathparse-0.1.2-py3-none-any.whl.metadata (776 bytes)
Requirement already satisfied: nltk<4.0,>=3.2 in c:\users\--\appdata\local\programs\python\python312\lib\site-packages (from chatterbot) (3.8.1)
Collecting pint>=0.8.1 (from chatterbot)
  Using cached Pint-0.24.3-py3-none-any.whl.metadata (8.5 kB)
Collecting pymongo<4.0,>=3.3 (from chatterbot)
  Using cached pymongo-3.13.0.tar.gz (804 kB)
  Preparing metadata (setup.py) ... done
Collecting python-dateutil<2.8,>=2.7 (from chatterbot)
  Using cached python_dateutil-2.7.5-py2.py3-none-any.whl.metadata (7.5 kB)
Collecting pyyaml<5.2,>=5.1 (from chatterbot)
  Using cached PyYAML-5.1.2.tar.gz (265 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\--\AppData\Local\Temp\pip-install-5dv6vnfj\pyyaml_2ef76d984def475d9c0a5afc98636544\setup.py", line 291, in <module>
          setup(
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 183, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\core.py", line 199, in run_commands
          dist.run_commands()
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
          self.run_command(cmd)
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\dist.py", line 999, in run_command
          super().run_command(command)
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
          cmd_obj.run()
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 312, in run
          self.find_sources()
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 320, in find_sources
          mm.run()
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 541, in run
          self.add_defaults()
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\egg_info.py", line 579, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\command\sdist.py", line 109, in add_defaults
          super().add_defaults()
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 238, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 323, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\--\AppData\Local\Temp\pip-install-5dv6vnfj\pyyaml_2ef76d984def475d9c0a5afc98636544\setup.py", line 199, in get_source_files
          self.cython_sources(ext.sources, ext)
          ^^^^^^^^^^^^^^^^^^^
        File "C:\Users\--\AppData\Local\Programs\Python\Python312\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by gunthercox** [comment]
I believe this may be resolved via the `pyyaml` upgrade issued in #2389. Please note that Python 3.12 is not yet supported by this project.
