### ISSUE TITLE
RepetitiveResponseFilter example not working

### ISSUE THREAD

**Issue by rileyjshaw** [gunthercox/ChatterBot#299]
I tried to adapt the example at http://chatterbot.readthedocs.io/en/stable/filters/index.html to my code, but I keep getting the error:

```bash
Traceback (most recent call last):
  File "bot.py", line 41, in <module>
    bot_input = bot.get_response(None)
  File "/Users/rileyshaw/code/chat/venv/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 141, in get_response
    self.storage.generate_base_query(self)
  File "/Users/rileyshaw/code/chat/venv/lib/python3.5/site-packages/chatterbot/adapters/storage/storage_adapter.py", line 23, in generate_base_query
    filter_instance = Filter()
TypeError: 'str' object is not callable
```

It looks like `Filter` is somehow being read as a string?

For reference, here's the code I'm using:

```python
from chatterbot import ChatBot
from chatterbot.trainers import ListTrainer


# Create a new ChatBot!
bot = ChatBot("demo",
    storage_adapter="chatterbot.adapters.storage.MongoDatabaseAdapter",
    logic_adapters=[
        "chatterbot.adapters.logic.ClosestMeaningAdapter",
        "chatterbot.adapters.logic.ClosestMatchAdapter"
    ],
    input_adapter="chatterbot.adapters.input.TerminalAdapter",
    output_adapter="chatterbot.adapters.output.TerminalAdapter",
    filters="chatterbot.filters.RepetitiveResponseFilter",
    database="demodb",  # (Already trained in this DB)
    database_uri="mongodb://localhost:27017/",
    read_only=True,
)

print("Type something to begin...")

# The following loop will execute each time the user enters input
while True:
    try:
        # We pass None to this method because the parameter
        # is not used by the TerminalAdapter
        bot_input = bot.get_response(None)

    # Press ctrl-c or ctrl-d on the keyboard to exit
    except (KeyboardInterrupt, EOFError, SystemExit):
        break
```

I also tried `from chatterbot.filters import RepetitiveResponseFilter` and using that directly, but that failed with:

```bash
Traceback (most recent call last):
  File "demo.py", line 42, in <module>
    bot_input = bot.get_response(None)
  File "/Users/rileyshaw/code/chat/venv/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 141, in get_response
    self.storage.generate_base_query(self)
  File "/Users/rileyshaw/code/chat/venv/lib/python3.5/site-packages/chatterbot/adapters/storage/storage_adapter.py", line 22, in generate_base_query
    for Filter in chatterbot.filters:
TypeError: 'type' object is not iterable
```

**Comment by rileyjshaw** [comment]
```python
from chatterbot.filters import RepetitiveResponseFilter

# ...

    filters=[RepetitiveResponseFilter],

```

seems to work... is this right? :S

**Comment by navyad** [comment]
@rileyjshaw  Yeah that will work, expected way is to pass filters as a tuple

**Comment by gunthercox** [comment]
@rileyjshaw There is a known issue with the current release where the filters parameter is expecting a callable for the filter class instead of a string path to the callable class. This has been fixed but the changes won't be available until the next version of ChatterBot is released.

**Comment by rileyjshaw** [comment]
Cool, thanks!!

**Comment by gunthercox** [comment]
@rileyjshaw ChatterBot version 0.4.10 has been released.
