### ISSUE TITLE
ImportError: No module named 'jsondb'

### ISSUE THREAD

**Issue by 12520054** [gunthercox/ChatterBot#425]
Hi there,
I'm trying to deploy my chat bot to openshift flask on python 3.5
Then I get that issue
```
Searching for chatterbot
Reading https://pypi.python.org/simple/chatterbot/
Best match: ChatterBot 0.4.13
Downloading https://pypi.python.org/packages/37/91/f3f6b38a47cc441b253c23233ddbf444fed51083eb1eaecb2535b115025b/ChatterBot-0.4.13.tar.gz#md5=a2bcab3dfb59441113973a97ba420f01
Processing ChatterBot-0.4.13.tar.gz
Writing /tmp/easy_install-rquhl12e/ChatterBot-0.4.13/setup.cfg
Running ChatterBot-0.4.13/setup.py -q bdist_egg --dist-dir /tmp/easy_install-rquhl12e/ChatterBot-0.4.13/egg-dist-tmp-dglb_h_f
Traceback (most recent call last):
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 152, in save_modules
    yield saved
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 193, in setup_context
    yield
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 237, in run_setup
    DirectorySandbox(setup_dir).run(runner)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 267, in run
    return func()
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 236, in runner
    _execfile(setup_script, ns)
  File "/opt/rh/rh-python35/root/usr/lib/python3.5/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-rquhl12e/ChatterBot-0.4.13/setup.py", line 7, in <module>
    author_email='12520054@gm.uit.edu.vn',
  File "/tmp/easy_install-rquhl12e/ChatterBot-0.4.13/chatterbot/__init__.py", line 4, in <module>
  File "/tmp/easy_install-rquhl12e/ChatterBot-0.4.13/chatterbot/chatterbot.py", line 2, in <module>
  File "/tmp/easy_install-rquhl12e/ChatterBot-0.4.13/chatterbot/adapters/storage/__init__.py", line 3, in <module>
  File "/tmp/easy_install-rquhl12e/ChatterBot-0.4.13/chatterbot/adapters/storage/jsonfile.py", line 3, in <module>
ImportError: No module named 'jsondb'
```
Any one help me please.
Thanks so much :D

**Comment by bkrmendy** [comment]
Also had this. Did you try installing jsondb?

**Comment by gunthercox** [comment]
Hi @12520054, @bkrmendy is correct. You should be able to resolve this issue by installing ChatterBot's dependencies before installing chatterbot itself. I've opened a pull request (#426) that makes changes to correct this issue in future versions of ChatterBot. Thank you for reporting the issue.
