### ISSUE TITLE
Can't get the example code to work.

### ISSUE THREAD

**Issue by tryzombie501** [gunthercox/ChatterBot#451]
It's most likely my stupidity 

this is my error on python 3.5.2

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/test.py", line 1, in <module>
    from chatterbot import ChatBot
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\chatterbot.py", line 4, in <module>
    from .logic import MultiLogicAdapter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\logic\__init__.py", line 1, in <module>
    from .logic_adapter import LogicAdapter
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\logic\logic_adapter.py", line 3, in <module>
    from chatterbot.utils import import_module
ImportError: cannot import name 'import_module'

**Comment by graylu21** [comment]
Which example are you trying to run?

**Comment by gunthercox** [comment]
Hi @tryzombie501 See my response here for how to fix: https://github.com/gunthercox/ChatterBot/issues/443

**Comment by tryzombie501** [comment]
Thank you, I've been dying to play around with this.

**Comment by tryzombie501** [comment]
Sorry to bother a closed issue but i was woundering if the chatbot can learn from speaking with the user for example through terminal

**Comment by graylu21** [comment]
Yes, check out the examples, also the docs!

**Comment by tryzombie501** [comment]
but from what i seen in the example terminal was that it only talks to the user, Or does it learn without needing .train called?

**Comment by gunthercox** [comment]
@tryzombie501 That is correct, the chat bot will learn by speaking to the user. You can prevent the chat bot from learning by setting `read_only=True`, but by default the chat bot will continuously learn based on how the user responds to it.
