### ISSUE TITLE
Error running basic_example.py

### ISSUE THREAD

**Issue by boris314159** [gunthercox/ChatterBot#457]
Installed from ZIP file on 12/02/16... Python 3.5.2
This ran a couple of days ago, just re-installed...maybe something broken?

>>> from chatterbot import ChatBot
>>> chatbot = ChatBot("Charlie")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\BockJoel\Downloads\ChatterBot-0.5.0\chatterbot\chatterbot.py", line 36, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\BockJoel\Downloads\ChatterBot-0.5.0\chatterbot\utils.py", line 81, in initialize_class
    return Class(**kwargs)
  File "C:\Users\BockJoel\Downloads\ChatterBot-0.5.0\chatterbot\storage\jsonfile.py", line 14, in __init__
    from jsondb import Database
  File "C:\Python35-64\lib\site-packages\jsondb\__init__.py", line 14, in <module>
    import core
ImportError: No module named 'core'

**Comment by boris314159** [comment]
FIXED by following these instructions:

_If you see a directory named utils delete it.
Also if you see a directory named adapters delete it.

I had a similar issue recently. For some reason pip appears to be adding cached outdated modules from the previous version when ChatterBot gets upgraded._

**Comment by gunthercox** [comment]
Hi @boris314159, glad you were able to resolve the issue. Sorry I didn't get a chance to respond earlier.

**Comment by boris314159** [comment]
It's all good, thank you.
I'm excited about the ChatterBot project and hope to maybe contribute once
I get up to speed.
