### ISSUE TITLE
AttributeError: module 'chatterbot.logic' has no attribute 'BestMatch'

### ISSUE THREAD

**Issue by tshrjn** [gunthercox/ChatterBot#460]
I tried the simple [terminal example](https://github.com/gunthercox/ChatterBot/blob/master/examples/terminal_example.py) but got this error. Any suggestions ? Thanks in advance.

```
/Users/tshrjn/anaconda3/lib/python3.5/site-packages/chatterbot/storage/jsonfile.py:19: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production application environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "terminal_example.py", line 19, in <module>
    database="../database.db"
  File "/Users/tshrjn/anaconda3/lib/python3.5/site-packages/chatterbot/chatterbot.py", line 49, in __init__
    self.logic.add_adapter(adapter, **kwargs)
  File "/Users/tshrjn/anaconda3/lib/python3.5/site-packages/chatterbot/logic/multi_adapter.py", line 99, in add_adapter
    utils.validate_adapter_class(adapter, LogicAdapter)
  File "/Users/tshrjn/anaconda3/lib/python3.5/site-packages/chatterbot/utils.py", line 112, in validate_adapter_class
    if not issubclass(import_module(validate_class), Adapter):
  File "/Users/tshrjn/anaconda3/lib/python3.5/site-packages/chatterbot/utils.py", line 65, in import_module
    return getattr(module, module_parts[-1])
AttributeError: module 'chatterbot.logic' has no attribute 'BestMatch'
```

**Comment by gunthercox** [comment]
Hi @tshrjn, sorry about the error, `BestMatch` was a new class name that I added a few hours ago. I've released the latest version of ChatterBot which included this class. To upgraded run:

```
pip install chatterbot --upgrade
```

This should fix your issue.
