### ISSUE TITLE
No module named storage

### ISSUE THREAD

**Issue by HelloJyo** [gunthercox/ChatterBot#478]
I am trying to create a web site to which i need to integrate the chatterbot. I created my own web page using Django. But when tried to integrate the chatterbot, i got this error.... i didn't used "django_chatterbot" and just used the chatterbot package...

```
python manage.py runserver causes the below error
----------------------------------------------------------------------------------------------------------------------------------

Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fe0db2610c8>
Traceback (most recent call last):
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cedex/Desktop/test2/mysite/urls.py", line 23, in <module>
    url(r'', include('chatbot.urls')),
  File "/home/cedex/.local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cedex/Desktop/test2/chatbot/urls.py", line 2, in <module>
    from . import views
  File "/home/cedex/Desktop/test2/chatbot/views.py", line 23, in <module>
    from chatter import *
  File "/home/cedex/Desktop/test2/chatbot/chatter.py", line 1, in <module>
    from chatterbot import ChatBot
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/chatterbot.py", line 3, in <module>
    from .storage import StorageAdapter
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/storage/__init__.py", line 2, in <module>
    from .django_storage import DjangoStorageAdapter
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/storage/django_storage.py", line 1, in <module>
    from chatterbot.storage import StorageAdapter
ImportError: No module named storage
ython manage.py runserver
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x7fe0db2610c8>
Traceback (most recent call last):
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/management/base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/checks/registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cedex/Desktop/test2/mysite/urls.py", line 23, in <module>
    url(r'', include('chatbot.urls')),
  File "/home/cedex/.local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 52, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/cedex/Desktop/test2/chatbot/urls.py", line 2, in <module>
    from . import views
  File "/home/cedex/Desktop/test2/chatbot/views.py", line 23, in <module>
    from chatter import *
  File "/home/cedex/Desktop/test2/chatbot/chatter.py", line 1, in <module>
    from chatterbot import ChatBot
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/chatterbot.py", line 3, in <module>
    from .storage import StorageAdapter
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/storage/__init__.py", line 2, in <module>
    from .django_storage import DjangoStorageAdapter
  File "/home/cedex/Desktop/test2/chatbot/chatterbot/storage/django_storage.py", line 1, in <module>
    from chatterbot.storage import StorageAdapter
ImportError: No module named storage
```

**Comment by ThomasKoscheck** [comment]
Same issue

**Comment by gunthercox** [comment]
Hi @HelloJyo, what do you get as output when you enter `python -m chatterbot --version` in your terminal?

**Comment by ThomasKoscheck** [comment]
Hey, I am having a similar Error:
```
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    output_adapter="chatterbot.output.OutputFormatAdapter"
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 36, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/utils.py", line 81, in initialize_class
    return Class(**kwargs)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/storage/jsonfile.py", line 14, in __init__
    from jsondb import Database
ImportError: No module named jsondb
```
This error also appears, when I am trying to run some examples of you.

When I am running `python -m chatterbot --version`, it gives me this output.
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/__main__.py", line 8, in <module>
    print(chatterbot.__version__)
AttributeError: 'module' object has no attribute '__version__'
```

**Comment by HelloJyo** [comment]
I have a traceback as follows when i run the django application in the browser

>
Environment:


Request Method: POST
Request URL: http://127.0.0.1:8000/views/act

Django Version: 1.9.2
Python Version: 2.7.6
Installed Applications:
['django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'chatbot',
 'chatbot.chatterbot',
 'chatbot.chatterbot.storage']
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']



Traceback:

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/jyothish/Desktop/test2/chatbot/views.py" in act
  58. 		    database='mydb'

File "/home/jyothish/Desktop/test2/chatbot/chatterbot/chatterbot.py" in __init__
  32.         utils.validate_adapter_class(storage_adapter, StorageAdapter)

File "/home/jyothish/Desktop/test2/chatbot/chatterbot/utils.py" in validate_adapter_class
  116.                 Adapter.__name__

Exception Type: InvalidAdapterException at /views/act
Exception Value: 'chatterbot.storage.MongoDatabaseAdapter must be a subclass of Adapter'
 

>

**Comment by gunthercox** [comment]
@HelloJyo can you post your `CHATTERBOT` configuration from your `settings.py` file? It may be able to help me determine what the cause of this issue is.
***
@ThomasKoscheck I don't think you have chatterbot installed correctly. The output `ImportError: No module named jsondb` tells me that you don't have that package installed and that you are likely missing other requirements as well. The recommended way to install chatterbot is by running:
```
pip install chatterbot --upgrade
```
or, if you are using linux:
```
sudo pip install chatterbot
```

**Comment by gunthercox** [comment]
@HelloJyo Did you follow the setup instructions for using ChatterBot with Django?
http://chatterbot.readthedocs.io/en/latest/django/index.html#installation

**Comment by HelloJyo** [comment]
My settings.py file is this.....


"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 1.9.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'blk-g3_&rs(+0v(a!e@=w1ek@=3r4dqv7ke#vx88mc^(i3@#^='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatbot',
    'chatbot.chatterbot',
    'chatbot.chatterbot.storage',

]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mysite.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'

**Comment by gunthercox** [comment]
Ah, I'm pretty sure I see your issue. For ChatterBot to work in Django, you need to include it's Django extension module in your `INSTALLED_APPS` list. So you should add `'chatterbot.ext.django_chatterbot',` in your installed apps.

Also, I see that you have the following in your installed apps as well:
```
    'chatbot',
    'chatbot.chatterbot',
    'chatbot.chatterbot.storage',
```

If the `chatterbot` module is something you made yourself, you should rename it to stop import errors. For example, if you try to import something `from chatterbot ...` it will import from that module instead of the actual `chatterbot` package and you will get errors about things like modules not being found.

If the  `chatterbot` module is just a downloaded copy of ChatterBot, I recommend you install in with pip so that you don't have to worry about managing the package manually.

I hope this helps.

**Comment by gunthercox** [comment]
There is also a Django example on GitHub if an example would help:
https://github.com/gunthercox/ChatterBot/tree/master/examples/django_app

**Comment by HelloJyo** [comment]
chatterbot is the downloaded copy and I made some changes in it. I want to use that as a module in a web application. I didn't want to install the chatterbot, instead want to use the downloaded copy. But when i try to do so, I am getting this....

> 

Unhandled exception in thread started by <function wrapper at 0x7f478fee4e60>
Traceback (most recent call last):
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/cedex/.local/lib/python2.7/site-packages/django/apps/config.py", line 123, in create
    import_module(entry)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named chatterbot

> 


Is there a way to use the downloaded copy as an independent one???

**Comment by gunthercox** [comment]
Sure, you'll just have to remember to modify any imports to match the name spacing of your app.

**Comment by HelloJyo** [comment]
Thanks... Now it's working..
