### ISSUE TITLE
Python3.6 Import Error importing utils

### ISSUE THREAD

**Issue by NotSoSuper** [gunthercox/ChatterBot#530]
Attempting to import `from chatterbot import ChatBot` yields error 

```
root@host:~# python3.6
Python 3.6.0 (default, Dec 24 2016, 00:44:03)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from chatterbot import ChatBot
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ChatterBot-0.5.3-py3.6.egg/chatterbot/__init__.py", line 4, in <module>
    from .chatterbot import ChatBot
  File "/usr/local/lib/python3.6/site-packages/ChatterBot-0.5.3-py3.6.egg/chatterbot/chatterbot.py", line 4, in <module>
    from .input import InputAdapter
  File "/usr/local/lib/python3.6/site-packages/ChatterBot-0.5.3-py3.6.egg/chatterbot/input/__init__.py", line 6, in <module>
    from .terminal import TerminalAdapter
  File "/usr/local/lib/python3.6/site-packages/ChatterBot-0.5.3-py3.6.egg/chatterbot/input/terminal.py", line 4, in <module>
    from chatterbot.utils import input_function
ImportError: cannot import name 'input_function'
```

Python 3.6 was just recently released and I'm not really sure what's causing this import error...

**Comment by vkosuri** [comment]
Thanks, we haven't add it to in Travis also, You could try it Python earlier versions at this moment.

Cheers 👍

**Comment by gunthercox** [comment]
@NotSoSuper, See my response to https://github.com/gunthercox/ChatterBot/issues/443#issuecomment-264070500, I believe you may be encountering a similar issue.

**Comment by NotSoSuper** [comment]
Alright, thanks, I just ported my project to Python 3.6 (and other modules) and this was the only one that wasn't working.

**Comment by gunthercox** [comment]
Ok, so just to confirm, the solution from https://github.com/gunthercox/ChatterBot/issues/443#issuecomment-264070500 did correct your issue?

**Comment by NotSoSuper** [comment]
Correct, deleting the `utils` and `adapters` folders fixed the problem.
