### ISSUE TITLE
ImportError: No module named 'chatterbot.input'

### ISSUE THREAD

**Issue by sivasivacsc** [gunthercox/ChatterBot#534]
In example directory am trying to run the terminal_mongo_example.py but i got an a issue 

```
/usr/local/lib/python3.5/dist-packages/fuzzywuzzy/fuzz.py:35: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')
/usr/local/lib/python3.5/dist-packages/nltk/decorators.py:59: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  regargs, varargs, varkwargs, defaults = inspect.getargspec(func)
Traceback (most recent call last):
  File "terminal_mongo_example.py", line 20, in <module>
    database='chat'
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 37, in __init__
    self.validate_adapter_class(storage_adapter, StorageAdapter)
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 99, in validate_adapter_class
    if not issubclass(import_module(validate_class), Adapter):
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/utils/module_loading.py", line 12, in import_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'chatterbot.storage'

```

**Comment by vkosuri** [comment]
which version of chatterbot are you using? Use ``python -m chatterbot --version`` in your terminal to get version?

If still problem persists try to upgrade to latest chatterbot

``` Bash
pip install chatterbot --upgrade
```

**Comment by sivasivacsc** [comment]
Super Dude :+1:  you fixed issue 
i have one more doubt where i pass this parameter **i.e the database_uri and database_name**

**Comment by vkosuri** [comment]
I never tried, I think this link will help you https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/.

I am closing this issue, please feel to reopen if you have any issues.
