### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 98: invalid continuation byte

### ISSUE THREAD

**Issue by martmists** [gunthercox/ChatterBot#567]
```python
>>> b = ChatBot(
...     "my bot",
...     trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
...     logic_adapters=[
...         {
...          	"import_path": "chatterbot.logic.MathematicalEvaluation"
...	    },
... 	    {
...             "import_path": "chatterbot.logic.TimeLogicAdapter",
...         },
...         {
...             'import_path': 'chatterbot.logic.BestMatch'
...         },
...         {
...             'import_path': 'chatterbot.logic.LowConfidenceAdapter',
...             'threshold': 0.8,
...             'default_response': "Sorry, but I don't understand."
...         }
...     ]
... )
...

>>> b.train("chatterbot.corpus.english")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/trainers.py", line 117, in train
    trainer.train(pair)
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/trainers.py", line 82, in train
    statement = self.get_or_create(text)
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/trainers.py", line 25, in get_or_create
    statement = self.storage.find(statement_text)
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/storage/jsonfile.py", line 46, in find
    values = self.database.data(key=statement_text)
  File "/usr/local/lib/python3.5/dist-packages/jsondb/db.py", line 98, in data
    return self._get_content(key)
  File "/usr/local/lib/python3.5/dist-packages/jsondb/db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "/usr/local/lib/python3.5/dist-packages/jsondb/file_writer.py", line 13, in read_data
    content = db.read()
  File "/usr/lib/python3.5/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 98: invalid continuation byte
```

**Comment by martmists** [comment]
Indents may look a little messed up but I can assure you they are fine.

**Comment by vkosuri** [comment]
@martmists I guess you are mixing with both double quotes and single quotes, I think this will work
```Python
b = ChatBot(
    'my bot',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.MathematicalEvaluation'
        },
        {
            'import_path': 'chatterbot.logic.TimeLogicAdapter',
        },
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.8,
            'default_response': 'Sorry, but I don't understand.'
        }
    ]
)

```

**Comment by martmists** [comment]
How is that an issue? 
1. Python supports both
2. Yours doesn't work because of an unescaped `'`
3. The error pops up in `b.train`, so why would there be an error in ChatBot's `__init__`

**Comment by SunYunyun** [comment]
are you solution?

**Comment by vkosuri** [comment]
Thanks @martmists which version of chatter bot are you using, i have tried below example it is working fine.

```bash
(env)vkosuri:~/chatterbox/ChatterBot$ python -m chatterbot --version
0.5.3
```

``` Python
from chatterbot import ChatBot
b = ChatBot(
    'my bot',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer',
    logic_adapters=[
        {
            'import_path': 'chatterbot.logic.MathematicalEvaluation'
        },
        {
            'import_path': 'chatterbot.logic.TimeLogicAdapter',
        },
        {
            'import_path': 'chatterbot.logic.BestMatch'
        },
        {
            'import_path': 'chatterbot.logic.LowConfidenceAdapter',
            'threshold': 0.8,
            'default_response': 'Sorry, but I dont understand.'
        }
    ]
)
```

**Comment by martmists** [comment]
I'm using the latest from pypi. 
Again, the error IS NOT in the `__init__` for ChatBot, it's in the `b.train`

**Comment by martmists** [comment]
@gunthercox gonna wait for a response from you since I'm afraid this guy doesn't know English.

**Comment by gunthercox** [comment]
@martmists Do you have the unicode header at the top of your python file? `# -*- coding: utf-8 -*-`

**Comment by martmists** [comment]
No, does that matter on Windows when using `chcp 65001`?

**Comment by martmists** [comment]
just checked, adding that does NOT fix this. I also checked the windows 10 linux subsystem, and it results in the same error.

**Comment by martmists** [comment]
@gunthercox The problem seems to have fixed itself after deleting database.db, will investigate further.
