### ISSUE TITLE
Threading support to reply lots of people

### ISSUE THREAD

**Issue by lattice0** [gunthercox/ChatterBot#604]
I'm thinking about using ChatterBot to answer lots of people in a server. The messages are going to be received through NodeJS and passed to python through ZeroMQ. I'm thinking about the best strategy to process all messages, but I didn't see anything in the documentation. 

As I see, it'd be necessary for the ChatterBot object to be global, because we don't want more than one instance of the same logic adapter in memory, that's not necessary. I wonder which are the consequences of calling `chatbot.get_response(message)` in each thread. Is it enough?

I'd create like, 10 threads, where each one would wait for a socket message and then call a get_response. Do you think this would be enough? 

Are there risks of race condition? As I see, you implemented your own Queue, and the storage adapters may or may not suffer from race conditions. 

Would be nice to hear from you the best methods for this and if there'll be further work in the future to make it easier. Or even to add an example in `examples/` where threading is used.

**Comment by lucaszanella** [comment]
Here's the output when trying to call get_response inside a thread:

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "bot.py", line 13, in process_message
    response = chatbot.get_response("How are you?")
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 120, in get_response
    self.learn_response(statement, previous_statement)
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 159, in learn_response
    self.storage.update(statement)
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/storage/jsonfile.py", line 161, in update
    self.database.data(key=statement.text, value=data)
  File "/usr/local/lib/python3.5/dist-packages/jsondb/db.py", line 109, in data
    return self._get_content()
  File "/usr/local/lib/python3.5/dist-packages/jsondb/db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "/usr/local/lib/python3.5/dist-packages/jsondb/file_writer.py", line 15, in read_data
    obj = decode(content)
  File "/usr/local/lib/python3.5/dist-packages/jsondb/compat.py", line 32, in decode
    return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
  File "/usr/lib/python3.5/json/__init__.py", line 332, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 342, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

```

If you, however, set training to False, it works without any problems, so the problem is really something related to json storage and threading. I'm trying to understand where's the problem

**Comment by gunthercox** [comment]
The file database that ChatterBot uses by default isn't thread safe. It's the default because it doesn't require any databases to be installed locally so it is easy for people to get started and test out their chat bots. The error you are seeing is because multiple threads have attempted to read and write to the the same file at the same time and a write was not completed so the data was invalid.

**Comment by addelll** [comment]
how to resolve this probleme?

**Comment by monokal** [comment]
Use a supported database @addelll. A MongoDB storage adapter is documented here: http://chatterbot.readthedocs.io/en/stable/storage/

**Comment by gunthercox** [comment]
I'm going to close this issue off because it's been quite a while at this point.

If it helps anyone who comes across this in the future, I also recently put up an article that demonstrates how to use `celery` to asynchronously process tasks: https://chatterbot.us/2025/05/ai-scaling-costs/

Using celery and a task queue as noted would likely provide a large scaling capacity if one needed to generate responses to a large amount of inputs.
