### ISSUE TITLE
TypeError: object of type 'Statement' has no len()

### ISSUE THREAD

**Issue by rachit1994** [gunthercox/ChatterBot#612]
What am I doing wrong? I created a route to train the chatbot and a route to chat.
**main.py**:
```
from flask import Flask, render_template, request, jsonify
from initialSetup import ChatbotSetup
app = Flask(__name__)
@app.route("/")
def hello():
    return render_template('chat.html')
@app.route("/train")
def trainBot():
    return render_template('train.html')
@app.route("/ask", methods=['POST'])
def ask():
    message = str(request.form['messageText'])
    bot_response = str(Chatbot.getResponse(message))
    return jsonify({'status':'OK','answer':'bot_response'})
@app.route("/train", methods=['POST'])
def train():
    message = str(request.form['messageText'])
    Chatbot.train(message);
    return jsonify({'status':'OK','answer':'trained'})
if __name__ == "__main__":
    Chatbot = ChatbotSetup('test')
    import socket
    ip = [(s.connect(('8.8.8.8', 53)), s.getsockname()[0], s.close()) for s in [socket.socket(socket.AF_INET, socket.SOCK_DGRAM)]][0][1]
    app.run(host=ip,port=5000,debug=True)
```

**ChatbotSetup.py**:
```
from chatterbot import ChatBot
from chatterbot.comparisons import levenshtein_distance
from chatterbot.trainers import ListTrainer
class ChatbotSetup:
    def __init__(self,database = 'jarvii-database',**kwargs):
        self.chat = []
        self.Jarvii = ChatBot("English Bot",
        storage_adapter='chatterbot.storage.MongoDatabaseAdapter',
        filters=["chatterbot.filters.RepetitiveResponseFilter"],
        logic_adapters=[
            {
                'import_path': 'LogicAdapters.RemoveOffensiveWords',
                "response_selection_method": "chatterbot.comparisons.levenshtein_distance"
            },
            {
                'import_path': 'LogicAdapters.Greet',
                "response_selection_method": "chatterbot.comparisons.levenshtein_distance"
            },
            {
            "import_path": "chatterbot.logic.BestMatch",
            "response_selection_method": "chatterbot.comparisons.levenshtein_distance",
            "statement_comparison_function": "chatterbot.response_selection.get_first_response"
            },
            {
            "import_path": "chatterbot.logic.TimeLogicAdapter"
            },
            {
            "import_path":"chatterbot.logic.MathematicalEvaluation"
            },
            {
            'import_path': 'LogicAdapters.HandleMovies',
            "response_selection_method": "chatterbot.comparisons.levenshtein_distance"
            }   
            ],
        database = database,
        )     
    def getResponse(self,message):
        return str(self.Jarvii.get_response(message))
    def train(self,message):
        self.chat.append(message)
        self.Jarvii.set_trainer(ListTrainer)
        print('chat',self.chat)
        self.Jarvii.train(self.chat)
```

This is the error I am getting:

```Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/nitin/rachit/Bot/main.py", line 19, in ask
    bot_response = str(Chatbot.getResponse(message))
  File "/home/nitin/rachit/Bot/initialSetup/Chatbot.py", line 40, in getResponse
    return str(self.Jarvii.get_response(message))
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 114, in get_response
    statement, response, confidence = self.generate_response(input_statement, session_id)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 138, in generate_response
    confidence, response = self.logic.process(input_statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/logic/multi_adapter.py", line 37, in process
    confidence, output = adapter.process(statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/logic/best_match.py", line 54, in process
    closest_match = self.get(input_statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/logic/best_match.py", line 36, in get
    confidence = self.compare_statements(input_statement, statement)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/response_selection.py", line 50, in get_first_response
    len(response_list)
TypeError: object of type 'Statement' has no len()
```

**Comment by vkosuri** [comment]
By looking into your code, you have to change comparison function ``statement_comparison_function`` and statement functions ``response_selection_method`` something like below

``` Python
logic_adapters=[
            {
                'import_path': 'LogicAdapters.RemoveOffensiveWords',
                "response_selection_method": "chatterbot.comparisons.levenshtein_distance"
            },
            {
                'import_path': 'LogicAdapters.Greet',
                "response_selection_method": "chatterbot.comparisons.levenshtein_distance"
            },
            {
            "import_path": "chatterbot.logic.BestMatch",
            "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance",
            "response_selection_method": "chatterbot.response_selection.get_first_response"
            },
            {
            "import_path": "chatterbot.logic.TimeLogicAdapter"
            },
            {
            "import_path":"chatterbot.logic.MathematicalEvaluation"
            },
            {
            'import_path': 'LogicAdapters.HandleMovies',
            "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance"
            }   
```

Documentation should also be update here http://chatterbot.readthedocs.io/en/stable/logic/index.html#setting-parameters

**Comment by rachit1994** [comment]
still the same error. However when i remove all the 'response_selection_method' and 'statement_comparison_function' things work fine

**Comment by vkosuri** [comment]
which version chatterbot are you using?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: rachit1994Sent: Tuesday 31 January 2017 12:18To: gunthercox/ChatterBotReply To: gunthercox/ChatterBotCc: Mallikarjunarao Kosuri; CommentSubject: Re: [gunthercox/ChatterBot] TypeError: object of type 'Statement' has no len() (#612)still the same error. However when i remove all the 'response_selection_method' and 'statement_comparison_function' things work fine

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gunthercox/ChatterBot","title":"gunthercox/ChatterBot","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/gunthercox/ChatterBot"}},"updates":{"snippets":[{"icon":"PERSON","message":"@rachit1994 in #612: still the same error. However when i remove all the 'response_selection_method' and 'statement_comparison_function' things work fine"}],"action":{"name":"View Issue","url":"https://github.com/gunthercox/ChatterBot/issues/612#issuecomment-276287988"}}}

**Comment by rachit1994** [comment]
>>> chatterbot.__version__
'0.5.5'

**Comment by vkosuri** [comment]
Thanks @rachit1994, My guess was you are trying combine many things, could you please try to add one after another logic adapters, still observing same issue let me know.

```Python
logic_adapters=[
    {
        'import_path': 'LogicAdapters.RemoveOffensiveWords',
        "statement_comparison_function": "chatterbot.comparisons.levenshtein_distance"
    }
]

**Comment by sanjaykhanal** [comment]
I was also having similar problem a while ago. try modifying you code as below. so far my problem was solved doing this.

def getResponse(self,message):
        return str(self.Jarvii.get_response(str(message)))
