### ISSUE TITLE
Cannot initialize Spanish Chatbot

### ISSUE THREAD

**Issue by KonradKlimczak** [gunthercox/ChatterBot#627]
Hello, whenever I try to initialize ChatterBot using Spanish corpus I got UnicodeDecodeError.
My file:

```
# -*- coding: utf-8 -*-

from chatterbot import ChatBot

chatbot = ChatBot(
    'Bob',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)

chatbot.train('chatterbot.corpus.spanish')

chatbot.get_response('Hola')
```

Traceback:
```
Traceback (most recent call last):
  File "d:\workspace\chatterbot_playground\chatterbot_instance.py", line 10, in <module>
    chatbot.train('chatterbot.corpus.spanish')
  File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 117, in train
    trainer.train(pair)
  File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 82, in train
    statement = self.get_or_create(text)
  File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 25, in get_or_create
    statement = self.storage.find(statement_text)
  File "C:\Python27\lib\site-packages\chatterbot\storage\jsonfile.py", line 42, in find
    values = self.database.data(key=statement_text)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 98, in data
    return self._get_content(key)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "C:\Python27\lib\site-packages\jsondb\file_writer.py", line 15, in read_data
    obj = decode(content)
  File "C:\Python27\lib\site-packages\jsondb\compat.py", line 32, in decode
    return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
  File "C:\Python27\lib\json\__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xed in position 8: invalid continuation byte
```

I am using Python 2.7.11 on Windows 8.1 64-bit.
Any idea how can I solve this issue?

**Comment by vkosuri** [comment]
Python2.7 are having Unicode issues when you are using existing ``database.db``, Try to remove existing ``database.db`` retrain your bot, let me know still you are facing issue.

**Comment by KonradKlimczak** [comment]
I have deleted old database.db file, but I still receive the same error.
When I open new database.db file I can see that is has some encoding problems: 

```
{"Buenos d�as, �c�mo est�s?": {"created_at": {"$date": 1486980434813}, "extra_data": {}, "in_response_to": []}}
```

**Comment by vkosuri** [comment]
As per my understanding Python 2.7 not good for unicode, could you please try it on Python3.x, and let me know your observations

**Comment by vkosuri** [comment]
https://github.com/gunthercox/ChatterBot/blob/021a808a71cd390ab33d127ae8c3f4b4f6c83b1d/docs/quickstart.rst

**Comment by vkosuri** [comment]
@KonradKlimczak did your problem is resolved?

**Comment by f3tejada** [comment]
Same problem here. I installed python 3.6 but it didn't work.

**Comment by f3tejada** [comment]
I tried with: 
`chatbot.set_trainer(ListTrainer)
chatbot.train([
   "árbol",
   "te gustan los árboles?",
])`

And it returns:

`Warning (from warnings module):
  File "C:\Python27\lib\site-packages\chatterbot\storage\jsonfile.py", line 26
    self.UnsuitableForProductionWarning
UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.

Traceback (most recent call last):
  File "C:\Users\Comercial 01\Google Drive\Python\Chat Troubleshooting\AI Python\Chatterbot\QuickStart y Tutorial\tutorial.py", line 41, in <module>
    "chao",
  File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 90, in train
    self.storage.update(statement)
  File "C:\Python27\lib\site-packages\chatterbot\storage\jsonfile.py", line 161, in update
    self.database.data(key=statement.text, value=data)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 102, in data
    self._set_content(key, value)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 66, in _set_content
    self.write_data(self.path, obj)
  File "C:\Python27\lib\site-packages\jsondb\file_writer.py", line 26, in write_data
    db.write(encode(obj))
  File "C:\Python27\lib\site-packages\jsondb\compat.py", line 25, in encode
    return unicode(value)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 2: ordinal not in range(128)`

Tildes are not working.

Im using python 27 (and 36) on windows 8 64bit. At the begining of the code I put # -*- coding: utf-8 -*-

**Comment by vkosuri** [comment]
Use Python 3to resolve this issue, let me know if you need any help

**Comment by KonradKlimczak** [comment]
Works with Python 3.6.0 on Windows 10 64bit.
