### ISSUE TITLE
Compressed file ended before the end-of-stream

### ISSUE THREAD

**Issue by TernTuring** [gunthercox/ChatterBot#631]
Extracting dialogs/8/4259.tsv
Extracting dialogs/8/42590.tsv
Traceback (most recent call last):
  File "ubuntu_corpus_training_example.py", line 19, in <module>
    chatbot.train()
  File "/usr/lib64/python3.4/site-packages/chatterbot/trainers.py", line 320, in train
    self.extract(corpus_download_path)
  File "/usr/lib64/python3.4/site-packages/chatterbot/trainers.py", line 306, in extract
    tar.extractall(path=self.data_directory, members=track_progress(tar))
  File "/usr/lib64/python3.4/tarfile.py", line 1986, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir())
  File "/usr/lib64/python3.4/tarfile.py", line 2025, in extract
    set_attrs=set_attrs)
  File "/usr/lib64/python3.4/tarfile.py", line 2094, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib64/python3.4/tarfile.py", line 2140, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)
  File "/usr/lib64/python3.4/tarfile.py", line 247, in copyfileobj
    buf = src.read(remainder)
  File "/usr/lib64/python3.4/gzip.py", line 365, in read
    if not self._read(readsize):
  File "/usr/lib64/python3.4/gzip.py", line 449, in _read
    self._read_eof()
  File "/usr/lib64/python3.4/gzip.py", line 482, in _read_eof
    crc32, isize = struct.unpack("<II", self._read_exact(8))
  File "/usr/lib64/python3.4/gzip.py", line 286, in _read_exact
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

**Comment by gunthercox** [comment]
This may have been a one time error due to a network issue. I've tested the training process locally (with the latest 0.7.0 version of ChatterBot and I can't recreate this issue.
