### ISSUE TITLE
ImportError: cannot import name Api

### ISSUE THREAD

**Issue by TernTuring** [gunthercox/ChatterBot#632]
/usr/local/lib/python2.7/site-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "twitter.py", line 36, in <module>
    trainer="chatterbot.trainers.TwitterTrainer"
  File "/usr/local/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 71, in __init__
    self.trainer = TrainerClass(self.storage, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/chatterbot/trainers.py", line 131, in __init__
    from twitter import Api as TwitterApi
  File "/Users/aiosdeveloper/Downloads/chatbot/twitter.py", line 36, in <module>
    trainer="chatterbot.trainers.TwitterTrainer"
  File "/usr/local/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 71, in __init__
    self.trainer = TrainerClass(self.storage, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/chatterbot/trainers.py", line 131, in __init__
    from twitter import Api as TwitterApi
ImportError: cannot import name Api

Thanks!

**Comment by vkosuri** [comment]
Try to do fallowing steps, Recommended use [virtual environments ](http://docs.python-guide.org/en/latest/dev/virtualenvs/)

```
virtualvenv venv
source venv/bin/activate
pip install --upgrade pip
pip install chatterbot
```

Let me know still if you are facing this issue.

**Comment by TernTuring** [comment]
python twitter.py 
/opt/chatbot/mengbao/venv/lib/python3.4/site-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "twitter.py", line 36, in <module>
    trainer="chatterbot.trainers.TwitterTrainer"
  File "/opt/chatbot/mengbao/venv/lib/python3.4/site-packages/chatterbot/chatterbot.py", line 71, in __init__
    self.trainer = TrainerClass(self.storage, **kwargs)
  File "/opt/chatbot/mengbao/venv/lib/python3.4/site-packages/chatterbot/trainers.py", line 131, in __init__
    from twitter import Api as TwitterApi
  File "/opt/chatbot/mengbao/twitter.py", line 36, in <module>
    trainer="chatterbot.trainers.TwitterTrainer"
  File "/opt/chatbot/mengbao/venv/lib/python3.4/site-packages/chatterbot/chatterbot.py", line 71, in __init__
    self.trainer = TrainerClass(self.storage, **kwargs)
  File "/opt/chatbot/mengbao/venv/lib/python3.4/site-packages/chatterbot/trainers.py", line 131, in __init__
    from twitter import Api as TwitterApi
ImportError: cannot import name 'Api'

**Comment by vkosuri** [comment]
Read the documentation https://pypi.python.org/pypi/twitter/1.17.1

**Comment by gunthercox** [comment]
@TernTuring Make sure that you have the correct requirements installed. There are several Python twitter libraries available, some of them can have conflicting package names if both are installed on the same system. Check the `requirements.txt` file for the exact packages and versions that ChatterBot uses. Let me know if you have any questions.
