### ISSUE TITLE
Can't initialize ChatBot

### ISSUE THREAD

**Issue by StDogbert** [gunthercox/ChatterBot#634]
Hi!

I am trying to initialize chatbot using python 2.7.10

`# -*- coding: utf-8 -*-

from chatterbot import ChatBot

bot = ChatBot("Ron Obvious")`

And get this error:

/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "<user path>/Chatterbot/Test.py", line 7, in <module>
    bot = ChatBot("Ron Obvious")
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 83, in __init__
    self.initialize()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 93, in initialize
    nltk_download_corpus('corpora/wordnet')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/chatterbot/utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/data.py", line 635, in find
    return find(modified_name, paths)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/data.py", line 621, in find
    return ZipFilePathPointer(p, zipentry)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/data.py", line 470, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/nltk/data.py", line 986, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

Any ideas what am I doing wrong?

**Comment by priyanka22kar** [comment]
me too facing the same issue!!!

**Comment by StDogbert** [comment]
Did the same from other mac and it worked. It worked from windows too. Tried to uninstall and reinstall all dependencies and chatterbot itself - same problem. I have no idea what to try next...

**Comment by StDogbert** [comment]
Somehow corpora/wordnet archive was corrupted during first loading and as download step was skipped every time cause archive was already there I got this error. Deleted archive and next time it was redownloaded succesfully.

**Comment by yumupinglan** [comment]
how to delete archive ?
