### ISSUE TITLE
Not able to import the chatbot package please help!

### ISSUE THREAD

**Issue by priyanka22kar** [gunthercox/ChatterBot#637]
me too facing the same issue!!!

File "C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo.py", line 8, in 
from chatterbot import ChatBot

File "chatterbot.py", line 7, in

ImportError: cannot import name ChatBot

and yes I don't have any directories named utils and adapters checked that approach too!!
please help.

![image](https://cloud.githubusercontent.com/assets/26005427/23350198/ede4a7da-fcde-11e6-879a-7f09cdd5c4bb.png)
![image](https://cloud.githubusercontent.com/assets/26005427/23350215/17adda82-fcdf-11e6-9dbd-a8751a660f6c.png)

I am using anaconda 2 for python 2.7.
your help would be really appreciated 
Thank You.

**Comment by vkosuri** [comment]
@priyanka22kar did you tried same example on ``Python2.7``, 

Which version of chatterbot are you using, to get chatterbot version ``python -m chatterbot --version``

**Comment by priyanka22kar** [comment]
![image](https://cloud.githubusercontent.com/assets/26005427/23350645/fc8ace38-fce1-11e6-94c0-2ff87493a3d5.png)

**Comment by vkosuri** [comment]
could you provide error stack trace for python2.7

**Comment by priyanka22kar** [comment]
I 
![image](https://cloud.githubusercontent.com/assets/26005427/23350891/be98970c-fce3-11e6-9685-c17bb85e633b.png)

**Comment by vkosuri** [comment]
My guess could issue with your python path. http://stackoverflow.com/questions/33549546/python-path-issue

Add these steps at startup to know where your path is setted.

``` Python
print sys.path
```

**Comment by priyanka22kar** [comment]
![image](https://cloud.githubusercontent.com/assets/26005427/23351551/e040ed88-fce7-11e6-9e1c-92ee112c2379.png)

**Comment by vkosuri** [comment]
I am not sure what happening, In a general process what i am doing on a new windows machine

```
pip install --upgrade pip
pip install chatterbot
python -m chatterbot --version
```

I am not familer with Anaconda, By looking into [setup.py](https://github.com/gunthercox/ChatterBot/blob/master/setup.py#L60) it supports only python.

**It is not recommended,** you may try to 

``` 
pip uninstall chatterbot
pip install chatterbot
python -m chatterbot --version
```

Still if problem persists try to remove python2 and install a fresh copy do above steps. I hope this will help you.

**Comment by priyanka22kar** [comment]
Sir I tried your suggestion
Still not working

**Comment by priyanka22kar** [comment]
its working fine with python 3.5
but  over here i am tring to execute the twitter data training example its showing an error
![image](https://cloud.githubusercontent.com/assets/26005427/23356236/1ce97d2e-fcff-11e6-8dfe-b3246d17a63d.png)
can you explain how to resolve it? and further more after training the twitter data to the bot 
will the bot be able to fetch the answers from twitter for a given question or how is this example useful? 
Thank You

**Comment by vkosuri** [comment]
Here is an example located here http://chatterbot.readthedocs.io/en/stable/training.html#twitter-training-example

**Comment by priyanka22kar** [comment]
it stopped executing in python 3.5 too
 
![image](https://cloud.githubusercontent.com/assets/26005427/23361868/d1649ca2-fd18-11e6-84fe-c6565669b360.png)

**Comment by gunthercox** [comment]
@priyanka22kar Based on your output it looks like you are using Anaconda and an iPython notebook. I haven't tested ChatterBot heavily under these environments but I am aware of a few reports of developers encountering issues when attempting to use ChatterBot in an iPython notebook.

ChatterBot has been developed and is heavily tested under the normal Python installation, Anaconda and iPython are a bit new to me but I would be happy to install them locally to try to see if I can replicate and fix) the same issue that you are encountering.

**Comment by priyanka22kar** [comment]
@gunthercox  That would be really helpful 
Thank You

**Comment by priyanka22kar** [comment]
I re-installed everything 
now previous error isn't displaying 
but when i am trying to run the gitter bot example is gives me error

This is how the simple example is working :
![image](https://cloud.githubusercontent.com/assets/26005427/23401389/86a95738-fdcd-11e6-98d7-220a0dd45d6b.png)

This is the new error i am facing 
![image](https://cloud.githubusercontent.com/assets/26005427/23401426/a61b5a3a-fdcd-11e6-9ed0-8873c29e0006.png)

please Kindly help !! Your help will be really appreciated!!!
@gunthercox @vkosuri 

Thank You.

**Comment by vkosuri** [comment]
@priyanka22kar I assume the settings is from ``Django``, You can rewrite like this, replace with your gitter ``room_id`` and ``api_key``


```Python
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
import logging

logging.basicConfig(level=logging.INFO)

chatbot = ChatBot(
    'GitterBot',
    gitter_room="YOUR_GITTER_ROOM_ID",
    gitter_api_token="YOUR_GITTER_API_TOKEN",
    gitter_only_respond_to_mentions=False,
    input_adapter='chatterbot.input.Gitter',
    output_adapter='chatterbot.output.Gitter',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)
```

**Comment by priyanka22kar** [comment]
@vkosuri 
The code executes but throws an error:


runfile('C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_gitter_demo.py', wdir='C:/Users/Priyanka Baviskar/Documents/py_2')
C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\storage\jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.gitter.im
INFO:chatterbot.adapters:401 joining room https://api.gitter.im/v1/rooms
Traceback (most recent call last):

  File "<ipython-input-23-983eb2bfb276>", line 1, in <module>
    runfile('C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_gitter_demo.py', wdir='C:/Users/Priyanka Baviskar/Documents/py_2')

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_gitter_demo.py", line 19, in <module>
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\chatterbot.py", line 38, in __init__
    self.input = utils.initialize_class(input_adapter, **kwargs)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\input\gitter.py", line 31, in __init__
    room_data = self.join_room(self.gitter_room)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\input\gitter.py", line 58, in join_room
    self._validate_status_code(response)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\input\gitter.py", line 41, in _validate_status_code
    raise self.HTTPStatusException('{} status code recieved'.format(code))

HTTPStatusException: '401 status code recieved'

**Comment by vkosuri** [comment]
401 represent unauthorized, check with api and room id

**Comment by vkosuri** [comment]
401 represent unauthorized, check with api and room id

**Comment by priyanka22kar** [comment]
@vkosuri  Sir I have 2 Queries:
[1]
When I created an app using gitter 
I received:
TOKEN	
OAUTH KEY	
OAUTH SECRET	
REDIRECT URL	

So I applied it in the code as follows:
![image](https://cloud.githubusercontent.com/assets/26005427/23403106/9c2f2eaa-fdd4-11e6-8ade-5aea00d64c8c.png)


And when executed got the following error:
runfile('C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_gitter_demo.py', wdir='C:/Users/Priyanka Baviskar/Documents/py_2')
C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\storage\jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
INFO:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): api.gitter.im
INFO:chatterbot.adapters:404 joining room https://api.gitter.im/v1/rooms
Traceback (most recent call last):

  File "<ipython-input-25-983eb2bfb276>", line 1, in <module>
    runfile('C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_gitter_demo.py', wdir='C:/Users/Priyanka Baviskar/Documents/py_2')

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_gitter_demo.py", line 19, in <module>
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\chatterbot.py", line 38, in __init__
    self.input = utils.initialize_class(input_adapter, **kwargs)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\input\gitter.py", line 31, in __init__
    room_data = self.join_room(self.gitter_room)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\input\gitter.py", line 58, in join_room
    self._validate_status_code(response)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\input\gitter.py", line 41, in _validate_status_code
    raise self.HTTPStatusException('{} status code recieved'.format(code))

HTTPStatusException: '404 status code recieved'

[2]
In the example to train the classifier with the ubuntu corpus:
the corpus is downloaded but while extracting:
![image](https://cloud.githubusercontent.com/assets/26005427/23403280/738bf2d4-fdd5-11e6-961e-c6fd7aaebab8.png)
it extracts till here and then throws the error:

Traceback (most recent call last):

  File "<ipython-input-26-d9c17baf69d4>", line 1, in <module>
    runfile('C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_ubuntu_corpus.py', wdir='C:/Users/Priyanka Baviskar/Documents/py_2')

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Priyanka Baviskar/Documents/py_2/chatbot_demo_ubuntu_corpus.py", line 26, in <module>
    chatbot.train()

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\trainers.py", line 320, in train
    self.extract(corpus_download_path)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\site-packages\chatterbot\trainers.py", line 306, in extract
    tar.extractall(path=self.data_directory, members=track_progress(tar))

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\tarfile.py", line 1996, in extractall
    numeric_owner=numeric_owner)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\tarfile.py", line 2038, in extract
    numeric_owner=numeric_owner)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\tarfile.py", line 2108, in _extract_member
    self.makefile(tarinfo, targetpath)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\tarfile.py", line 2156, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\tarfile.py", line 247, in copyfileobj
    buf = src.read(remainder)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\gzip.py", line 274, in read
    return self._buffer.read(size)

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\_compression.py", line 68, in readinto
    data = self.read(len(byte_view))

  File "C:\Users\Priyanka Baviskar\Anaconda_\lib\gzip.py", line 480, in read
    raise EOFError("Compressed file ended before the "

EOFError: Compressed file ended before the end-of-stream marker was reached

Thank You for answering all my queries with patience .Much appreciated Sir

**Comment by vkosuri** [comment]
On Gitter see some example over here https://github.com/gunthercox/ChatterBot/blob/master/tests/input_adapter_tests/test_gitter_input_adapter.py#L23

I am not sure with Ubuntu corpus issues

**Comment by priyanka22kar** [comment]
Can I edit the Corpus ?
add more conversations directly into the json file ?

**Comment by gunthercox** [comment]
You can certainly edit the corpus files. The Ubuntu dialog corpus is a separate project but ChatterBot has a smaller built in corpus in the `corpus/data` directory.

**Comment by priyanka22kar** [comment]
One last doubt @gunthercox  
when we download the The Ubuntu dialog corpus via the program were does it get stored ?
Because it isn't extracting the whole data for me its throwing error.

**Comment by gunthercox** [comment]
The Ubuntu dialog corpus should be downloaded to the same directory that
your Python code is being executed from. I test out the download process as
soon as I can. It is possible that some change has been made since I wrote
the download code.

**Comment by gunthercox** [comment]
@priyanka22kar Yes, you can edit the corpus by editing the json file.
