### ISSUE TITLE
ImportError: no module named 'chatterbot.ext' on own app

### ISSUE THREAD

**Issue by jbmlaird** [gunthercox/ChatterBot#640]
When I run the sample Django Chatterbot app, it runs fine but not when I run my own project. I have tried `pip install chatterbot --upgrade`.

Stack trace:

```
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "g:\Python\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "g:\Python\lib\site-packages\django\core\management\__init__.py", line 341, in execute
    django.setup()
  File "g:\Python\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "g:\Python\lib\site-packages\django\apps\registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "g:\Python\lib\site-packages\django\apps\config.py", line 116, in create
    mod = import_module(mod_path)
  File "g:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'chatterbot.ext'
```

My **settings.py**:

```
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'chatterbot.ext.django_chatterbot',
]
```

My **urls.py**:

```
from django.conf.urls import url, include
from django.contrib import admin
from chatterbot.ext.django_chatterbot import urls as chatterbot_urls

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chatterbot/', include(chatterbot_urls, namespace='chatterbot')),
]
```

Ctrl+clicking on chatterbot.ext.django_chatterbot displays the correct file!

**Comment by jbmlaird** [comment]
I'm not entirely sure what fixed it but after creating another app and including it before chatterbot, it migrated fine.
