### ISSUE TITLE
OperationFailure: not authorized on chatterbot-database to execute command { createIndexes: "statements", indexes: [ { key: { text: 1 }, unique: true, name: "text_1" } ] }

### ISSUE THREAD

**Issue by jbmlaird** [gunthercox/ChatterBot#642]
Upon trying to run my app locally I get the above error that occurs on the database_uri line.

```
# Create a new instance of a ChatBot
bot = ChatBot("Terminal",
              storage_adapter="chatterbot.storage.MongoDatabaseAdapter",
              logic_adapters=[
                  "chatterbot.logic.MathematicalEvaluation",
                  "chatterbot.logic.TimeLogicAdapter",
                  "chatterbot.logic.BestMatch"
              ],
              input_adapter="chatterbot.input.VariableInputTypeAdapter",
              output_adapter="chatterbot.output.OutputAdapter",
              output_format='text',
              database_uri="mongodb://heroku_address:password@ds1234567.mlab.com:12345/heroku_address"
              )
```

Full stack trace:

```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x04BC6198>
Traceback (most recent call last):
  File "g:\Python\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "g:\Python\lib\site-packages\django\core\management\commands\runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "g:\Python\lib\site-packages\django\core\management\base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "g:\Python\lib\site-packages\django\core\management\base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "g:\Python\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "g:\Python\lib\site-packages\django\core\checks\urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "g:\Python\lib\site-packages\django\core\checks\urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "g:\Python\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "g:\Python\lib\site-packages\django\urls\resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "g:\Python\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "g:\Python\lib\site-packages\django\urls\resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "g:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "g:\Git\ChatterbotTest\chatterbottest\urls.py", line 22, in <module>
    url(r'^myapp/', include('myapp.urls')),
  File "g:\Python\lib\site-packages\django\conf\urls\__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "g:\Python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "g:\Git\ChatterbotTest\myapp\urls.py", line 3, in <module>
    from myapp.views import MyApp
  File "g:\Git\ChatterbotTest\myapp\views.py", line 29, in <module>
    database_uri="mongodb://heroku_24sw30n9:bla8gdmaukpnmdau20e3aaeaba@ds113938.mlab.com:13938/heroku_24sw30n9"
  File "g:\Python\lib\site-packages\chatterbot\chatterbot.py", line 37, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "g:\Python\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "g:\Python\lib\site-packages\chatterbot\storage\mongodb.py", line 102, in __init__
    self.statements.create_index('text', unique=True)
  File "g:\Python\lib\site-packages\pymongo\collection.py", line 1529, in create_index
    self.__create_index(keys, kwargs)
  File "g:\Python\lib\site-packages\pymongo\collection.py", line 1430, in __create_index
    parse_write_concern_error=True)
  File "g:\Python\lib\site-packages\pymongo\collection.py", line 232, in _command
    collation=collation)
  File "g:\Python\lib\site-packages\pymongo\pool.py", line 419, in command
    collation=collation)
  File "g:\Python\lib\site-packages\pymongo\network.py", line 116, in command
    parse_write_concern_error=parse_write_concern_error)
  File "g:\Python\lib\site-packages\pymongo\helpers.py", line 210, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: not authorized on chatterbot-database to execute command { createIndexes: "statements", indexes: [ { key: { text: 1 }, unique: true, name: "text_1" } ] }
```

Interestingly, I connected to the database using the command line and ran the above command and got a success message returned. Running the app still causes this error, however.

Is this an error with mLab?

**Comment by gunthercox** [comment]
Hi @jbmlaird, this isn't an issue I have encountered before. To me it looks like an authentication issue with the server hosting your database.
