### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'database.db'

### ISSUE THREAD

**Issue by Parveen-Thind** [gunthercox/ChatterBot#650]
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    c = ChatBot('Ron Obvious')
  File "C:\Users\Hp W8.1 ori\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\chatterbot.py", line 37, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\Hp W8.1 ori\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "C:\Users\Hp W8.1 ori\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\storage\jsonfile.py", line 30, in __init__
    self.database = Database(database_path)
  File "C:\Users\Hp W8.1 ori\AppData\Local\Programs\Python\Python35\lib\site-packages\jsondb\db.py", line 22, in __init__
    self.set_path(file_path)
  File "C:\Users\Hp W8.1 ori\AppData\Local\Programs\Python\Python35\lib\site-packages\jsondb\db.py", line 47, in set_path
    self.write_data(file_path, {})
  File "C:\Users\Hp W8.1 ori\AppData\Local\Programs\Python\Python35\lib\site-packages\jsondb\file_writer.py", line 25, in write_data
    with open_file_for_writing(path) as db:
  File "C:\Users\Hp W8.1 ori\AppData\Local\Programs\Python\Python35\lib\site-packages\jsondb\compat.py", line 70, in open_file_for_writing
    return io.open(*args, **kwargs)
PermissionError: [Errno 13] Permission denied: 'database.db'

**Comment by vkosuri** [comment]
@Parveen-Thind could you please describe your prblem detail? For more information please look here http://stackoverflow.com/questions/23870808/oserror-errno-13-permission-denied

**Comment by Parveen-Thind** [comment]
from chatterbot import ChatBot
chatbot  = ChatBot('Ron Obvious') 
 # this code gives me above errors . I am not being able remove it.

**Comment by vkosuri** [comment]
I think you are trying to work on chatterbot examples folder, try to run it somewhere you have privileges to create or delete files from your python script.
