### ISSUE TITLE
NLTK error during chatterbot setup

### ISSUE THREAD

**Issue by nony05** [gunthercox/ChatterBot#662]
When i initialize a chatterbot  like this 
Install chatterbot using  `pip install django chatterbot`, then add `chatterbot.ext.django_chatterbot` in Installed apps and then run `./manage.py runserver`

shows Error
```
Unhandled exception in thread started by <function wrapper at 0x7f5f7ea17410>
Traceback (most recent call last):
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 121, in inner_run
    self.check(display_num_errors=True)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 374, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/core/management/base.py", line 361, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/core/checks/registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    for pattern in resolver.url_patterns:
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 313, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/utils/functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/urls/resolvers.py", line 306, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tapish/noransoft/chatbot/chatbot/urls.py", line 21, in <module>
    url(r'^chatterbot/', include('chatterbot.ext.django_chatterbot.urls', namespace='chatterbot')),
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/django/conf/urls/__init__.py", line 50, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/urls.py", line 3, in <module>
    from .views import ChatterBotView
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/views.py", line 8, in <module>
    class ChatterBotViewMixin(object):
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/chatterbot/ext/django_chatterbot/views.py", line 13, in ChatterBotViewMixin
    chatterbot = ChatBot(**settings.CHATTERBOT)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 83, in __init__
    self.initialize()
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/chatterbot/chatterbot.py", line 94, in initialize
    nltk_download_corpus('tokenizers/punkt')
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/chatterbot/utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/nltk/data.py", line 635, in find
    return find(modified_name, paths)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/nltk/data.py", line 621, in find
    return ZipFilePathPointer(p, zipentry)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/nltk/data.py", line 470, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/home/tapish/noransoft/chatbot/venv/local/lib/python2.7/site-packages/nltk/data.py", line 986, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file
```

**Comment by gunthercox** [comment]
@nony05 Sorry about the late response. If you are still encountering this issue, based on the error you are receiving (`zipfile.BadZipfile: File is not a zip file`) it appears that there is an issue with your NLTK data files. 

Is there any chance that you downloaded the NLTK data files manually?

**Comment by vkosuri** [comment]
@nony05 did you tried manually download the files? And also try to upgrade chatterbot to latest version  ``pip install --upgrade chatterbot``

**Comment by gunthercox** [comment]
I'm going to close this issue due to lack of activity.
