### ISSUE TITLE
Errors when running the basic example

### ISSUE THREAD

**Issue by 6d6366726c** [gunthercox/ChatterBot#672]
Hey folks,
I pip installed chatterbot to a new virtualenv, but having trouble running the first basic example here: 
https://chatterbot.readthedocs.io/en/stable/examples.html

I can see from a search on previous issues that UnsuitableForProductionWarning is an alert only so can be ignored, but the rest of the errors have me stumped.

Help please!

`/Library/Python/2.7/site-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "Basic.py", line 4, in <module>
    chatbot = ChatBot('Charlie')
  File "/Library/Python/2.7/site-packages/chatterbot/chatterbot.py", line 83, in __init__
    self.initialize()
  File "/Library/Python/2.7/site-packages/chatterbot/chatterbot.py", line 94, in initialize
    nltk_download_corpus('tokenizers/punkt')
  File "/Library/Python/2.7/site-packages/chatterbot/utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "/Library/Python/2.7/site-packages/nltk/data.py", line 635, in find
    return find(modified_name, paths)
  File "/Library/Python/2.7/site-packages/nltk/data.py", line 621, in find
    return ZipFilePathPointer(p, zipentry)
  File "/Library/Python/2.7/site-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/nltk/data.py", line 470, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/Library/Python/2.7/site-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/nltk/data.py", line 986, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file`

**Comment by yumupinglan** [comment]
I also have this problem on python3.5.

`C:\Program Files\Python 3.5\lib\site-packages\chatterbot\storage\jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python 3.5\lib\site-packages\chatterbot\chatterbot.py", line 83, in __init__
    self.initialize()
  File "C:\Program Files\Python 3.5\lib\site-packages\chatterbot\chatterbot.py", line 93, in initialize
    nltk_download_corpus('corpora/wordnet')
  File "C:\Program Files\Python 3.5\lib\site-packages\chatterbot\utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "C:\Program Files\Python 3.5\lib\site-packages\nltk\data.py", line 635, in find
    return find(modified_name, paths)
  File "C:\Program Files\Python 3.5\lib\site-packages\nltk\data.py", line 621, in find
    return ZipFilePathPointer(p, zipentry)
  File "C:\Program Files\Python 3.5\lib\site-packages\nltk\compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Program Files\Python 3.5\lib\site-packages\nltk\data.py", line 470, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "C:\Program Files\Python 3.5\lib\site-packages\nltk\compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Program Files\Python 3.5\lib\site-packages\nltk\data.py", line 986, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "C:\Program Files\Python 3.5\lib\zipfile.py", line 1023, in __init__
    self._RealGetContents()
  File "C:\Program Files\Python 3.5\lib\zipfile.py", line 1090, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

**Comment by vkosuri** [comment]
similar issue see https://github.com/gunthercox/ChatterBot/issues/662#issuecomment-289863176

**Comment by 6d6366726c** [comment]
I didn't download NLTK manually. Any ideas on how to resolve?

**Comment by gunthercox** [comment]
@6d6366726c If you haven't already done so, I would recommend making sure that you have the latest version of NLTK installed. To do this you can run:

```
pip install nltk --upgrade
```

This error is very likely occurring due to an issue with one ore more of the NLTK data files. These files are not downloaded with the NLTK python package and have to be downloaded separately. Typically ChatterBot will attempt to trigger the download of these files if they cannot be found locally. I'm wondering if the download partially failed and resulted in incomplete or damaged data files. If you can find the default NLTK download location on your computer you should be able to delete them so the they get re-downloaded by ChatterBot the next time you run your program.

**Comment by yumupinglan** [comment]
download NLTK manually, and the issue resolved. @vkosuri thank you vary much!

**Comment by vkosuri** [comment]
@yumupinglan Thanks Master @gunthercox
