### ISSUE TITLE
UnicodeDecodeError:  avec la commande-->  response = self.bot.get_response(u"stève")

### ISSUE THREAD

**Issue by steveh110** [gunthercox/ChatterBot#719]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "E:\inmoovPY\inmoov\soft\chat.py", line 68, in run
    response = self.bot.get_response(u"stÃ¨ve")
  File "C:\Python27\lib\site-packages\chatterbot\chatterbot.py", line 108, in get_response
    input_statement = self.input.process_input_statement(input_item)
  File "C:\Python27\lib\site-packages\chatterbot\input\input_adapter.py", line 24, in process_input_statement
    existing_statement = self.chatbot.storage.find(input_statement.text)
  File "C:\Python27\lib\site-packages\chatterbot\storage\jsonfile.py", line 42, in find
    values = self.database.data(key=statement_text)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 98, in data
    return self._get_content(key)
  File "C:\Python27\lib\site-packages\jsondb\db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "C:\Python27\lib\site-packages\jsondb\file_writer.py", line 15, in read_data
    obj = decode(content)
  File "C:\Python27\lib\site-packages\jsondb\compat.py", line 32, in decode
    return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
  File "C:\Python27\lib\json\__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "C:\Python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python27\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe8 in position 2: invalid continuation byte

**Comment by gunthercox** [comment]
I was unable to recreate this issue using the latest version of ChatterBot. There is additional information [in the documentation](http://chatterbot.readthedocs.io/en/stable/encoding.html) on how to solve various common unicode errors in Python.

Feel free to reopen this issue if you are still encountering the error.
