### ISSUE TITLE
JSONDecodeError 

### ISSUE THREAD

**Issue by addelll** [gunthercox/ChatterBot#729]
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer

chatterbot = ChatBot("Training Example")
chatterbot.set_trainer(ChatterBotCorpusTrainer)

chatterbot.train("./greetings.corpus.json")

> I used same corpus file but when i deploy to heroku with python 3.6.1 i have this error :`

2017-05-11T10:19:31.942240+00:00 heroku[web.1]: State changed from starting to up
2017-05-11T10:19:32.233320+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
2017-05-11T10:19:32.233335+00:00 app[web.1]:   self.UnsuitableForProductionWarning
2017-05-11T10:19:32.243964+00:00 app[web.1]: /app/.heroku/python/lib/python3.6/site-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
2017-05-11T10:19:32.243966+00:00 app[web.1]:   self.UnsuitableForProductionWarning
2017-05-11T10:19:32.663339+00:00 app[web.1]: [2017-05-11 10:19:32 +0000] [9] [ERROR] Exception in worker process
2017-05-11T10:19:32.663355+00:00 app[web.1]: Traceback (most recent call last):
2017-05-11T10:19:32.663356+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-05-11T10:19:32.663357+00:00 app[web.1]:     worker.init_process()
2017-05-11T10:19:32.663357+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-05-11T10:19:32.663358+00:00 app[web.1]:     self.load_wsgi()
2017-05-11T10:19:32.663359+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-05-11T10:19:32.663359+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-05-11T10:19:32.663360+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-05-11T10:19:32.663361+00:00 app[web.1]:     self.callable = self.load()
2017-05-11T10:19:32.663362+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-05-11T10:19:32.663362+00:00 app[web.1]:     return self.load_wsgiapp()
2017-05-11T10:19:32.663363+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-05-11T10:19:32.663364+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-05-11T10:19:32.663365+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-05-11T10:19:32.663365+00:00 app[web.1]:     __import__(module)
2017-05-11T10:19:32.663366+00:00 app[web.1]:   File "/app/echobot.py", line 14, in <module>
2017-05-11T10:19:32.663366+00:00 app[web.1]:     chatterbot.train("./greetings.corpus.json")
2017-05-11T10:19:32.663367+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/chatterbot/trainers.py", line 117, in train
2017-05-11T10:19:32.663368+00:00 app[web.1]:     trainer.train(pair)
2017-05-11T10:19:32.663368+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/chatterbot/trainers.py", line 90, in train
2017-05-11T10:19:32.663369+00:00 app[web.1]:     self.storage.update(statement)
2017-05-11T10:19:32.663369+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/chatterbot/storage/jsonfile.py", line 161, in update
2017-05-11T10:19:32.663370+00:00 app[web.1]:     self.database.data(key=statement.text, value=data)
2017-05-11T10:19:32.663371+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/db.py", line 109, in data
2017-05-11T10:19:32.663372+00:00 app[web.1]:     return self._get_content()
2017-05-11T10:19:32.663373+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/db.py", line 52, in _get_content
2017-05-11T10:19:32.663373+00:00 app[web.1]:     obj = self.read_data(self.path)
2017-05-11T10:19:32.663374+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/file_writer.py", line 15, in read_data
2017-05-11T10:19:32.663374+00:00 app[web.1]:     obj = decode(content)
2017-05-11T10:19:32.663375+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/compat.py", line 32, in decode
2017-05-11T10:19:32.663376+00:00 app[web.1]:     return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
2017-05-11T10:19:32.663376+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/json/__init__.py", line 367, in loads
2017-05-11T10:19:32.663377+00:00 app[web.1]:     return cls(**kw).decode(s)
2017-05-11T10:19:32.663378+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 342, in decode
2017-05-11T10:19:32.663378+00:00 app[web.1]:     raise JSONDecodeError("Extra data", s, end)
2017-05-11T10:19:32.663383+00:00 app[web.1]: **json.decoder.JSONDecodeError:** Extra data: line 1 column 3 (char 2)
2017-05-11T10:19:32.663445+00:00 app[web.1]: [2017-05-11 10:19:32 +0000] [8] [ERROR] Exception in worker process
2017-05-11T10:19:32.663447+00:00 app[web.1]: Traceback (most recent call last):
2017-05-11T10:19:32.663448+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2017-05-11T10:19:32.663448+00:00 app[web.1]:     worker.init_process()
2017-05-11T10:19:32.663449+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2017-05-11T10:19:32.663450+00:00 app[web.1]:     self.load_wsgi()
2017-05-11T10:19:32.663450+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2017-05-11T10:19:32.663451+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2017-05-11T10:19:32.663452+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2017-05-11T10:19:32.663452+00:00 app[web.1]:     self.callable = self.load()
2017-05-11T10:19:32.663453+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2017-05-11T10:19:32.663453+00:00 app[web.1]:     return self.load_wsgiapp()
2017-05-11T10:19:32.663454+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2017-05-11T10:19:32.663455+00:00 app[web.1]:     return util.import_app(self.app_uri)
2017-05-11T10:19:32.663455+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2017-05-11T10:19:32.663456+00:00 app[web.1]:     __import__(module)
2017-05-11T10:19:32.663457+00:00 app[web.1]:   File "/app/echobot.py", line 14, in <module>
2017-05-11T10:19:32.663457+00:00 app[web.1]:     chatterbot.train("./greetings.corpus.json")
2017-05-11T10:19:32.663458+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/chatterbot/trainers.py", line 117, in train
2017-05-11T10:19:32.663458+00:00 app[web.1]:     trainer.train(pair)
2017-05-11T10:19:32.663459+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/chatterbot/trainers.py", line 82, in train
2017-05-11T10:19:32.663460+00:00 app[web.1]:     statement = self.get_or_create(text)
2017-05-11T10:19:32.663460+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/chatterbot/trainers.py", line 25, in get_or_create
2017-05-11T10:19:32.663461+00:00 app[web.1]:     statement = self.storage.find(statement_text)
2017-05-11T10:19:32.663461+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/chatterbot/storage/jsonfile.py", line 42, in find
2017-05-11T10:19:32.663462+00:00 app[web.1]:     values = self.database.data(key=statement_text)
2017-05-11T10:19:32.663463+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/db.py", line 98, in data
2017-05-11T10:19:32.663463+00:00 app[web.1]:     return self._get_content(key)
2017-05-11T10:19:32.663464+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/db.py", line 52, in _get_content
2017-05-11T10:19:32.663464+00:00 app[web.1]:     obj = self.read_data(self.path)
2017-05-11T10:19:32.663465+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/file_writer.py", line 15, in read_data
2017-05-11T10:19:32.663465+00:00 app[web.1]:     obj = decode(content)
2017-05-11T10:19:32.663466+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/jsondb/compat.py", line 32, in decode
2017-05-11T10:19:32.663467+00:00 app[web.1]:     return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
2017-05-11T10:19:32.663468+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/json/__init__.py", line 367, in loads
2017-05-11T10:19:32.663468+00:00 app[web.1]:     return cls(**kw).decode(s)
2017-05-11T10:19:32.663469+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/json/decoder.py", line 342, in decode
2017-05-11T10:19:32.663470+00:00 app[web.1]:     raise JSONDecodeError("Extra data", s, end)
2017-05-11T10:19:32.663473+00:00 app[web.1]: json.decoder.JSONDecodeError: Extra data: line 1 column 3 (char 2)

**Comment by vkosuri** [comment]
Which version of chatterbot are you using? To know use ``python -m chatterbot --version``

Can try to define encoding of your file by adding very first line in your python file ``# -*- coding: utf-8 -*-`` on type file, and also verify you have valid JSON file using https://jsonlint.com/

If still failing let us know

**Comment by addelll** [comment]
I have the error when I use corpus of the chatterbot , i dont know where is probleme ?

**Comment by Cosmos19** [comment]
Hi,

chatterbot.train("./greetings.corpus.json")

Can you please check above line.  It might be like below ( python 3.6.1)

chatterbot.train("chatterbot.corpus.english.greetings");

**Comment by addelll** [comment]
the same error i dont know where is probleme!!!
