### ISSUE TITLE
corpus data dne?

### ISSUE THREAD

**Issue by Thetoxicarcade** [gunthercox/ChatterBot#73]
When I try to train using the example in the readme, I get this error:

code:

```python
#!/usr/bin/env python
from chatterbot import ChatBot

bot = ChatBot("Terminal",
    storage_adapter="chatterbot.adapters.storage.JsonDatabaseAdapter",
    logic_adapter="chatterbot.adapters.logic.ClosestMatchAdapter",
    io_adapter="chatterbot.adapters.io.TerminalAdapter",
    database="database.db")

bot.train("chatterbot.corpus.english.greetings")
```

output:

```
[pons@australis-aurora code]$ ./chatting.py 
Traceback (most recent call last):
  File "./chatting.py", line 10, in <module>
    bot.train("chatterbot.corpus.english.greetings")
  File "/usr/lib64/python2.7/site-packages/chatterbot/chatterbot.py", line 152, in train
    self.trainer.train_from_corpora(corpora)
  File "/usr/lib64/python2.7/site-packages/chatterbot/training.py", line 34, in train_from_corpora
    corpus_data = self.corpus.load_corpus(corpus)
  File "/usr/lib64/python2.7/site-packages/chatterbot/corpus/corpus.py", line 55, in load_corpus
    corpus = self.read_corpus(corpus_path)
  File "/usr/lib64/python2.7/site-packages/chatterbot/corpus/corpus.py", line 30, in read_corpus
    with open(file_name) as data_file:    
IOError: [Errno 2] No such file or directory: '/usr/lib64/python2.7/site-packages/chatterbot/corpus/data/english/greetings'
```

is something just not installing?

**Comment by gunthercox** [comment]
Hi, it appears that the corpus data files were not included in the package. I've corrected the issue by including them in the project's `MANIFEST.in` file.

You should now be able to upgrade to chatterbot 0.2.9 where this should now be fixed.

**Comment by Thetoxicarcade** [comment]
you're awesome :) <3
