### ISSUE TITLE
“UnicodeDecodeError: 'utf8' codec can't decode byte 0xd4 in position 0: invalid continuation byte“

### ISSUE THREAD

**Issue by lijun900302** [gunthercox/ChatterBot#740]
I  changed  chatbot.train('chatterbot.corpus.english') to chatbot.train('chatterbot.corpus.chinese'), then I got the problem  “UnicodeDecodeError: 'utf8' codec can't decode byte 0xd4 in position 0: invalid continuation byte”. Then all of examples (  https://github.com/gunthercox/ChatterBot/tree/master/examples) have the sam problem.How can I solve this problem?

```
 D:\Anaconda\lib\site-packages\IPython\utils\traitlets.py:5: UserWarning: IPython.utils.traitlets has moved to a top-level traitlets package.
  warn("IPython.utils.traitlets has moved to a top-level traitlets package.")
pydev debugger: process 27696 is connecting

Connected to pydev debugger (build 141.2569)
D:\Anaconda\lib\site-packages\chatterbot\storage\jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "D:\PyCharm 4.5.4\helpers\pydev\pydevd.py", line 2358, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\PyCharm 4.5.4\helpers\pydev\pydevd.py", line 1778, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:/pycharm/ChatterBot/examples/export_example.py", line 15, in <module>
    chatbot.train('chatterbot.corpus.english')
  File "D:\Anaconda\lib\site-packages\chatterbot\trainers.py", line 117, in train
    trainer.train(pair)
  File "D:\Anaconda\lib\site-packages\chatterbot\trainers.py", line 82, in train
    statement = self.get_or_create(text)
  File "D:\Anaconda\lib\site-packages\chatterbot\trainers.py", line 25, in get_or_create
    statement = self.storage.find(statement_text)
  File "D:\Anaconda\lib\site-packages\chatterbot\storage\jsonfile.py", line 42, in find
    values = self.database.data(key=statement_text)
  File "D:\Anaconda\lib\site-packages\jsondb\db.py", line 98, in data
    return self._get_content(key)
  File "D:\Anaconda\lib\site-packages\jsondb\db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "D:\Anaconda\lib\site-packages\jsondb\file_writer.py", line 15, in read_data
    obj = decode(content)
  File "D:\Anaconda\lib\site-packages\jsondb\compat.py", line 32, in decode
    return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
  File "D:\Anaconda\lib\json\__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "D:\Anaconda\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda\lib\json\decoder.py", line 380, in raw_decode
    obj, end = self.scan_once(s, idx)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd4 in position 0: invalid continuation byte 
```

**Comment by gunthercox** [comment]
Hi @lijun900302 It sounds like this might be a simple Python encoding issue. I noticed that you are using iPython and I am aware that developers seem to encounter errors like this more frequently with Anaconda distrobutions of Python. If you have a way to set the encoding in iPython this might fix the problem.

**Comment by gunthercox** [comment]
I've attempted to recreate this issue using the latest version of ChatterBot and `chatterbot-corpus`. I believe this may have been corrected in a previous release.
