### ISSUE TITLE
Error after actualice chatterbot to 6.0 version

### ISSUE THREAD

**Issue by Marcogb81** [gunthercox/ChatterBot#743]
I actualiced the chatterbot to new version 6.0 and give me this error in python 2.7:
this code:
# -*- coding: utf-8 -*-
"""RESET: por si te da guerra este pedazo de desgraciado
   cibernetico, aqui tienes el enlace:
   https://chatterbot.readthedocs.io/en/stable/tutorial.html"""
from chatterbot import ChatBot

# new instance, databse, logic adapters
bot = ChatBot('TeRiehBot',
              storage_adapter='chatterbot.adapters.storage.JsonFileStorageAdapter',
              input_adapter='chatterbot.adapters.input.TerminalAdapter',
              output_adapter='chatterbot.adapters.output.TerminalAdapter',
              database='./database.json'
              )

# get response and scape bt control + C
while True:
    try:
        bot_input = bot.get_response(None)
    except(KeyboardInterrupt, EOFError, SystemExit):
        break

# training
bot.train([
    'Hola',
    '¿Qué tal?',
    '¿Cómo te va?',
    '¡¿Te Rieh!?',
    'Gracias.',
    'Adios.',
])

this output error

/usr/bin/python2.7 /home/marco/Desktop/.idea/TeRiehBot.py
/usr/local/lib/python2.7/dist-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "/home/marco/Desktop/.idea/TeRiehBot.py", line 12, in <module>
    database='./database.json'
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 83, in __init__
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 94, in initialize
    nltk_download_corpus('tokenizers/punkt')
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 635, in find
    return find(modified_name, paths)
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 621, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/local/lib/python2.7/dist-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 470, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/local/lib/python2.7/dist-packages/nltk/compat.py", line 366, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nltk/data.py", line 986, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "/usr/lib/python2.7/zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file

**Comment by gunthercox** [comment]
This is an error that occurs sometimes as a result of a bad NLTK corpus download. ChatterBot downloads this data automatically when it starts up.

See if the solution that was reached in https://github.com/gunthercox/ChatterBot/issues/736#issuecomment-301325738 works for you. Let me know if deleting the downloaded data files doesn't solve the issue.

Also noting that this was reported in (#662, #634, #657, #672).
