### ISSUE TITLE
ValueError: Extra data:

### ISSUE THREAD

**Issue by sanyam8182** [gunthercox/ChatterBot#760]
When i try to run the bot i get the below output.

# Train based on the english corpus
... chatbot.train("chatterbot.corpus.english")
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "chatterbot/trainers.py", line 117, in train
    trainer.train(pair)
  File "chatterbot/trainers.py", line 82, in train
    statement = self.get_or_create(text)
  File "chatterbot/trainers.py", line 25, in get_or_create
    statement = self.storage.find(statement_text)
  File "chatterbot/storage/jsonfile.py", line 42, in find
    values = self.database.data(key=statement_text)
  File "/Users/yuvikakoul/anaconda/lib/python2.7/site-packages/jsondb/db.py", line 98, in data
    return self._get_content(key)
  File "/Users/yuvikakoul/anaconda/lib/python2.7/site-packages/jsondb/db.py", line 52, in _get_content
    obj = self.read_data(self.path)
  File "/Users/yuvikakoul/anaconda/lib/python2.7/site-packages/jsondb/file_writer.py", line 15, in read_data
    obj = decode(content)
  File "/Users/yuvikakoul/anaconda/lib/python2.7/site-packages/jsondb/compat.py", line 32, in decode
    return json_decode(value, encoding='utf-8', object_hook=json_util.object_hook)
  File "/Users/yuvikakoul/anaconda/lib/python2.7/json/__init__.py", line 352, in loads
    return cls(encoding=encoding, **kw).decode(s)
  File "/Users/yuvikakoul/anaconda/lib/python2.7/json/decoder.py", line 367, in decode
    raise ValueError(errmsg("Extra data", s, end, len(s)))
ValueError: Extra data: line 1 column 1026 - line 1 column 158860 (char 1025 - 158859)
>>> 

i cant figure out what the problem is. I tried to reinstall the bot but the problem still remained.
Please help me out here.

**Comment by vkosuri** [comment]
Currently chatterbot doesn't tested on anaconda, please try with Python2 or Python3 variants,  If it reproduces please feel to reopen this issue.

**Comment by BlogBlocks** [comment]
367             raise ValueError(errmsg("Extra data", s, end, len(s)))
    368         return obj
    369 

ValueError: Extra data: line 1 column 3 - line 1 column 223466 (char 2 - 223465)

**Comment by gunthercox** [comment]
I can't seem to recreate this error on my system. If anyone can create a training test case that fails when it should pass for this data it would help to resolve the error. Until then there isn't much I can do because I don't have a way to test or recreate this.

**Comment by lashkarpalash** [comment]
I encountered same issue running on python 2.7. 
What is the location of the  english corpa JSON file ? 

-PL

**Comment by lashkarpalash** [comment]
Found 20 JSON files in <>python\v2.7\Lib\site-packages\chatterbot_corpus\data\english . 
Which file @BlogBlocks ?

**Comment by lashkarpalash** [comment]
I was on python2.7 while I had that error, later using virtualenv tried testing on python3.6 and it worked fine without making any change to any JSON file. I am on a 64 bit machine/os.

**Comment by gunthercox** [comment]
@lashkarpalash What version of ChatterBot did you encounter this issue with?

**Comment by lashkarpalash** [comment]
been away, its v 0.6.3

**Comment by vkosuri** [comment]
current chatterbot version is ``0.7.0``, could you try to upgrade to latest version and let me know

``pip install --upgrade chatterbot``
