### ISSUE TITLE
Chatterbot error on windows

### ISSUE THREAD

**Issue by psengupta1973** [gunthercox/ChatterBot#779]
Hi,

Facing an issue as below. Please help.

``` Bash
C:\>python
Python 3.6.0 |Anaconda 4.3.1 (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1
900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ChatBot from chatterbot
  File "<stdin>", line 1
    import ChatBot from chatterbot
                      ^
SyntaxError: invalid syntax
>>> from chatterbot import ChatBot
>>> chatbot = ChatBot('Ujbuk')
C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\chatterbot\
storage\jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapt
er is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\cha
tterbot\chatterbot.py", line 37, in __init__
    self.storage = utils.initialize_class(storage_adapter, **kwargs)
  File "C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\cha
tterbot\utils.py", line 33, in initialize_class
    return Class(**kwargs)
  File "C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\cha
tterbot\storage\jsonfile.py", line 30, in __init__
    self.database = Database(database_path)
  File "C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\jso
ndb\db.py", line 22, in __init__
    self.set_path(file_path)
  File "C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\jso
ndb\db.py", line 47, in set_path
    self.write_data(file_path, {})
  File "C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\jso
ndb\file_writer.py", line 25, in write_data
    with open_file_for_writing(path) as db:
  File "C:\Users\eparsen\AppData\Local\Continuum\Anaconda3\lib\site-packages\jso
ndb\compat.py", line 70, in open_file_for_writing
    return io.open(*args, **kwargs)
PermissionError: [Errno 13] Permission denied: 'database.db'
>>>
```

**Comment by gunthercox** [comment]
I think the last line of this stack trace might be the best clue as to what is going wrong.

> PermissionError: [Errno 13] Permission denied: 'database.db'

For some reason ChatterBot can't create a new database file in whatever directory the chat bot is being executed in. The reason, as specified in the stack trace is that it doesn't have permission to do this.

One way you may be able to fix this is to create a new file called `database.db` in the directory that you want to execute your chat bot from.

**Comment by psengupta1973** [comment]
Hi,
Thanks for your reply.
I have tried changing permission to all directories and sub-directories of the location where it's installed and also tried creating a blank file names 'database.db' in most of the directories under chatterbot, however it didn't work.
