### ISSUE TITLE
I have a problem, I've done everything and I could not solve

### ISSUE THREAD

**Issue by lucas-alberto98** [gunthercox/ChatterBot#780]
I installed everything as the ChatterBot site says, but still gets this error.
```Bash
> /usr/local/lib/python3.5/dist-packages/chatterbot/storage/jsonfile.py:26: UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
  self.UnsuitableForProductionWarning
Traceback (most recent call last):
  File "terminal_example.py", line 20, in <module>
    database="../database.db"
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 84, in __init__
    self.initialize()
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/chatterbot.py", line 94, in initialize
    nltk_download_corpus('corpora/wordnet')
  File "/usr/local/lib/python3.5/dist-packages/chatterbot/utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 640, in find
    return find(modified_name, paths)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 626, in find
    return ZipFilePathPointer(p, zipentry)
  File "/usr/local/lib/python3.5/dist-packages/nltk/compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 473, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "/usr/local/lib/python3.5/dist-packages/nltk/compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/nltk/data.py", line 992, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "/usr/lib/python3.5/zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.5/zipfile.py", line 1093, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

I've tried reinstalling everything, but the error has already been reinstalled a thousand times the ChatterBot lib and ntlk and continues with this error.
The error happens in python2 and python3
Can someone help me?

**Comment by gunthercox** [comment]
Hi @lucas-alberto98 , I have seen this error reported several times. It is caused by a broken NLTK data download. This problem can be fixed if you remove the NLTK corpus files that get automatically downloaded.

**Comment by lucas-alberto98** [comment]
But I already tried to delete the nltk and install, but the error continues.
Have it delete which folder/file?

**Comment by gunthercox** [comment]
The folder you want to delete is called `nltk_data`. It is created automatically by the NLTK Python library. Usually, `nltk_data` can be found in your home directory, although it can be different depending on what operating system you have.
