### ISSUE TITLE
I got a problem while installing the chatterbot

### ISSUE THREAD

**Issue by SzuHannah** [gunthercox/ChatterBot#785]
I've tried as many things I could but still couldn't resolve the problem..
here's the error message:
`Traceback (most recent call last):
  File "C:/Users/qqisi/Documents/Han/大四/計程/final project/try step by step.py", line 5, in <module>
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\chatterbot.py", line 84, in __init__
    self.initialize()
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\chatterbot.py", line 94, in initialize
    nltk_download_corpus('corpora/wordnet')
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\utils.py", line 118, in nltk_download_corpus
    find(resource_path)
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\data.py", line 640, in find
    return find(modified_name, paths)
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\data.py", line 626, in find
    return ZipFilePathPointer(p, zipentry)
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\data.py", line 473, in __init__
    zipfile = OpenOnDemandZipFile(os.path.abspath(zipfile))
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\compat.py", line 221, in _decorator
    return init_func(*args, **kwargs)
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\data.py", line 992, in __init__
    zipfile.ZipFile.__init__(self, filename)
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\zipfile.py", line 1026, in __init__
    self._RealGetContents()
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\zipfile.py", line 1094, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`

I saw others ask this question, and got the reply that the chatterbot would work if the nltk corpus files were removed. However, I removed them but still got an error:
`Warning (from warnings module):
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\storage\jsonfile.py", line 26
    self.UnsuitableForProductionWarning
UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
Traceback (most recent call last):
  File "C:/Users/qqisi/Documents/Han/大四/計程/final project/try step by step.py", line 5, in <module>
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\chatterbot.py", line 84, in __init__
    self.initialize()
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\chatterbot.py", line 93, in initialize
    nltk_download_corpus('corpora/stopwords')
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\chatterbot\utils.py", line 99, in nltk_download_corpus
    from nltk.data import find
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\__init__.py", line 137, in <module>
    from nltk.stem import *
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\stem\__init__.py", line 29, in <module>
    from nltk.stem.snowball import SnowballStemmer
  File "C:\Users\qqisi\AppData\Local\Programs\Python\Python35\lib\site-packages\nltk\stem\snowball.py", line 26, in <module>
    from nltk.corpus import stopwords
ImportError: No module named 'nltk.corpus'`

please help..thanks

**Comment by SzuHannah** [comment]
Ahh I solved it, thanks.
