### ISSUE TITLE
ModuleNotFoundError: No module named 'chatterbot_corpus'

### ISSUE THREAD

**Issue by Olagsfark** [gunthercox/ChatterBot#833]
**Hi; firstly i must commend your work, its amazing! Good job!!

So i ran the _tkinter_gui.py_ example perfectly well with no issues. But then i tried to train the bot with an English corpus trainer and ended up with moduleImportError.** 

## Here is the final code i ran

```
# -*- coding: utf-8 -*-
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer
import tkinter as tk
try:
    import ttk as ttk
    import ScrolledText
except ImportError:
    import tkinter.ttk as ttk
    import tkinter.scrolledtext as ScrolledText
import time


class TkinterGUIExample(tk.Tk):

    def __init__(self, *args, **kwargs):
        """
        Create & set window variables.
        """
        tk.Tk.__init__(self, *args, **kwargs)

        self.chatbot = ChatBot(
            "GUI Bot",
            storage_adapter="chatterbot.storage.JsonFileStorageAdapter",
            logic_adapters=[
                "chatterbot.logic.BestMatch"
            ],
            input_adapter="chatterbot.input.VariableInputTypeAdapter",
            output_adapter="chatterbot.output.OutputAdapter",
            database="database.json"
        )
        self.chatbot.set_trainer(ChatterBotCorpusTrainer)
        self.chatbot.train('chatterbot.corpus.english')
        
        self.title("Chatterbot")

        self.initialize()

    def initialize(self):
        """
        Set window layout.
        """
        self.grid()

        self.respond = ttk.Button(self, text='Get Response', command=self.get_response)
        self.respond.grid(column=0, row=0, sticky='nesw', padx=3, pady=3)

        self.usr_input = ttk.Entry(self, state='normal')
        self.usr_input.grid(column=1, row=0, sticky='nesw', padx=3, pady=3)

        self.conversation_lbl = ttk.Label(self, anchor=tk.E, text='Conversation:')
        self.conversation_lbl.grid(column=0, row=1, sticky='nesw', padx=3, pady=3)

        self.conversation = ScrolledText.ScrolledText(self, state='disabled')
        self.conversation.grid(column=0, row=2, columnspan=2, sticky='nesw', padx=3, pady=3)

    def get_response(self):
        """
        Get a response from the chatbot and display it.
        """
        user_input = self.usr_input.get()
        self.usr_input.delete(0, tk.END)

        response = self.chatbot.get_response(user_input)

        self.conversation['state'] = 'normal'
        self.conversation.insert(
            tk.END, "Human: " + user_input + "\n" + "ChatBot: " + str(response.text) + "\n"
        )
        self.conversation['state'] = 'disabled'

        time.sleep(0.5)


gui_example = TkinterGUIExample()
gui_example.mainloop()

```

## here is the error log

```
Warning (from warnings module):
  File "C:\Users\foo\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot-0.6.1-py3.6.egg\chatterbot\storage\jsonfile.py", line 26
UnsuitableForProductionWarning: The JsonFileStorageAdapter is not recommended for production environments.
Traceback (most recent call last):
  File "C:\Users\foo\Codes\AI\projects\carl\tkinter_gui.py", line 75, in <module>
    gui_example = TkinterGUIExample()
  File "C:\Users\foo\Codes\AI\projects\carl\tkinter_gui.py", line 32, in __init__
    self.chatbot.set_trainer(ChatterBotCorpusTrainer)
  File "C:\Users\foo\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot-0.6.1-py3.6.egg\chatterbot\chatterbot.py", line 166, in set_trainer
    self.trainer = training_class(self.storage, **kwargs)
  File "C:\Users\foo\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot-0.6.1-py3.6.egg\chatterbot\trainers.py", line 101, in __init__
    from .corpus import Corpus
  File "C:\Users\foo\AppData\Local\Programs\Python\Python36\lib\site-packages\chatterbot-0.6.1-py3.6.egg\chatterbot\corpus\__init__.py", line 6, in <module>
    from chatterbot_corpus import Corpus
ModuleNotFoundError: No module named 'chatterbot_corpus'
```

i am actually planning to integrate this bot in a live project as a replacement of a Chatscript server, your response and support will go a looong long way. Thanks

**Comment by vkosuri** [comment]
@Olagsfark Thank you. ``chatterbot_corpus`` will come through ``chatterbot`` requirements. 

Could you please try to do update chatterbot by using  ``pip install --upgrade chatterbot``. 

Still if you are seeing same error message. Try to install ``chatterbot_corpus`` individually ``pip install --upgrade chatterbot_corpus``

**Comment by Olagsfark** [comment]
Okay, i'll follow those instructions. Thanks!

**Comment by atulanandnitt** [comment]
Neither
 pip install --upgrade chatterbot_corpus nor
 pip install --upgrade chatterbot
is working for me.


I am using:
Python 3.6.3 :: Anaconda custom (64-bit)
in windows 7.



its throwing error:
C:\Users\atanand.ORADEV>pip install --upgrade chatterbot_corpus
Collecting chatterbot_corpus
Exception:
Traceback (most recent call last):
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\commands\install.py", line 335, in run
    wb.build(autobuilding=True)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\req\req_set.py", line 554, in _prepare_file
    require_hashes
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\req\req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 811, in get_page
    inst = cls(resp.content, resp.url, resp.headers)
  File "C:\Users\atanand.ORADEV\AppData\Local\Continuum\anaconda3\lib\site-packages\pip\index.py", line 731, in __init__
    namespaceHTMLElements=False,
TypeError: parse() got an unexpected keyword argument 'transport_encoding'
