### ISSUE TITLE
when run example file, report many errors

### ISSUE THREAD

**Issue by huobaiyu** [gunthercox/ChatterBot#842]
source py file:
```Python
from chatterbot import ChatBot

chatbot = ChatBot(
    'Ron Obvious',
    trainer='chatterbot.trainers.ChatterBotCorpusTrainer'
)

# Train based on the english corpus
chatbot.train("chatterbot.corpus.english")

# Get a response to an input statement
chatbot.get_response("Hello, how are you today?")
```
output：
```Bash
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: ResponseTable.text, ResponseTable.text_search [SQL: 'INSERT INTO "ResponseTable" (id, text, occurrence, statement_text, text_search) VALUES (?, ?, ?, ?, ?)'] [parameters: (None, 'you are cheating', 1, 'you are a cheat', '{"id": null, "text": "you are cheating", "occurrence": 1, "statement_text": "you are a cheat"}')]
None
Traceback (most recent call last):
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: ResponseTable.text, ResponseTable.text_search

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Program Files (x86)\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 292, in _session_finish
    session.commit()
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 906, in commit
    self.transaction.commit()
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 461, in commit
    self._prepare_impl()
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 441, in _prepare_impl
    self.session.flush()
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2171, in flush
    self._flush(objects)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2291, in _flush
    transaction.rollback(_capture_exception=True)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\util\langhelpers.py", line 66, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 187, in reraise
    raise value
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\session.py", line 2255, in _flush
    flush_context.execute()
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 389, in execute
    rec.execute(self)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\unitofwork.py", line 548, in execute
    uow
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 181, in save_obj
    mapper, table, insert)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\persistence.py", line 835, in _emit_insert_statements
    execute(statement, params)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute
    return meth(self, multiparams, params)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement
    compiled_sql, distilled_params
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context
    context)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception
    exc_info
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise
    raise value.with_traceback(tb)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context
    context)
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: ResponseTable.text, ResponseTable.text_search [SQL: 'INSERT INTO "ResponseTable" (id, text, occurrence, statement_text, text_search) VALUES (?, ?, ?, ?, ?)'] [parameters: (None, 'you are a bad husband', 1, 'you are a bad spouse', '{"id": null, "text": "you are a bad husband", "occurrence": 1, "statement_text": "you are a bad spouse"}')]
```

**Comment by gunthercox** [comment]
Hi @huobaiyu thank you for the bug report. I will correct this as soon as possible.

**Comment by gabru-md** [comment]
Check Stack-Overflow [Here](https://stackoverflow.com/questions/31059477/sqlalchemy-unique-constraint-failed-error-yet-no-unique-constraints-set)

It says that : 
"Drop your tables or delete your DB and initialize it again. Every time you make a schema change you must drop your tables and re-initialize, it doesn't just update."

I hope this helps :D
Cheers!

**Comment by huobaiyu** [comment]
I didn't create any tables. How to drop or delete tables?

**Comment by gunthercox** [comment]
my_chatbot = ChatBot(...)

my_chatbot.storage.drop()

**Comment by huobaiyu** [comment]
still report errors:
Traceback (most recent call last):                                                                                                                                                                                 
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context                                                                                               
    context)                                                                                                                                                                                                       
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute                                                                                                   
    cursor.execute(statement, parameters)                                                                                                                                                                          
sqlite3.OperationalError: no such table: StatementTable                                                                                                                                                            
                                                                                                                                                                                                                   
The above exception was the direct cause of the following exception:                                                                                                                                               
                                                                                                                                                                                                                   
Traceback (most recent call last):                                                                                                                                                                                 
  File ".\bot_api.py", line 10, in <module>                                                                                                                                                                        
    chatbot.train("chatterbot.corpus.english")                                                                                                                                                                     
  File "D:\Program Files (x86)\Python36\lib\site-packages\chatterbot\trainers.py", line 124, in train                                                                                                              
    statement = self.get_or_create(text)                                                                                                                                                                           
  File "D:\Program Files (x86)\Python36\lib\site-packages\chatterbot\trainers.py", line 27, in get_or_create                                                                                                       
    statement = self.storage.find(statement_text)                                                                                                                                                                  
  File "D:\Program Files (x86)\Python36\lib\site-packages\chatterbot\storage\sql_storage.py", line 148, in find                                                                                                    
    record = query.first()                                                                                                                                                                                         
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2755, in first                                                                                                            
    ret = list(self[0:1])                                                                                                                                                                                          
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2547, in __getitem__                                                                                                      
    return list(res)                                                                                                                                                                                               
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2855, in __iter__                                                                                                         
    return self._execute_and_instances(context)                                                                                                                                                                    
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\orm\query.py", line 2878, in _execute_and_instances                                                                                           
    result = conn.execute(querycontext.statement, self._params)                                                                                                                                                    
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 945, in execute                                                                                                         
    return meth(self, multiparams, params)                                                                                                                                                                         
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\sql\elements.py", line 263, in _execute_on_connection                                                                                         
    return connection._execute_clauseelement(self, multiparams, params)                                                                                                                                            
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1053, in _execute_clauseelement                                                                                         
    compiled_sql, distilled_params                                                                                                                                                                                 
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1189, in _execute_context                                                                                               
    context)                                                                                                                                                                                                       
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1402, in _handle_dbapi_exception                                                                                        
    exc_info                                                                                                                                                                                                       
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 203, in raise_from_cause                                                                                                
    reraise(type(exception), exception, tb=exc_tb, cause=cause)                                                                                                                                                    
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\util\compat.py", line 186, in reraise                                                                                                         
    raise value.with_traceback(tb)                                                                                                                                                                                 
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\base.py", line 1182, in _execute_context                                                                                               
    context)                                                                                                                                                                                                       
  File "D:\Program Files (x86)\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 470, in do_execute                                                                                                   
    cursor.execute(statement, parameters)                                                                                                                                                                          
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: StatementTable [SQL: 'SELECT "StatementTable".id AS "StatementTable_id", "StatementTable".text AS "StatementTable_text", "StatementTable
".extra_data AS "StatementTable_extra_data", "StatementTable".text_search AS "StatementTable_text_search" \nFROM "StatementTable" \nWHERE "StatementTable".text = ?\n LIMIT ? OFFSET ?'] [parameters: ('What is ai'
, 1, 0)]

**Comment by gunthercox** [comment]
@huobaiyu Yes, this is an actual bug in ChatterBot. You aren't doing anything incorrectly. I am still tracking down where the error is actually occurring.
