### ISSUE TITLE
Crash in use SQLStorageAdapter

### ISSUE THREAD

**Issue by Listade** [gunthercox/ChatterBot#867]
``` Python
def filter_selection(self, chatterbot, session_id):

        session = chatterbot.conversation_sessions.get(session_id)

        if session.conversation.empty():
            return chatterbot.storage.base_query

        text_of_recent_responses = []

        for statement, response in session.conversation:
            text_of_recent_responses.append(response.text)

        query = chatterbot.storage.base_query.statement_text_not_in(
            text_of_recent_responses
        )

        return query
```

``` Bash
>
INFO:ChatBot:"сколько филиалов?" is not a known statement
Traceback (most recent call last):
  File "/home/listade/.IdeaIC2017.1/config/plugins/python-ce/helpers/pydev/pydevd.py", line 1585, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/listade/.IdeaIC2017.1/config/plugins/python-ce/helpers/pydev/pydevd.py", line 1021, in run
    runpy._run_module_as_main(module_name, alter_argv=False)
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/listade/Desktop/speech_bot-project/speech_bot/__main__.py", line 71, in <module>
    main()
  File "/home/listade/Desktop/speech_bot-project/speech_bot/__main__.py", line 65, in main
    chatbot.get_response(None)
  File "/usr/lib/python3.6/site-packages/chatterbot/chatterbot.py", line 109, in get_response
    statement, response = self.generate_response(input_statement, session_id)
  File "/usr/lib/python3.6/site-packages/chatterbot/chatterbot.py", line 126, in generate_response
    self.storage.generate_base_query(self, session_id)
  File "/usr/lib/python3.6/site-packages/chatterbot/storage/storage_adapter.py", line 45, in generate_base_query
    self.base_query = filter_instance.filter_selection(chatterbot, session_id)
  File "/usr/lib/python3.6/site-packages/chatterbot/filters.py", line 39, in filter_selection
    query = chatterbot.storage.base_query.statement_text_not_in(
AttributeError: 'NoneType' object has no attribute 'statement_text_not_in'
> 
```

**Comment by vkosuri** [comment]
@Listade Could you please your example code, to debug further.

**Comment by ingmferrer** [comment]
I'm having this same issue, same traceback.

**Comment by AxelAli** [comment]
same
