### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by nalancer08** [gunthercox/ChatterBot#913]
Hi, I use a Mac with python 2.7.10 and pip2

When i tried to install the bot with pip, gives me this error, can you help me.

```
Collecting ruamel.yaml<=0.15 (from chatterbot-corpus<1.1,>=1.0->chatterbot)
  Downloading ruamel.yaml-0.15.0.tar.gz (247kB)
    100% |████████████████████████████████| 256kB 3.0MB/s 
    Complete output from command python setup.py egg_info:
    /tmp/tmp_ruamel_0utFWU/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /tmp/tmp_ruamel_0utFWU/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /tmp/tmp_ruamel_0utFWU/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    /tmp/tmp_ruamel_0utFWU/test_ruamel_yaml.c:6:8: warning: explicitly assigning value of variable of type 'yaml_parser_t' (aka 'struct yaml_parser_s') to itself [-Wself-assign]
    parser = parser;  /* prevent warning */
    ~~~~~~ ^ ~~~~~~
    /tmp/tmp_ruamel_0utFWU/test_ruamel_yaml.c:6:10: warning: variable 'parser' is uninitialized when used here [-Wuninitialized]
    parser = parser;  /* prevent warning */
             ^~~~~~
    /tmp/tmp_ruamel_0utFWU/test_ruamel_yaml.c:5:1: note: variable 'parser' is declared here
    yaml_parser_t parser;
    ^
    2 warnings generated.
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-_9XDX7/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/private/tmp/pip-build-_9XDX7/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 326, in finalize_options
        ep.require(installer=self.fetch_build_egg)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2385, in require
        reqs = self.dist.requires(self.extras)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2617, in requires
        dm = self._dep_map
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 2606, in _dep_map
        if invalid_marker(marker):
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1424, in is_invalid_marker
        cls.evaluate_marker(text)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1549, in _markerlib_evaluate
        env = cls._translate_metadata2(_markerlib.default_environment())
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1537, in _translate_metadata2
        for key, value in env
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1536, in <genexpr>
        (key.replace('.', '_'), value)
    ValueError: too many values to unpack
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-_9XDX7/ruamel.yaml/

```

**Comment by gunthercox** [comment]
Hi @nalancer08 I don't have a Mac to test with but I'll see what I can do to resolve this. One thing I just noticed is that there have been [some updates](https://pypi.python.org/pypi/ruamel.yaml) to the `ruamel.yaml` library since version 0.15, one of which seems to include Python wheels (which may fix some of the c-related errors you are seeing in your output).

Want to try running the following and let me know if it installs?

```
pip install ruamel.yaml --upgrade
```

This should install the latest version of `ruamel.yaml`. It looks like I need to update the version that is pinned in the `chatterbot-corpus` package: https://github.com/gunthercox/chatterbot-corpus/blob/master/requirements.txt

**Comment by 7633** [comment]
How about python 3?

**Comment by vkosuri** [comment]
Similar issue https://bitbucket.org/ruamel/yaml/issues/37/osx-not-able-to-install-using-pip

**Comment by nalancer08** [comment]
Thank you so much for everyone, I fixed compiling direct with

python setup.py build
python setup.py install

But, with PIP I didnt make it works

**Comment by gunthercox** [comment]
@nalancer08 I'm glad your issue was resolved. I am going to make changes to switch to a different Python YAML library to hopefully fix and prevent issues like this in the future.
