### ISSUE TITLE
chatterbot train fails: value too long for type character varying(255)

### ISSUE THREAD

**Issue by cho-is** [gunthercox/ChatterBot#921]
`AbstractBaseStatement`[models.py#L12](https://github.com/gunthercox/ChatterBot/blob/master/chatterbot/ext/django_chatterbot/models.py#L12) has `max_length=255` so the corpus fails at: [corpus.english.ai#L57](https://github.com/gunthercox/chatterbot-corpus/blob/master/chatterbot_corpus/data/english/ai.yml#L57)

I understand using `CharField` and maximum length might be more efficient in terms of performance or storage, but that forces to short statements.

**Comment by vkosuri** [comment]
how about increased it to 16K, 

```Python
text = models.CharField(
        unique=True,
        blank=False,
        null=False,
        max_length=16384
)
```
or make it as TextField

```Python
text = models.TextField(
        unique=True,
        blank=False,
        null=False
)
```

**Comment by cho-is** [comment]
Just tried making it a `TextField` and then got 

```
Training: [####################] 98%Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/sentiment/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/sentiment/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/vagrant/sentiment/local/lib/python2.7/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/vagrant/sentiment/local/lib/python2.7/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/vagrant/api/django_chatterbot/management/commands/train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
  File "/home/vagrant/sentiment/local/lib/python2.7/site-packages/chatterbot/trainers.py", line 141, in train
    self.storage.update(statement)
  File "/home/vagrant/sentiment/local/lib/python2.7/site-packages/chatterbot/storage/django_storage.py", line 107, in update
    response.occurrence += 1
AttributeError: can't set attribute
```

**Comment by vkosuri** [comment]
@cho-is It working fine on my machine. I am not sure in what you are getting this error.

```
text = models.TextField(
        unique=True,
        blank=False,
        null=False
)
```
