### ISSUE TITLE
Problem when training a custom corpus in django project.

### ISSUE THREAD

**Issue by vedantnarayan** [gunthercox/ChatterBot#959]
Hi ,

I have added a custom corpus . my directory structure is as follows - circus/example_app/CustomCorpus/oneWindow.yml

and my Settings.py looks like this -- 
``` Python
CHATTERBOT = {
    'name': 'Django ChatterBot Example',
    'logic_adapters': [
        "chatterbot.logic.MathematicalEvaluation",
        "chatterbot.logic.BestMatch"
    ],
    'trainer': 'chatterbot.trainers.ChatterBotCorpusTrainer',
    'training_data': [
        'circus.example_app.CustomCorpus'
    ]
}
```
When I am running manage.py train, I am getting the following error-
``` Bash
C:\Python27\python.exe C:/Python27/Scripts/circus/manage.py train
Traceback (most recent call last):
  File "C:/Python27/Scripts/circus/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\chatterbot\ext\django_chatterbot\management\commands\train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
  File "C:\Python27\lib\site-packages\chatterbot\trainers.py", line 119, in train
    corpora = self.corpus.load_corpus(corpus_path)
  File "C:\Python27\lib\site-packages\chatterbot_corpus\corpus.py", line 86, in load_corpus
    corpus = self.read_corpus(file_path)
  File "C:\Python27\lib\site-packages\chatterbot_corpus\corpus.py", line 52, in read_corpus
    with io.open(file_name, encoding='utf-8') as data_file:
IOError: [Errno 2] No such file or directory: 'circus\\example_app\\CustomCorpus'
```
Please help.

**Comment by vkosuri** [comment]
@vedantnarayan Django unable to find your custom corpus file in Pythons ``site-packages`` folder, Could try to place your CustomCorpus. for example ``C:\Python27\Lib\site-packages\circus\example_app\CustomCorpus``

**Comment by vedantnarayan** [comment]
The issue is solved. Please close this.
