### ISSUE TITLE
untraining a chatbot

### ISSUE THREAD

**Issue by MayankGupta3090** [gunthercox/ChatterBot#970]
how can I untrain a chatbot?
I have done following:
1. deleted db.sqlite3 file
2. trying to train the chatbot after deleting the db.sqlite3 file

getting the following error while training the bot:

Thanks in advance!!!

C:\Python36\python.exe C:/Users/mayan/Desktop/Circus-master/manage.py train
botprofile.yml Training: [###                 ] 17%Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such table: django_chatterbot_statement

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/mayan/Desktop/Circus-master/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "C:\Python36\lib\site-packages\django\core\management\__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python36\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python36\lib\site-packages\django\core\management\base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "C:\Python36\lib\site-packages\chatterbot\ext\django_chatterbot\management\commands\train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
  File "C:\Python36\lib\site-packages\chatterbot\trainers.py", line 133, in train
    statement = self.get_or_create(text)
  File "C:\Python36\lib\site-packages\chatterbot\trainers.py", line 28, in get_or_create
    statement = self.storage.find(statement_text)
  File "C:\Python36\lib\site-packages\chatterbot\storage\django_storage.py", line 25, in find
    return Statement.objects.get(text=statement_text)
  File "C:\Python36\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Python36\lib\site-packages\django\db\models\query.py", line 374, in get
    num = len(clone)
  File "C:\Python36\lib\site-packages\django\db\models\query.py", line 232, in __len__
    self._fetch_all()
  File "C:\Python36\lib\site-packages\django\db\models\query.py", line 1118, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "C:\Python36\lib\site-packages\django\db\models\query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch)
  File "C:\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 894, in execute_sql
    raise original_exception
  File "C:\Python36\lib\site-packages\django\db\models\sql\compiler.py", line 884, in execute_sql
    cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 80, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "C:\Python36\lib\site-packages\django\utils\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Python36\lib\site-packages\django\db\backends\utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "C:\Python36\lib\site-packages\django\db\backends\sqlite3\base.py", line 328, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such table: django_chatterbot_statement

Process finished with exit code 1

**Comment by maylad31** [comment]
I think you forgot to migrate before training.

**Comment by maylad31** [comment]
Did my respnse help?

**Comment by vkosuri** [comment]
@maylad31 are looking a solution or anything you are conveying message to update solution?

**Comment by WildDylan** [comment]
untrain a chatbot? why not redeploy....

**Comment by Issen007** [comment]
I think the correct way from a Django perspective is to login as Django Admin and open Response / Statement and delete the line you want to "untrain" or correct the answer so you get the correct statement with the correct answer.

**Comment by Issen007** [comment]
@MayankGupta3090 if this is solve, can you please close this issue ticket.

**Comment by gunthercox** [comment]
I'm going to close this ticket off due to lack of activity.

**Comment by hack-r** [comment]
I actually have this issue as well after having cloned and attempted to run the example Django app. The server allows me to run the example but generates no responses and throws this error when you type. The solution is unclear to me.

**Comment by hack-r** [comment]
The migrations are what solved the problem in my case, just to be clear.
