### ISSUE TITLE
Training with the Twitter API in Django ChatterBot

### ISSUE THREAD

**Issue by jiangyuhe123** [gunthercox/ChatterBot#980]
Dear buddy,

I want to train with Twitter API in the Django ChatterBot example app. But I meet following problem when call command train. (all the Twitter key ... are set correctly)

Traceback (most recent call last):
  File "/Users/southdom/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/172.3968.37/PyCharm.app/Contents/helpers/pycharm/django_manage.py", line 43, in <module>
    run_module(manage_file, None, '__main__', True)
  File "/Users/southdom/anaconda/lib/python3.6/runpy.py", line 205, in run_module
    return _run_module_code(code, init_globals, run_name, mod_spec)
  File "/Users/southdom/anaconda/lib/python3.6/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/Users/southdom/anaconda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/southdom/Repository/ChatterBot/examples/django_app/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/southdom/anaconda/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/Users/southdom/anaconda/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/southdom/anaconda/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/southdom/anaconda/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/southdom/anaconda/lib/python3.6/site-packages/chatterbot/ext/django_chatterbot/management/commands/train.py", line 19, in handle
    chatterbot.train(chatterbot.training_data)
TypeError: train() takes 1 positional argument but 2 were given

Appreciated if you can provide some help, thanks!

**Comment by vkosuri** [comment]
http://chatterbot.readthedocs.io/en/stable/examples.html#examples I think above train examples will help you
