### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by hawskpy** [gunthercox/ChatterBot#989]
Traceback (most recent call last):
  File "chatRobot.py", line 25, in <module>
    print(chatbot.get_response(str))
  File "/Library/Python/2.7/site-packages/chatterbot/chatterbot.py", line 104, in get_response
    input_statement = self.input.process_input_statement(input_item)
  File "/Library/Python/2.7/site-packages/chatterbot/input/input_adapter.py", line 22, in process_input_statement
    self.logger.info('Recieved input statement: {}'.format(input_statement.text))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

**Comment by vkosuri** [comment]
@hawskpy did you added [Unicode header](http://chatterbot.readthedocs.io/en/stable/encoding.html#unicode-header) to your file?

**Comment by gunthercox** [comment]
@hawskpy I believe @vkosuri's diagnosis might have been correct. I'm going to close this ticket off since we haven't heard a reply from you.
